### ISSUE TITLE
Please add back-end repo to Contribute

### ISSUE THREAD

**Issue by batpad** [mapbox/osmcha-frontend#101]
The Contribute button right just links to the frontend repo. It would be nice if either the frontend repo README prominently linked to https://github.com/willemarcel/osmcha-django and mentioned it as the API code or if Contribute some-how led to a bit of text leading to both repositories. 🙇 

cc @kepta @jinalfoflia

**Comment by kepta** [comment]
This was fixed in the CONTRIBUTING.md.

@batpad if 👍  close this.
