### ISSUE TITLE
favicon for osmcha

### ISSUE THREAD

**Issue by kepta** [mapbox/osmcha-frontend#107]
We don't have a favicon :(

**Comment by kepta** [comment]
@rasagy @batpad is it possible if we can work on this right now than push it for v1.1

**Comment by rasagy** [comment]
Let’s use the beautiful [assembly icon](https://www.mapbox.com/assembly/icons/) for osm that uses negative space nicely:

![image](https://user-images.githubusercontent.com/1117531/27478025-c201d25c-582b-11e7-93f7-4b287081f5cc.png)

I’m going to make favicon images based on http://realfavicongenerator.net/

**Comment by ajithranka** [comment]
Done!

**Comment by rasagy** [comment]
This got shipped: 
![image](https://user-images.githubusercontent.com/1117531/27908401-399a299e-6269-11e7-935c-a85d77532011.png)
