### ISSUE TITLE
Browser hangs when I visit changeset url

### ISSUE THREAD

**Issue by bkowshik** [mapbox/osmcha-frontend#109]
When I visit the following url, my browser hangs. Looking at the Activity Monitor, I see that the memory used by the browser continues to grow.

- https://osmcha.mapbox.com/47514474/

On a Mac, I could `Quit` in my Firefox browser but for Chrome, I had to go the command line route.

```bash
killall -9 "Google Chrome"
```

---

cc: @kepta

**Comment by kepta** [comment]
@bkowshik as a temporary fix you can remove the trailing `/`.
Since I have figured out this is causing problem. I will fix this asap.

Thanks for reporting.
