### ISSUE TITLE
Restore links to external tools in changeset-map

### ISSUE THREAD

**Issue by planemad** [mapbox/osmcha-frontend#112]
It seems like changeset-map does not show links to various tools https://github.com/osmlab/changeset-map/issues/137#issuecomment-292494461 from within osmcha. Would be great to have these.

**Comment by rasagy** [comment]
Link to changeset related tools are up here: 
<img width="1280" alt="screenshot 2017-06-22 13 19 43" src="https://user-images.githubusercontent.com/1117531/27422929-8c753fd6-574d-11e7-9225-7481b9b46d52.png">

For the user-specific tools, we’re improving the user panel to highlight these links (#46)

**Comment by kepta** [comment]
@planemad considering the above screenshot are we missing anything in particular?
