### ISSUE TITLE
Correcting an incorrect review

### ISSUE THREAD

**Issue by planemad** [mapbox/osmcha-frontend#113]
We currently don't allow a mechanism to change the review made by another user:

**eg** This change of a new city node should have been marked bad https://osmcha.mapbox.com/changesets/48828299/ but was marked as good

How should we handle such cases?

**Comment by kepta** [comment]
@planemad The backend implementation says only the user who created it in first place can clear it or a staff account is needed.

cc @willemarcel

**Comment by kepta** [comment]
@batpad @manoharuss

**Comment by batpad** [comment]
Upgrading data team users to staff accounts is on my to-do list for tomorrow.

Then we can override reviews. @kepta will the front-end just work or will it require changes?

**Comment by kepta** [comment]
@batpad @planemad I just want to be clear with the intent of this issue.

which one is it.
@planemad from Mapbox can't change the mark review and wants the entire team to be staff.

or 
@planemad as an OSM user is disgruntled with a changeset and wants to override verify status.

**Comment by planemad** [comment]
We would want any experienced user to have the power to amend a review if it is incorrect, except their own. 

Since we have no real mechanism to evaluate an experienced user (Maybe the [HDYC verified badge](http://neis-one.org/2016/05/verified-osm-contributors/)?), lets start with the Mapbox team who are the largest power users of the tool.

**Comment by kepta** [comment]
@planemad @batpad @willemarcel Maybe the backend have a credibility score attached to every osm user, which could  be a product of her `osmcha changeset marked good/bad` + `edit count` + `age` + other sources like `HDYC`.

**Comment by planemad** [comment]
Any credibility system will be highly debated and might get trapped by bikeshedding if not well researched and optimized, HDYC already faces this problem. Lets have a simple solution that we can roll out within a day and discuss scoring separately.

**Comment by willemarcel** [comment]
> The backend implementation says only the user who created it in first place can clear it or a staff account is needed.

Right now, the API doesn't allow a staff user to override the changeset review. The staff users have the power to change the tags that another user added to a changeset.

If you want to allow the staff users to uncheck a changeset, I can change it in short time.

**Comment by willemarcel** [comment]
I believe it is solved with the change in the API that allows staff users to uncheck any changeset https://github.com/willemarcel/osmcha-django/commit/fb751cc85986919c03caab074606028cc81861a9

**Comment by kepta** [comment]
Fixed in https://github.com/willemarcel/osmcha-django/commit/fb751cc85986919c03caab074606028cc81861a9

**Comment by Locke** [comment]
@kepta did you mean to close this issue? It looks to me like the original discussion is still unresolved: how should the workflow be to uncheck a validation?

As part of the HOT project in Florida regarding Hurricane Irma we spotted vandalism done by CoastalGenius. Some of their changesets have been validated in osmcha but reverted in osm.

Maybe add a "request uncheck of validation" button or something like that, to get in contact with the person who validated or with the staff?
