### ISSUE TITLE
Display number of reviewed and harmful changesets

### ISSUE THREAD

**Issue by planemad** [mapbox/osmcha-frontend#114]
As of date there are [12327](https://osmcha.mapbox.com/?filters=%7B%22hide_whitelist%22%3A%5B%7B%22label%22%3A%22No%22%2C%22value%22%3A%22False%22%7D%5D%2C%22reasons%22%3A%5B%7B%22label%22%3A%22New%20mapper%22%2C%22value%22%3A40%7D%5D%2C%22checked%22%3A%5B%7B%22label%22%3A%22Yes%22%2C%22value%22%3A%22True%22%7D%5D%7D) changesets that have been reviewed and [2761](https://osmcha.mapbox.com/?filters=%7B%22harmful%22%3A%5B%7B%22label%22%3A%22Yes%22%2C%22value%22%3A%22True%22%7D%5D%2C%22reasons%22%3A%5B%7B%22label%22%3A%22New%20mapper%22%2C%22value%22%3A40%7D%5D%2C%22hide_whitelist%22%3A%5B%7B%22label%22%3A%22No%22%2C%22value%22%3A%22False%22%7D%5D%7D) marked harmful. 

How can we make these numbers more readily visible and presented in a way that encourages more users to participate in peer reviewing contributions to OSM? This would also communicate more readily what the project is about and why its effective to an OSM contributor.

**Comment by willemarcel** [comment]
We have three endpoints that provides stats:

* General stats: https://osmcha.mapbox.com/api-docs/#!/stats/stats_list
* AoI stats: https://osmcha.mapbox.com/api-docs/#!/aoi/aoi_stats_list
* User stats: https://osmcha.mapbox.com/api-docs/#!/user-stats/user_stats_read

**Comment by rasagy** [comment]
This might be interesting to show in the homepage, will explore this when we are working on improving it and include it in that ticket. Closing this for now.
