### ISSUE TITLE
When comment is empty the front-end breaks

### ISSUE THREAD

**Issue by geohacker** [mapbox/osmcha-frontend#121]
https://osmcha.mapbox.com/changesets/49726994

cc @kepta @batpad @ajithranka

**Comment by willemarcel** [comment]
@geohacker the comment is not empty, but the changeset seems to be empty or was redacted by DWG, I believe it's an issue to `changeset-map`

**Comment by geohacker** [comment]
Right @willemarcel 

Similar https://osmcha.mapbox.com/changesets/49343813?filters=%7B%22users%22%3A%5B%7B%22label%22%3A%22RecklessRivers%22%2C%22value%22%3A%22RecklessRivers%22%7D%5D%7D - changeset is empty

**Comment by kepta** [comment]
@geohacker @willemarcel any ideas on how we should show it in frontend.

**Comment by ajithranka** [comment]
We can't detect empty / redacted changesets on real-changesets S3. So for now, maybe just show a cleaner error message?

**Comment by willemarcel** [comment]
@kepta I think we should show a message alerting that the changeset is empty

**Comment by rasagy** [comment]
This is how it looks like right now:

<img width="1280" alt="screenshot 2017-06-28 12 22 06" src="https://user-images.githubusercontent.com/1117531/27632309-f50409a4-5c18-11e7-8c2e-1495d67dab46.png">

We should ditch the red background and make the error notification more helpful.

**Comment by kepta** [comment]
We are now displaying 
`[id] does not have a comment.`
Closing this.
