### ISSUE TITLE
Don't add default start date if visiting from URL

### ISSUE THREAD

**Issue by batpad** [mapbox/osmcha-frontend#122]
Not sure how best to handle this.

But steps to reproduce:

Go to filters, clear the date, make a search.

Then, share that URL and try opening it up - the interface adds a start date automatically.

**Comment by kepta** [comment]
@batpad @geohacker  This is a complicated one. As per our conversation,
There are the two states we want to manage.
`date__gte as null` for an explicit empty start date.
and `` (no date__gte key) for using the default date.
