### ISSUE TITLE
Browser resize triggers a page reload

### ISSUE THREAD

**Issue by ajithranka** [mapbox/osmcha-frontend#123]
![resize](https://user-images.githubusercontent.com/11095038/27418798-1e9236f2-573b-11e7-8c25-9058101be6f6.gif)

cc: @kepta @geohacker

**Comment by bkowshik** [comment]
Changing the font size with `Cmd+` and `Cmd-` also triggers the same behaviour.

![zoom](https://user-images.githubusercontent.com/2899501/27422605-6b0e2390-574c-11e7-85dd-3fdba0fa6fb5.gif)

**Comment by kepta** [comment]
This is out of the scope for current releases.
Let reopen it when we are a bit more stable
