### ISSUE TITLE
Link to see changesets of a user

### ISSUE THREAD

**Issue by willemarcel** [mapbox/osmcha-frontend#126]
Issue opened by @planemad in https://github.com/willemarcel/osmcha-django/issues/76 that I think is relevant.

> The usual action to inspect a new or suspicious user is to inspect other changes by the same user to find any further edits that need fixing https://osmcha.mapbox.com/47173090
> 
> Currently this involves going to the osmcha homepage, manually typing the username and make sure to change the filters to show all. This should rather be a single step process from any changeset page. Maybe a small magnifying glass next to the username can provide such a link.

**Comment by rasagy** [comment]
@willemarcel Definitely useful, @ajithranka is working on having this as part of the User panel.

**Comment by kepta** [comment]
@rasagy this functionality was implemented in this #129

cc @ajithranka
