### ISSUE TITLE
The user icon is broken for long names

### ISSUE THREAD

**Issue by kepta** [mapbox/osmcha-frontend#131]
https://osmcha.mapbox.com/

**Comment by rasagy** [comment]
@kepta Are you referring to the alignment issue like:

![image](https://user-images.githubusercontent.com/1117531/27483700-23f50cd2-5844-11e7-94d3-b975eac3f859.png)

https://osmcha.mapbox.com/changesets/49760365

**Comment by kepta** [comment]
Yes @rasagy
