### ISSUE TITLE
can I filter a boundary (zb Netherlands)

### ISSUE THREAD

**Issue by Commodoortje** [mapbox/osmcha-frontend#133]
Can I filter a boundary zb the Netherlands?
At this moment I can create a BBox but there are also edits from Germany and Belgium in this filter.
[picture](https://www.dropbox.com/s/zb5w3cp3afc7dcc/2017-06-26_12-40-37.jpg?raw=1)

**Comment by kepta** [comment]
At the moment you cannot. But we will soon be shipping out the filter where you can upload the geometry.

**Comment by Hjart** [comment]
I'd appreciate having this too. I'm usually interested in what's happening within the borders of Denmark (the country) only, so I'd appreciate being able to select "Denmark" as a filter (or even one of the 5 administrative regions). The borders are in OSM allready, so it shouldn't be necessary to upload any geometry.

**Comment by eneerhut** [comment]
Also useful for the Mapillary team. Linking image capture challenges with edit challenges will be a lot easier when we can search changeset comments easily within a given area.

**Comment by Hjart** [comment]
Similar issue here: #208

**Comment by tridip1931** [comment]
Duplicate. I am closing this. We are implementing this feature request.
