### ISSUE TITLE
old queries / URL parameters no longer supported

### ISSUE THREAD

**Issue by govvin** [mapbox/osmcha-frontend#134]
It seems that the new version is silently ignoring older queries constructed from URL parameters

**Comment by kepta** [comment]
I am afraid but the current filter URL is backward incompatible. 

Is it possible if you could use the new filters page to create the same URL parameters?

**Comment by govvin** [comment]
Thanks for the response, @kepta.  I'm positive it could be done, but could be tedious with URLs like this:
`http://osmcha.mapbox.com/?usernames=+Brad-M%2C+EAA22%2C+Leipo+Spes%2C+imeeperezveedor%2C+digmaan%2C+crops+production&bbox=120.47048594404993%2C13.552746258220381%2C121.83257592681281%2C14.251082389674593&is_suspect=False&is_whitelisted=True&harmful=None&checked=All&all_reason=True
`

**Comment by kepta** [comment]
No further action.
Closing for now.
