### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by james2432** [mapbox/osmcha-frontend#139]
I get to the "Read preferences" in the popup window, but when I click authorize the popup window goes blank and I am not signed in on the main page.

**Comment by willemarcel** [comment]
Hi @james2432 

Check if you are using the https url: https://osmcha.mapbox.com/

**Comment by james2432** [comment]
Login only works on HTTPS, if that is the case there should be a 301 redirect or an HSTS Preloading insctruction to not use HTTP

**Comment by ajithranka** [comment]
Sorry @james2432, we'll be fixing this soon.
