### ISSUE TITLE
Have all the error messages in first person

### ISSUE THREAD

**Issue by jinalfoflia** [mapbox/osmcha-frontend#145]
Will it be a good idea to have these error messages in the first person. For example: Instead of `User does not have permission to uncheck this changeset.` we could make it more personal: `You do not have permission to uncheck this changeset.`

We know that there is going to be just one user using this tool, and these messages sound friendlier.

Thoughts @rasagy @kepta @ajithranka?

**Comment by tridip1931** [comment]
Stale. I am closing this.
