### ISSUE TITLE
A couple of UI appearance suggestions

### ISSUE THREAD

**Issue by DaveF63** [mapbox/osmcha-frontend#15]
Hi
I'm finding this project very useful.

Could changeset descriptions be added to the dialog so it can been read in fullscreen mode? It's useful as a guide as to what was edited.
Could the dialog be collapsible to an icon & slightly transparent when open?

![capture](https://cloud.githubusercontent.com/assets/9528328/25290172/9f42241c-26c4-11e7-9593-dfb8c69b5bfb.JPG)

**Comment by ajithranka** [comment]
Thanks @DaveF63!

These changes should be part of changeset-map. Moving to [changeset-map#150](https://github.com/osmlab/changeset-map/issues/150).
