### ISSUE TITLE
Add filter for current/receive blocks

### ISSUE THREAD

**Issue by simonpoole** [mapbox/osmcha-frontend#166]
The API can return information on the number of past and currently active blocks http://wiki.openstreetmap.org/wiki/API_v0.6#Details_of_a_user 

It would be a good idea if we could filter on blocks and potentially have chagesets from users that have received say, more than one block, flagged.

**Comment by batpad** [comment]
cc @willemarcel - is this something that seems reasonable to add to the `osmcha` code and hit that API for each changeset that comes through to check if the user who made the changeset has any blocks and if yes, flag with a reason like "User has blocks" or so? If this seems doable, we can create a ticket in `willemarcel/osmcha` and close here.

Thanks for the issue, @simonpoole !

**Comment by willemarcel** [comment]
@batpad Yes, It's a very good idea!

**Comment by willemarcel** [comment]
It's already implemented and in production, so @kepta can close it.
Thanks, @simonpoole !
