### ISSUE TITLE
[UI Discussions] Filters

### ISSUE THREAD

**Issue by batpad** [mapbox/osmcha-frontend#17]
cc @kepta

**Comment by rasagy** [comment]
Following up from #11, let’s use this ticket to iterate on the Filters view.

First, I took a shot at going through the [currently available filters](https://github.com/mapbox/osmcha-frontend/blob/master/src/config/filters.json), categorizing them and picking the most frequent ones (based on user feedback in #2):

![osmcha filters](https://cloud.githubusercontent.com/assets/1117531/26296781/d21f6c6e-3eed-11e7-9081-506f23db32d3.png)
_Fields in **bold** were used more often, flags were earlier called suspicious reasons_

Based on the sketches shared in https://github.com/mapbox/osmcha-frontend/issues/11#issuecomment-296993601, this page needs:

1. Option to load a saved filter
2. List of filters (separate frequent and rest of the filters)
3. CTA

## First draft

This design takes the layout from the changeset detail page forward, and is similar to the current OSMCHA layout (two-column, horizontal label+input fields). I’ve added a subtle background to highlight the above categories in four _chunks_:

![filters v4](https://cloud.githubusercontent.com/assets/1117531/26297160/58941758-3eef-11e7-80d4-d6e932eb21fd.png)

We can focus on visually highlighting the priority of CTA during the visual design phase, and work on ensuring each field has a smart default and help text. The left-hand changeset list might not be relevant while setting the filters, and we can explore ways to hide/dim it in the visual design phase.

Would love some feedback on the copy (field labels), prioritization and order. cc @planemad @maning @manoharuss 🙇 

cc @ajithranka @kepta @batpad

**Comment by manoharuss** [comment]
@rasagy Awesome ticket. 

Quick feedback, we are not using `Powerful editor` property in any of the filter or workflow as of now.

**Comment by kepta** [comment]
Closing this ticket, as it has gotten out of date.

**Comment by rasagy** [comment]
Continuing the filter conversation here (instead of #56) so we have one dedicated issue for tracking this.

Based on our interviews and user testing, filters are still complex, and two major feedback emerges:
- Filters should be categorized by use case, so it’s easy to see all related filters
- Filters should be ordered to show the most frequently used fields first

Apart from this, we have a pretty extensive set of filters, and it’s not very easy to understand them all. We should have more standardized names & better descriptions for each filter.

**Comment by rasagy** [comment]
Let’s continue using the single column approach, but make way for descriptions and headers for categories, like:

![filters - single column layout with description](https://user-images.githubusercontent.com/1117531/27063674-9ff981c8-5010-11e7-8654-503274c4e9d6.png)

Moving the call-to-action buttons on the top right to stay consistent with our changeset details page (thanks @kepta for that!), and showing `Reset` as a link to show secondary action.

The description of the field should show up only when the filter is active (mouseover or input field is active)

Here’s the proposed order of filters with categories:

### Frequently used filters
**Changeset created between:**
_Description_: Set the date range to view changesets created during that duration.
_Fields_: [ DD/MM/YY ] (From) + [ DD/MM/YY ] (To)
- [ ] We should mention more on defaults here

----

**Region/Bbox:**
_Description_: Enter the Bbox values (S,W,E,N) or use the map button to specify an area to filter changesets in that area. [Read more about how this works.](#)
_Fields_: [_____________] (Enter Bbox value) + [Map] (Draw Bbox on map)
- [ ] We should give a proper placeholder text here

----

**Comment:**
_Description_: Enter keywords separated by comma to filter changesets that mention any of the keywords in the comment. Not case-sensitive.
_Fields_: [ hotosm, import, fixme, … ]
- [ ] Confirm that the API supports comma separated values

----

### Automated flagging

**Flagged status:**
_Description_: Choose to view only changesets that have been flagged, not flagged, or all. Read more about [how changesets are flagged](#).
_Fields_: ● Flagged ○ Not flagged ○ All changesets
- [ ] Confirm if we need to explain flagging here, and if _Automated flagging_ is a good header


----

**Flagged for:**
_Description_: Select one or multiple reasons that a changeset might be flagged for. Read more about [how common flag reasons work](#).
_Fields_: [ No reason selected v ] (Start typing or pick from the list)
- [ ] Need to fix minor bugs with the dropdown button not working
- [ ] Confirm if we can add explanation for individual reasons


----

### Reviewed by users

### Changeset metadata

(Will add more details here)

cc @kepta @batpad

**Comment by kepta** [comment]
@rasagy could you with the help of @willemarcel  help in getting better descriptions for the filters.

The filters.json file could be found [here](https://github.com/mapbox/osmcha-frontend/blob/master/src/config/filters.json)

**Comment by kepta** [comment]
filters got a ui uplift in #67 
closing this

**Comment by willemarcel** [comment]
Some suggestions to a better filter organization:

* The **Basic** section could have also: `bbox size bound` (that one needs to be together with bbox) and, maybe, `comment` because it is a very important field.
* Validation section should have also `check date`, `checked by`, `tags` and `Harmful`
* `Source` should go to **Changeset Data** section
* In **Changeset Data** section, order the fields by input type. I think it makes easy to the user find what he wants.

**Comment by kepta** [comment]
@willemarcel I just deployed v0.23, what do you think?

**Comment by willemarcel** [comment]
@kepta great! It's excellent! My only suggestion is to put the `bbox size bound` next to the `bbox` field

**Comment by willemarcel** [comment]
But I think it's not a priority, We could wait for one month. We introduced a new field to store the area of the bbox of the changeset, but as it's only filled in the changesets that were imported after the system upgrade, it will hide a lot of changesets from the results.

**Comment by kepta** [comment]
Closing this ticket.

**Comment by willemarcel** [comment]
> @kepta great! It's excellent! My only suggestion is to put the bbox size bound next to the bbox field

Now I think it's already a good time to give more visibility in the interface to the **Bbox size bound**.
