### ISSUE TITLE
Add AoI RSS feed link

### ISSUE THREAD

**Issue by willemarcel** [mapbox/osmcha-frontend#171]
I'm submitting a **feature request.**
 

## *Brief Description*
We added RSS feeds to AoIs, it would be good to add a link to it in the Saved Filters section:

![captura de tela de 2017-08-04 10-43-00](https://user-images.githubusercontent.com/666291/28971314-e2766128-7901-11e7-82fe-6b1ba3ebfda1.png)

URL example: https://osmcha-django-staging.tilestream.net/api/v1/aoi/37334b0f-1c0b-4adc-a504-9f3a76a59afa/changesets/feed/

**Comment by kepta** [comment]
@tridip1931 can you look into this?

Feel free to ask any doubt or if you are stuck.

**Comment by tridip1931** [comment]
@kepta 
I am able to add icon, I also know aoi id is required for creating the RSS link which I got from redux tool. I think I would need help to figure out in the code how should I call the aoi ID and put it in a link.

**Comment by kepta** [comment]
@tridip1931 if you get the AOI-id, I think that should be enough to create a link for RSS feed.
What do you wanna call ?

**Comment by tridip1931** [comment]
Added RSS link. Closing this ticket.
