### ISSUE TITLE
Visibility of Bbox size bound

### ISSUE THREAD

**Issue by kepta** [mapbox/osmcha-frontend#173]
## *Brief Description*
We need to make the bbox size bound filter more prominent. 

## What is the motivation / use case for this feature?
Currently it is not linked to the map bbox query and the user has to dig in to find out how to limit the size. And in general it is a bit unclear how to filter by a size bound.

Lets use this ticket to discuss on how to implement this.

cc @willemarcel @rasagy

**Comment by willemarcel** [comment]
We could only activate the `bbox size bound` input if the BBOX is defined.

Other suggestion I have is to change the presentation to be something like:
**Ignore changesets whose bbox area is larger than `< number input >` times your filter area**.

If the user doesn't touch it, don't apply the filter.

**Comment by willemarcel** [comment]
@kepta I think this issue was solved by https://github.com/mapbox/osmcha-frontend/pull/188
