### ISSUE TITLE
add Level 0 editor as an option to "Open with" changesets

### ISSUE THREAD

**Issue by govvin** [mapbox/osmcha-frontend#179]
## *Brief Description*
[Level 0](http://level0.osmz.ru/index.php) is an advanced editor that's perfect for quick edits

## What is the motivation / use case for this feature?
To quickly fix errors or issues requiring minor edits. Minor issues including typographical errors, or incorrect or incomplete tags.

## What  is the current behaviour, (attach relevant screenshots) ?

![image](https://user-images.githubusercontent.com/5821688/29646681-7d8ce8d4-88b7-11e7-8043-d0ba05e9ae42.png)

## What  is the expected behaviour ?
Include Level 0 among available editors.

**Comment by kepta** [comment]
@tridip1931 can you look into this>

**Comment by tridip1931** [comment]
@govvin @kepta Can you give me sample url that contains level 0 link with changeset id?
I believe level 0 do not parse by URL.

**Comment by govvin** [comment]
You may use the url query parameter

- a node: ` http://level0.osmz.ru/?url=node/240095754`
- a changeset: `http://level0.osmz.ru/?url=changeset/51391460`

**Comment by tridip1931** [comment]
Thanks @govvin 👍
