### ISSUE TITLE
Response times overpass-cfn-production.tilestream.net

### ISSUE THREAD

**Issue by mmd-osm** [mapbox/osmcha-frontend#187]
Not sure if this the right repo to report and track this issue, otherwise please provide some pointers to a more suitable place.

I noticed some that some of the changeset visualizations are being served by overpass-cfn-production.tilestream.net as a backend, which tends to take some time. That's especially relevant for older changesets, which are not being served from aws s3 cache.

For illustration purposes, here's the kind of response time I would expect based on the same achavi queries which are also in place for OSMCha: http://5.9.84.147/achavi2/index.html?changeset=16156126 vs. https://osmcha.mapbox.com/changesets/16156126

BTW: you can also test this via https://dev.overpass-api.de/api_mmd/interpreter which has an https endpoint.

**Comment by kepta** [comment]
cc @batpad @geohacker

**Comment by batpad** [comment]
@mmd-osm that is correct. For older changesets that we don't have in the s3 cache, we query our own overpass instance for results (so as to avoid overloading the main instance).

Thanks for identifying that this seems slower than the main overpass instance - we are planning for an overhaul of our overpass backend infrastructure in the next few weeks anyways, hopefully that improves the case for older changesets.

Thanks for flagging! Closing here though as no next actions.

**Comment by mmd-osm** [comment]
> Thanks for identifying that this seems slower than the main overpass instance

That's wasn't exactly the main overpass instance, but a dev instance.

> we are planning for an overhaul of our overpass backend infrastructure in the next few weeks anyways

Great to know, in case you have any questions on how to speed things up, always feel free to reach out: https://listes.openstreetmap.fr/wws/info/overpass

**Comment by batpad** [comment]
> Great to know, in case you have any questions on how to speed things up, always feel free to reach out: https://listes.openstreetmap.fr/wws/info/overpass

Thank you so much @mmd-osm ! We probably will :-)

**Comment by mmd-osm** [comment]
> we are planning for an overhaul of our overpass backend infrastructure in the next few weeks anyways, hopefully that improves the case for older changesets.

Just wondering if this task is completed now, with `overpass.maptime.in` being the new server, as per https://github.com/mapbox/osmcha-frontend/pull/211? Not sure if you've already noticed that there's still quite a large gap in response times compared to main instance.

**Comment by batpad** [comment]
> Not sure if you've already noticed that there's still quite a large gap in response times compared to the main instance.

I believe this is due to still running an older version of Overpass. Will look into what the upgrade path looks like and possibly reach out for help. Thanks for the flag @mmd-osm .

**Comment by mmd-osm** [comment]
FYI: I used endpoint https://lz4.overpass-api.de/api/interpreter for my tests, using the following prototyping instance: https://dev.overpass-api.de/tmp/psv/osmcha (patched version with disabled S3 caching).
