### ISSUE TITLE
Management of user Area Of Interest / Saved Searches

### ISSUE THREAD

**Issue by batpad** [mapbox/osmcha-frontend#19]
cc @kepta @ajithranka @rasagy

**Comment by rasagy** [comment]
@batpad Going to bake in a `Saved Filter` option in the filters page, but wondering if we should have a `Manage` button next to it [like in this sketch](https://github.com/mapbox/osmcha-frontend/issues/11#issuecomment-296993601).
 
How does the AoI work? Do we need a CRUD where one can have a set of AoI and then just pick from the drop-down in the Bbox section? If yes, I think it would help to move the _managing_ part of Filters & AoI 

```
               +------------------------------------+
Saved Filters: |                                  v |
               +------------------------------------+
```

```
      +--------------+ +----------+ +---------------+
Bbox: |              | | Set Bbox | | Saved Areas v |
      +--------------+ +----------+ +---------------+
```

```
+---------------+
| Saved Areas v |
+---------------+
| Bangalore     |
|               |
| Top Metros    |
|               |
| Tier-2 Cities |
|---------------|
| Upload Area   |
+---------------+
```

**Comment by willemarcel** [comment]
@rasagy `AoI` has a `name`, `uuid` (it will compose the url), a `filters` field (with the saved filter params) and a `geometry` field (with the same geospatial area that is present in the filter). When creating it, the user need to inform just the `name` and `filters`. The backend will take the geometry from the `filters` and store it in the `geometry` field.

We have endpoints to list the AoI's of a user, to get detail of an AoI, to update and delete it. Finally we have endpoints to list the features and changesets that match the AoI.

**Comment by rasagy** [comment]
Oops, it seems like I completely misunderstood what AoI & Filters mean in this context. @willemarcel thanks for the explanation, this helps.

Based on a quick chat with @batpad I don’t think we’ll support saving _areas_ — which are individual geojson that you can upload and then get a drop-down like I added in the above comment. Instead, we’ll save the whole set: Filter+Bbox/geometry as geojson as one entity. 

For the Bbox filter, we’ll then have something on the lines of:

```
      +--------------+ +----------+ +-----------------+
Bbox: |              | | Set Bbox | | Upload Geometry |
      +--------------+ +----------+ +-----------------+
```

**Comment by willemarcel** [comment]
Great, @rasagy!

The geometry field of an AoI can store any geometry type, so it's interesting to have the possibility of uploading geometry or drawing it.

**Comment by kepta** [comment]
This was implemented.
