### ISSUE TITLE
pokemon nest??

### ISSUE THREAD

**Issue by DaveF63** [mapbox/osmcha-frontend#193]
Hi
Why has my changeset been flagged with this:

![image](https://user-images.githubusercontent.com/9528328/30184479-1a3181ae-9416-11e7-9c5a-9ba02735bac3.png)

https://osmcha.mapbox.com/changesets/51824005/

**Comment by willemarcel** [comment]
@DaveF63  Some filters are wrongly considering the user as a 'new user'. I'll try to work on it soon. 'Pokemon nest' are some features that people add to the map expecting that it would influence the pokemon go game.

**Comment by willemarcel** [comment]
We had some problems detecting new users in the past, but I believe it's fixed now.
