### ISSUE TITLE
Monitor Cadastral points man_made=survey_point was moved

### ISSUE THREAD

**Issue by bgirardot** [mapbox/osmcha-frontend#201]
These points should almost never move without a very good source tag like "survey"

They are critical and accidental moves are a problem. Easy to revert though as the are usually just simple points.

Use case: Newbie mapping well survey Island, during Hurricane Irma. See photo of points that would be very damaging if moved by new mappers helping during a hurricane or other major event.

![2017-09-17_07h43_21](https://user-images.githubusercontent.com/265831/30520535-be2be5d8-9b7d-11e7-8d0e-9eff8a2826fb.png)

**Comment by kepta** [comment]
@bgirardot can you please stick to the issue ticket template. It helps us a lot ✌️

**Comment by bgirardot** [comment]
I'll look again, but where to leave a feature request is not clear in the osmcha website. It links here.

Also the template references a non existent directory the doc/ directory, it is not in this repo. I lost confidence in it then :) Or I am just not understanding something. that is usually the case.

**Comment by bgirardot** [comment]
Ok, I followed the template which was bug report focused, i hope it helps. sorry for ignoring the template the first time, just did not seem to appy to me, but i saw other issues that looked like feature requests.

resubmitted as issue #202
