### ISSUE TITLE
Feature Request: flag any change to man_made=survey_point

### ISSUE THREAD

**Issue by bgirardot** [mapbox/osmcha-frontend#202]
Note: Make sure a ticket for this does not already exist
done, no word survey in issues
Note: Make sure to refer to project docs / README to make sure tool is used correctly
Directory does not exist in this repo.
Consulted the link on contributing at the top of this new issue page, it does not mention how to make a feature request, only bug report.

## *Brief Description*
Track and report on any changes to man_made=survey_point nodes

## What is the motivation / use case for this feature?
These are critical nodes that accidentally or intentionally mis locating can have significant effects.

## What  is the current behaviour, (attach relevant screenshots) ?
not something that gets flagged for review

## What  is the expected behaviour ?
please flag it for review

## When does this occur ?
When someone moves a node with the key=value of man_made=survey_point

## How do we replicate the issue ?
Feature request

## Please tell us about your environment:
Win7, chrome

## Other Information / context:
Just a feature request

Here is screenshot of a typical area where this use case is very reverent, new mappers mapping in a well survey area.

![2017-09-17_07h43_21](https://user-images.githubusercontent.com/265831/30521151-dccb9e24-9b88-11e7-9797-0e9ce3dcf85e.png)

**Comment by planemad** [comment]
This should be a compare function on https://github.com/mapbox/osm-compare to flag any movement to `man_made=survey_point` nodes.

**Comment by batpad** [comment]
cc @willemarcel - do you think writing this compare function might be something you can take up, if we feel it's a good idea?

**Comment by willemarcel** [comment]
@batpad Excellent! I was thinking about to do it.

**Comment by willemarcel** [comment]
@batpad @planemad it's done in https://github.com/mapbox/osm-compare/pull/181

**Comment by kepta** [comment]
@willemarcel can we close this ticket?
