### ISSUE TITLE
Filter by admin area

### ISSUE THREAD

**Issue by joostschouppe** [mapbox/osmcha-frontend#208]
A lot of people like to watch "their area". Often this will coincide with some admin area, for example their city, region or country. It would be nice to be able to use these for filtering osmcha. Especially country outlines seem important, but maybe we could use admin_level 3 and 4 as well. There are of course non-osm devisions you could use as well.

**Comment by Hjart** [comment]
This is similar to: #133

**Comment by batpad** [comment]
The API already allows filtering by arbitrary GeoJSON (multi)polygons. Perhaps the solution here is two steps:

 - Expose just a text-box or so in the frontend for users to paste arbitrary GeoJSON (multi)polygons
 - As a second step, create a nice map  widget for users to optionally draw polygons to filter by

Hopefully this can be accomplished, @willemarcel ?

We still have the larger issue that what we have to filter changes by is the changeset bounding box and not the locations of individual edits, but that's a limitation that will need to be communicated clearly in the UI to minimize user confusion.

**Comment by Hjart** [comment]
I would prefer an option to select an (administrative) area already defined in OSM to avoid going through the hassle of entering or drawing my own polygons

**Comment by batpad** [comment]
> I would prefer an option to select an (administrative) area already defined in OSM to avoid going through the hassle of entering or drawing my own polygons

Ah, interesting :-)

This does seem like it would probably be the nicest solution - is there a good way to directly use OSM for this sort of thing (drill-down admin areas and get back polygon data for them), or would we have to rely on another service, or have a script to build up this list ourselves in the database and a way to periodically update it? Will leave it to you @willemarcel to figure out the best solution :)

**Comment by Hjart** [comment]
How about zooming in on an area on the map (filter setup) like we already do, then (when zoomed in sufficiently) have buttons that will find admin boundaries in that area via Overpass), which we can then choose between?
I would find this extremely handy

**Comment by willemarcel** [comment]
Solved and deployed. Check: https://osmcha.mapbox.com/filters

Today I'll publish a diary post about this.
