### ISSUE TITLE
[UI Discussions] Changeset List

### ISSUE THREAD

**Issue by rasagy** [mapbox/osmcha-frontend#21]
Following up from #11, let’s use this ticket to iterate on the Changeset list:

![c - changeset-list - v2](https://cloud.githubusercontent.com/assets/1117531/25932677/65a95d8a-3630-11e7-95a8-76c7106dc7fc.png)
_(Initial mockup)_

Based on my discussions, here’s the list of fields in the order of importance:

1. Verified status — Not reviewed, harmful, not harmful (Helps to skip already verified changesets)
1. Changeset comment (Most descriptive: reverts/HOT tasks vs gibberish/foul language etc.)
2. Count of added/modified/deleted objects (Gives context on the scale of the changeset)
2. Flagged reason
3. Date created
3. Tags added by user (Not as important in the list view)
4. User name (Might have cues like gibberish characters, or suffix like _revert)
5. Changeset ID (Helps to lookup details on other apps, but not as relevant to see in the list)
6. Verified by username (Useful in only edge cases)

Apart from this, a state change (visual attribute) that shows:

- Changesets not opened yet
- Current changeset being viewed (selected)
- Changesets that have been opened

Here’s the mockup with the above details:

![c - changeset-list - v3](https://cloud.githubusercontent.com/assets/1117531/25932791/1a48e724-3631-11e7-9e15-4fda88c4ee77.png)

Specific details:
- Bar on the left indicates verified status (Harmful, not harmful, not reviewed)
- Background color of list item + font-weight of comment indicates opened/selected state

cc @kepta @ajithranka @batpad @geohacker @Rub21

**Comment by rasagy** [comment]
**Things to discuss:**

- Should we only show the created/modified/deleted number if it’s non-zero, like in current prototype?
- Should we replace the flagged reason with the user tags for items that have been verified? Will that be helpful or confusing?
- Once you apply the filter, you’ll directly see this view (no table view to avoid drastic change in the context). Should the first changeset be selected (opened) by default, or should the main section stay empty till the user selects a list item?

Thoughts @planemad @maning @manoharuss & others? Happy to do a quick sync today afternoon for more feedback.

**Comment by bsrinivasa** [comment]
@rasagy The changeset list section looks awesome! 😄  Especially thanks for the `specific details`. 

> Once you apply the filter, you’ll directly see this view (no table view to avoid drastic change in the context). Should the first changeset be selected (opened) by default, or should the main section stay empty till the user selects a list item?

I would suggest to NOT select/open the first changeset automatically but also against displaying an empty page. Would love to see a Home/Welcome page as a default when the space is empty (something like our beloved JOSM welcome page 😛 )

> Should we replace the flagged reason with the user tags for items that have been verified? Will that be helpful or confusing?
 
Yes. This is a good idea. I'm 👍  for already reviewed harmful changesets, only when reason filters are applied.

**Comment by manoharuss** [comment]
> Should we only show the created/modified/deleted number if it’s non-zero, like in current prototype?

This sounds reasonable.

> Should we replace the flagged reason with the user tags for items that have been verified? Will that be helpful or confusing?

@bsrinivasa 
Tags = Manually given tags by reviewers (Intentional, Unintentional, Resolved, Unresolved etc)
Suspicious reasons = Reasons pushed by detectors (Park added by new user, Waterbody added by new user, Edited a major lake)

Nope. Let us keep these separate. Often when we share harmful changesets through our diary posts and mailing lists, we do give them link to each changeset on OSMCha. It is important that the community members also see which reason(detector) the edit has been flagged by and not just the manual tags given by us.

If these are not visible on reviewed changesets that also have tags, to know which detector flagged that changeset later in time is going to need further technical work which is not ideal.


> Once you apply the filter, you’ll directly see this view (no table view to avoid drastic change in the context). Should the first changeset be selected (opened) by default, or should the main section stay empty till the user selects a list item?

Neutral. But I don't think we have anything specific to show as such on the main section for every search retrieval. Let's have the first changeset in the retrieved list selected by default.

**Comment by rasagy** [comment]
Thanks @bsrinivasa & @manoharuss!

>It is important that the community members also see which reason(detector) the edit has been flagged by and not just the manual tags given by us.

This ticket is dedicated to the left sidebar, sorry should have been clearer in my question. See the image below:

<img width="1021" alt="c_-_changeset-list_-_v3_png" src="https://cloud.githubusercontent.com/assets/1117531/25948147/f7154a2e-366f-11e7-860c-b30386b9c5ae.png">

In this left bar, for items that have been _already verified (harmful/not harmful)_, would it be more useful to see what the user tagged this as instead of why this was flagged (aka suspicious reason).

Here’s how the fields would appear with the user tags instead of flagged reasons:

![c - changeset-list - v3 with tags](https://cloud.githubusercontent.com/assets/1117531/25948358/b78aeae8-3670-11e7-857c-ad14f1d9210a.png)

We can explore _how to communicate the difference_ (between flag & tag) if this is valuable.

**Comment by willemarcel** [comment]
> Should we only show the created/modified/deleted number if it’s non-zero, like in current prototype?

I prefer to have all the numbers. When you see always the three numbers you understand it directly. If you have just one or two, you need to learn or think about what does it mean.

> Once you apply the filter, you’ll directly see this view (no table view to avoid drastic change in the context). Should the first changeset be selected (opened) by default, or should the main section stay empty till the user selects a list item?

What do you think about to show the changesets bbox over a map?

**Comment by kepta** [comment]
Closing this ticket as the majority of the things have been settled.
