### ISSUE TITLE
Prompt for login when you try to verify a changeset

### ISSUE THREAD

**Issue by joostschouppe** [mapbox/osmcha-frontend#210]
This sequence could be more user friendly:
- user arrives at OSMcha for the first time, and is not logged in
- user gets the point, checks the changeset and wants to Verify
- upon trying to mark the changeset as good or bad, you get a message you need to sign in
- clicking on that message just makes it go away

In the last step, clicking on "Sign in" within the message could trigger the "Sign in" process.

**Comment by willemarcel** [comment]
As we need to login to be able to visualize the changeset, that issue is not useful anymore.
