### ISSUE TITLE
Error loading the map in bbox and changeset views

### ISSUE THREAD

**Issue by Zverik** [mapbox/osmcha-frontend#213]
When clicking on a bbox field, an empty rectangle is drawn, nothing happens inside it.

When clicking on a changeset, the map is filled with pink color, and a message is displayed: "t is not a function". In the browser console, I found this:

```
Error: Loading chunk 0 failed.
Stacktrace:
n@https://osmcha.mapbox.com/static/js/main.0d4dc015.js:1:500
  main.0d4dc015.js:1:572518
Failed to load module changeset-map  main.0d4dc015.js:1:572518
TypeError: t is not a function
Stacktrace:
u/<@https://osmcha.mapbox.com/static/js/main.0d4dc015.js:1:206828
  main.0d4dc015.js:1:572518
Loading a <script> with source «https://osmcha.mapbox.com/static/js/0.223dba27.chunk.js» failed.
```

Firefox 55.0.3, macOS 10.11.6

**Comment by willemarcel** [comment]
Hi @Zverik 

Reload your page with `F5`. This is caused by this issue https://github.com/mapbox/osmcha-frontend/issues/212

**Comment by Zverik** [comment]
Oh, indeed. Thanks Wille!
