### ISSUE TITLE
Show all changesets for a User (not just recent) when inspecting from User panel

### ISSUE THREAD

**Issue by rasagy** [mapbox/osmcha-frontend#215]
## *Brief Description*

The link in the User Panel that allows you to view all changesets in OSMCha takes the default `start-date` (probably because no date is mentioned), which leads to filtering for only recent changesets by default. In many cases, you would end up with no changesets shown due to this.

Current link: `https://osmcha.mapbox.com/?filters=%7B%22users%22%3A%5B%7B%22label%22%3A%22USERNAME%22%2C%22value%22%3A%22USERNAME%22%7D%5D%7D`

Should append the date filter value as null: `%7D%5D%2C"date__gte"%3A%5B%7B"label"%3A""%2C"value"%3Anull%7D%5D%7D`

cc @kepta @tridip1931

**Comment by willemarcel** [comment]
Solved with https://github.com/mapbox/osmcha-frontend/commit/9ff079c3eec26db51de3e6bd86a3f7c6a6ed83f

thanks, @rasagy !
