### ISSUE TITLE
Better documentation / instructions on setting up RSS feeds

### ISSUE THREAD

**Issue by batpad** [mapbox/osmcha-frontend#216]
The RSS feature is awesome! It's just quite confusing right now as to how one gets to it, and I don't really see clear documentation in our docs of how to setup RSS feeds.

Could we as a first step just add clear instructions on setting up RSS feeds, possibly as a separate heading in our documentation?

cc @willemarcel @manoharuss @ajashton

**Comment by manoharuss** [comment]
will add a section for using RSS feature in the OSMCha about guide and update here with the pr link @batpad

**Comment by SafwatHalaby** [comment]
I wasn't aware of an RSS feature. Where can I find it?

**Comment by manoharuss** [comment]
@SafwatHalaby 👋  It is currently a bit hidden. Once the user sets a filter, it is by default `unnamed`. But once we save it with a name, we can see it in our user page.

I made a quick gif to explain how to find it. I will make sure get this added under [OSMCha about guide](https://osmcha.mapbox.com/about) this week.


![osmcharsss](https://user-images.githubusercontent.com/8921295/32146241-33aed62e-bcfa-11e7-834b-23ff7f9367bc.gif)

**Comment by manoharuss** [comment]
OSMCha guides have been refreshed in https://github.com/mapbox/osmcha-frontend/pull/232. Closing.

**Comment by manoharuss** [comment]
Updated on OSMCha https://osmcha.mapbox.com/about#saving-and-sharing-custom-filters
