### ISSUE TITLE
OSMCHA does not handle usernames changing

### ISSUE THREAD

**Issue by SafwatHalaby** [mapbox/osmcha-frontend#219]
## *Brief Description*

I changed my username from SwiftFast to [SafwatHalaby](http://whosthat.osmz.ru). When I login to Osmcha, it is still using my old username in reviews, and in my profile page. However, when I make OSM edits, the *new* username is attributed to the new changesets.  It's unclear weather Osmcha is treating SafwatHalaby as a completely distinct, unrelated user when it comes to good/bad edit statistics.

## What is the motivation / use case for this feature?

Irrelevant.

## What  is the current behaviour, (attach relevant screenshots) ?

Osmcha retains the old username when a user username changes. (However, post-change OSM edits are filed under the new username).

## What  is the expected behaviour ?

Use new username.

## When does this occur ?

When changing usernames.

## How do we replicate the issue ?

1. Login at https://www.openstreetmap.org/
2. Visit `https://www.openstreetmap.org/user/<your username>/account`
3. Change the "Display Name" field and save your changes

## Please tell us about your environment:

Irrelevant.

## Other Information / context:

This website might be useful when testing: http://whosthat.osmz.ru

**Comment by SafwatHalaby** [comment]
Here are things I tried that did not resolve this:
- Logging out and then logging in
- Clearing browser cookies / history / cache and then logging in
- Logging out, revoking oAuth via the settings at https://www.openstreetmap.org, and then logging in

**Comment by willemarcel** [comment]
I confirmed this bug and I'm solving it in osmcha-django repository. Thanks, @SafwatHalaby !
