### ISSUE TITLE
[UI Discussions] Changeset Details

### ISSUE THREAD

**Issue by rasagy** [mapbox/osmcha-frontend#22]
Following up from #11, let’s use this ticket to iterate on the Changeset details view:

![c - changeset detail - v2](https://cloud.githubusercontent.com/assets/1117531/25933047/a04e0646-3632-11e7-9cf1-bd6ff6f3814e.png)

**Key information:**

1. Main header with CTA
  - Open in (JOSM, iD etc.)
  - Verify (Harmful, not harmful)
  - Add tag (Longer list of tags that could explain actual cause, action taken, escalation etc.)
2. Changeset metadata
  - Apart from what’s visible in the changeset list, more details like Imagery, Source, Editor etc.
3. Flagged features
  - Table with links to open the individual feature page, highlight it in changeset map, open in JOSM
4. Changeset discussion
5. Changeset map

For the layout, I’m envisioning the top half with dedicated section for 2, 3, 4 and the bottom half for changeset map. This ensures that the changeset detail is always visible (for context), and you can view the flagged feature list along with the changeset map (so you can quickly inspect individual features on the map without any scrolling).

cc @kepta @ajithranka @batpad @geohacker

**Comment by rasagy** [comment]
**Things to discuss**:

- How should the layout work responsively?
- How should the changeset map layout change to accomodate the responsive layout? This conversation can help push https://github.com/osmlab/changeset-map/issues/133 forward.
- How should changeset map open full-screen (Like full-screen video? In a new tab? Draggable layout?)

Thoughts @planemad @maning @manoharuss & others?

**Comment by bsrinivasa** [comment]
@rasagy , The changeset detail page looks good. Also curious to check out ideas on how changeset map and discussion module could be fit in the current layout design. 

> How should changeset map open full-screen (Like full-screen video? In a new tab? Draggable layout?)

Would suggest for changeset map to just expand in shape to about 75% (or a bit more than that) of the screen (as in a photo viewer experience) and when clicked outside the map, the page should return back to the original state which displays changeset details and the normal changeset map. I wouldn't recommend opening in a new tab as it would be again tedious to open - close and switching tabs.

**Comment by rasagy** [comment]
Since a common usecase with OSMCHA is to have a split-screen layout (OSMCHA + JOSM/iD), we need to make sure the layout is responsive here’s how the layout could look like on a 800x600 screen:

![c - v2 tablet](https://cloud.githubusercontent.com/assets/1117531/25933448/7cf290b6-3634-11e7-9340-77adbede0082.png)

We could push the 2, 3, 4 sections in a single layout (scrollable) and keep the changeset map pinned to the bottom. But with the list showing, the horizontal space will be pretty limited for the map.

![c - v2 tablet sidebar](https://cloud.githubusercontent.com/assets/1117531/25933449/7cf2b104-3634-11e7-8b1b-e62afefdfca4.png)

Collapsed view where the sidebar can be shown _on top of_ the details page when you click on the hamburger icon.

This still requires a lot more iterations to nail down, will work on this once we have clarity on how the details screen looks.

**Comment by willemarcel** [comment]
Good ideas, @rasagy !

I think it's not necessary too much space for "Flagged features" in the first image, so I would adjust its section height to the same of the changeset details

**Comment by rasagy** [comment]
@willemarcel Good point! @kepta also worked on a quick prototype to test this on multiple screens, and I think the overall feedback is to not do a 50%-50% split but roughly 30%-70% split so changeset map uses more space. Will iterate on this and see what works best!

**Comment by rasagy** [comment]
>Would suggest for changeset map to just expand in shape to about 75%…
@bsrinivasa Interesting feedback! Like @willemarcel mentioned, I think we can give changeset map more space by default. Let’s see if that removes the need to have a full-screen view for most cases.

**Comment by rasagy** [comment]
@kepta helped make a quick prototype to get feedback on the layout. The main feedback was that 50-50 split doesn’t work well, especially on slightly smaller screen sizes, and the changeset map should be toggle-able/expandable in some way.

Based on those inputs, @kepta, @ajithranka & I went ahead with rethinking the layout by focusing on the changeset map and adding details _around_ it.

### First iteration: Collapsable panels

![c - changeset-map ui - v4](https://cloud.githubusercontent.com/assets/1117531/26146720/d17fff4a-3b0e-11e7-97f4-bee330aaa099.png)

This combines the left panel in changeset map with other details in OSMCHA to create a set of toggle-able panels. These could open/close like accordions (at most one section open at one time).

### Second iteration: Panels as map controls

![c - changeset-map ui with icons - v4](https://cloud.githubusercontent.com/assets/1117531/26147050/ed2c1156-3b0f-11e7-9c5c-ea35178bb461.png)

Taking the above idea forward, this collapses the panels into a smaller control/icon/button, thus taking minimal space in the interface when someone wants to dive deep into the changeset map.

This approach avoids the jarring movement of clickable areas in an accordion that we saw in [Concept D](https://github.com/mapbox/osmcha-frontend/issues/11#issuecomment-297677505), and also makes each section flexible in size (for ex the `Flagged features` could be wider to accommodate the table, while the `Toggle layers` could be smaller).

![c - changeset-map ui with icons panels](https://cloud.githubusercontent.com/assets/1117531/26147157/49ccb352-3b10-11e7-836f-10313a9c73d7.png)

Let’s take this approach forward and start working on a high-fidelity design.

PS: This would require us to also update the design of the changeset map, tracking that on [this ticket](https://github.com/osmlab/changeset-map/issues/133).

**Comment by willemarcel** [comment]
Excelent!! Both are very good, but I prefer the `Panels as map controls`.

**Comment by kepta** [comment]
Closing this ticket as it has gone out of date.
