### ISSUE TITLE
How to send a feedback about an existing changeset review?

### ISSUE THREAD

**Issue by govvin** [mapbox/osmcha-frontend#221]
## I'm submitting a _question_
![image](https://user-images.githubusercontent.com/5821688/32439131-4d85301e-c328-11e7-8755-6130302ee8e3.png)
How to send a feedback about an existing changeset review?

## *Brief Description*
I'm reviewing this [changeset](https://openstreetmap.org/changeset/50614861), and noticed that it's been reviewed by another user. However, after reviewing the data further, it appears that the [changeset is actually harmful](https://osmlab.github.io/osm-deep-history/#/way/510686797). 

How can I mark the changeset as bad, or at least, leave some feedback for the reviewer?

## What is the motivation / use case for this feature?
Currently reviewing a [series of edits](https://osmcha.mapbox.com/changesets/50614861?filters=%7B%22in_bbox%22%3A%5B%7B%22label%22%3A%22121.6571%2C4.5859%2C127.3531%2C10.2320%22%2C%22value%22%3A%22121.6571%2C4.5859%2C127.3531%2C10.2320%22%7D%5D%2C%22date__lte%22%3A%5B%7B%22label%22%3A%222017-11-06%22%2C%22value%22%3A%222017-11-06%22%7D%5D%2C%22users%22%3A%5B%7B%22label%22%3A%22ErnieSarayno%22%2C%22value%22%3A%22ErnieSarayno%22%7D%5D%7D) that was made 3 months ago, and we belated realize many are actually harmful. Not all their changesets got flagged by OSMCha.

## What  is the current behaviour, (attach relevant screenshots) ?
![image](https://user-images.githubusercontent.com/5821688/32439131-4d85301e-c328-11e7-8755-6130302ee8e3.png)

## What  is the expected behaviour ?
A better way to add feedback for other reviewers, especially for us regular mappers who have no permissions to remove such tags.

## When does this occur ?
Changesets already reviewed by others.

**Comment by willemarcel** [comment]
Hi @govvin 

Right now, the only option is to send a message to the OSM user that reviewed the changeset.

**Comment by willemarcel** [comment]
Now that we have a comment feature inside OSMCha, I believe we can close it. Feedback can be sent by a comment.
