### ISSUE TITLE
[Perf] Tiles are downloaded multiple times

### ISSUE THREAD

**Issue by mmd-osm** [mapbox/osmcha-frontend#233]
## *Brief Description*
Same aerial and vector pbf files are getting downloaded multiple times when opening up a new changeset. This affects response times on a not so fast network link and results in unnecessary download of data.

## What is the motivation / use case for this feature?
This is slowing down loading of the page, as nearly 3-4MB of data needs to be loaded for each changeset. Other sites like [OSM Show Me the Way](https://osmlab.github.io/show-me-the-way/) are much quicker to show aerial imagery, as each tile is only loaded once.

## What  is the current behaviour, (attach relevant screenshots) ?
I tested this on Firefox 57. According to the following screenshot and the example of tile 22283.png, there are 8 downloads of the same file in a 300ms time interval. This happens across {a,b}.tiles.mapbox.com.

![grafik](https://user-images.githubusercontent.com/5842757/33524180-2b166dae-d818-11e7-8e02-28d43e979f08.png)

## What  is the expected behaviour ?
Load balancing across {a,b}.tiles.mapbox.com is a good thing. However, each tile should only be loaded once.

## When does this occur ?
Loading a changeset for the very first time (otherwise, tiles are being cached, so the download times won't matter anyway).

## How do we replicate the issue ?
1. Use Firefox 57 as indicated.
2. Open new Changeset
3. Check Network analysis tab in parallel

## Please tell us about your environment:
Firefox 57, Ubuntu 16.04.

Curiously, most of those excessive requests get canceled immediately when running on Chrome, and response times are much better. On Firefox this canceling doesn't seem to work here, resulting in the effect described in this issue.

**Comment by willemarcel** [comment]
Hi @mmd-osm 

Could you check the URL of the files that you think are duplicated? I checked it here and each file is different. Another evidence that every file is unique: observe the miniatures of the tiles and the size column.

**Comment by mmd-osm** [comment]
Good catch. I ran another HTTP trace now (see this attachment: [trace.txt](https://github.com/mapbox/osmcha-frontend/files/1526981/trace.txt)), to get the exact URLs called by OSMCha. And indeed, the screenshot above was tricking me a bit to believe that those are the same URLs. They're not. Nevertheless, we still got the 15s+ total loading time on Firefox.

While the GeoJSON diff was displayed fairly quickly, the full page still took around 17s to load. It seems that most of the time was really spent loading `/v4/mapbox.satellite/` in 3 different zoom levels(!) - check the HTTP trace for details. This is much quicker in Chrome, with a total loading time of maybe 3-4s.

Somehow I have the impression that Firefox just loads too much data. Maybe because of some zooming in/zooming out, which at the same time triggers the tile download.

Thanks for bearing with me.

**Comment by batpad** [comment]
I think this is a problem with the `style` we are using on changeset-map. @planemad do you think you could do a sanity check on the style to make sure we're not doing anything really weird there?

(thanks so much for flagging this @mmd-osm ! )
