### ISSUE TITLE
OSMCha down

### ISSUE THREAD

**Issue by DaveF63** [mapbox/osmcha-frontend#236]
## *Brief Description*
OSMCha appears to be down. Could someone turn it off & back on again please?

**Comment by amishas157** [comment]
@DaveF63 , Thanks for reporting the issue. This has been resolved. Feel free to report back if you see it again.

**Comment by DaveF63** [comment]
For me:
https://osmcha.mapbox.com/changesets displays after a delay of ~5 seconds (slower than previous)

http://osmlab.github.io/changeset-map still gives me a grey screen

**Comment by batpad** [comment]
We had intermittent issues in our processing pipeline over the weekend. Thank you for reporting @DaveF63 - these *should* be fixed now, please feel free to comment / re-open if you are still seeing issues.
