### ISSUE TITLE
CONTRIBUTING.md's link to CODE_OF_CONDUCT.md not found

### ISSUE THREAD

**Issue by paulmach** [mapbox/osmcha-frontend#240]
FYI, there is a link to a code of conduct that doesn't exist.

**Comment by willemarcel** [comment]
@paulmach thank you very much for noticing it!! I added it on https://github.com/mapbox/osmcha-frontend/commit/2bda0043199458c23ddd0f97f2047a1c9949244a

Soon it will be on the master branch.
