### ISSUE TITLE
"Failed to Load Page 0" message

### ISSUE THREAD

**Issue by Hjart** [mapbox/osmcha-frontend#242]
Recently (a week or 2 back) I started getting this error message whenever trying to apply a new filter or update an existing:
![failedloading](https://user-images.githubusercontent.com/9010705/34483606-ee07fa1c-efbf-11e7-84c5-213664064d44.png).
I tried resetting filters without any luck  and my network connection appears to work for everything else.
I'm using Firefox on an OpenSUSE Linux installation

**Comment by willemarcel** [comment]
Hi @Hjart 

Could you give us a feedback if this error is yet happening?

**Comment by Hjart** [comment]
It's no longer happening and since at least a week or 2, I've been able to succesfully use the filters, thank you. I
