### ISSUE TITLE
Blockers for a beta testing.

### ISSUE THREAD

**Issue by kepta** [mapbox/osmcha-frontend#25]
We are almost there with the existing [osmcha](https://osmcha.mapbox.com).
Couple of things that need to move before we start beta testing the app, next week.

### Login
___

|   |  |
|----------|-------------|
| **Status** |   Completed|
| **Info** |    The current login mechanism doesn't work in regular browsers. @wille is working on an update.   | 
| **Beta release** | Blocker | 

### Changeset Details View
___

|   |  |
|----------|-------------|
| **Status** |    functional but scope for improvement|
| **Info** |    This design is being tracked [here](https://github.com/mapbox/osmcha-frontend/issues/22). The changes mention require a UI uplift from both osmcha and changeset-map side. Would like to push it at the last of priority.   | 
| **Beta release** |  none of them are a blocker for beta testing.  | 
| **V1 release** | Up for discussion. Fix nit picks from beta testing phase. | 

### Changesetmap
___

|   |  |
|----------|-------------|
| **Status** |    functional and ok for v1.|
| **Info** |    Changesetmap has gotten a serious [refactor](https://github.com/osmlab/changeset-map/pull/153) to accommodate the needs for this project. Currently we have to unload and load changeset-map when Changeset Details View goes for loading, we should decouple cMap from this view.    | 
| **Beta release** |  good | 
| **V1 release** | ok Fix nit picks from beta testing phase. | 

### Sidebar View

|   |  |
|----------|-------------|
| **Status** |     Functional and good enough for v1.|
| **Info** |    Rasagy has some concerns our the sidebar aka changeset list, which are discussed [here](https://github.com/mapbox/osmcha-frontend/issues/21).   | 
| **Beta release** |  good,  none of them are a blocker for beta testing.  | 
| **V1 release** |  But we might need to consider the suggestions for the June 5 release.| 

### Filters View

|   |  |
|----------|-------------|
| **Status** |    non- Functional|
| **Info** | Filters page would be the major chunk of work to get to the June 5 release. Currently the design is ready and need to start on implementation.  [Ticket](https://github.com/mapbox/osmcha-frontend/issues/17) for discussion.   | 
| **Beta release** |   blocker?| 
| **V1 release** | blocker | 

### Add tags

|   |  |
|----------|-------------|
| **Status** |    Not yet picked or discussed formally |
| **Info** |    The backend allows us to add tags to a changeset. Have some concerns about how it will look and work. Need to open a ticket for it.   | 
| **Beta release** |  unknown?  | 
| **V1 release** |  unknown? | 

### Suspicious Feature

|   |  |
|----------|-------------|
| **Status** |   WIP |
| **Info** |    To get feature parity with existing osmcha. We need to be able to click on a feature and show it on the map.   | 
| **Beta release** | up for discussion ?  | 
| **V1 release** | desirable? | 

### Miscellaneous 
- [x] **Fresh data**: Get fresh data from backend
- **Fix map style**: changeset-map map style doesn't work atm.
- **Page ref in urls.**: show the page in url ?

cc @batpad @ajithranka @rasagy @manoharuss

**Comment by rasagy** [comment]
## Design master list

### Changeset View:

- [ ] Changeset details panel
- [ ] Flagged features panel
- [ ] Changeset discussions panel
- [ ] Navigation bar (CTA for Open, Verify, Tags)
- [ ] Empty states
- [ ] Error states
- [ ] Tested for edge cases (data + screen sizes)

### Changeset List:
- [ ] Individual list item — hierarchy
- [ ] Individual list item — states (Viewed, Selected, Default, Verified 👍, Verified 👎, Unverified)
- [ ] Sorting
- [ ] Pagination
- [ ] Tested for edge cases (data + screen sizes)

### Filters
- [ ] Layout
- [ ] Default states
- [ ] Interactivity
- [ ] Tested for edge cases (data + screen sizes)

### Login
- [ ] Drop-down (As overlay/slide-in panel)

cc @geohacker @batpad @ajithranka @kepta @tridip1931

**Comment by manoharuss** [comment]
![image](https://cloud.githubusercontent.com/assets/8921295/26721379/3e94bcb4-47a9-11e7-9ae4-0e027312af09.png)

It is easier if the urls in Imagery sources are shortened to only show until  the username and have a way button there, so a user can copy the complete link into clipboard to use in OSM editors.

**Comment by kepta** [comment]
beta testing has started.

Closing this ticket
