### ISSUE TITLE
Can't switch back to satellite style

### ISSUE THREAD

**Issue by bhousel** [mapbox/osmcha-frontend#250]
## *Brief Description*
If you switch to a different style, you can't switch back to satellite style.  Returning to the Map Style tab shows that it still thinks the style is Satellite (even if it isn't)

## What  is the current behaviour, (attach relevant screenshots) ?
![osmcha-satellite](https://user-images.githubusercontent.com/38784/34879897-c3a64bc4-f77c-11e7-9cf8-7b83e511d4c0.gif)

## What is the expected behaviour ?
should be able to switch back to satellite style

## When does this occur ?
always

**Comment by tridip1931** [comment]
This was fixed. Closing.
