### ISSUE TITLE
Add OSM background style option

### ISSUE THREAD

**Issue by planemad** [mapbox/osmcha-frontend#268]
## *Brief Description*
Currently the basemap for the changeset visualization are only Mapbox maps. Since these maps have only a subset of OSM features visible, often I open the changeset page to view current state of the rendered map on the OSM mapnik style. 

If we have an OSM layer as a basemap style option, one can analyze the changeset within osmcha

## What is the motivation / use case for this feature?
- Avoids having to browse to the OSM site for the latest state of the map

## Other Information / context:

- Demo code to add the OSM mapnik tiles to GL JS: https://www.openstreetmap.org/user/PlaneMad/diary/43008

**Comment by tordans** [comment]
Another suggestion: Choose the basemap based on the "best: true" option that the editor-layout-index provides for an area.

This would make checking the changeset a lot easier since this image is more likely being used for the change itself.

**Comment by willemarcel** [comment]
I added Bing imagery and I tried to add the OSM carto style, but it now requires to inform a user-agent. I didn't find a way to do it with mapbox-gl.
@tordans I like the idea of using editor-layout-index options!

**Comment by andrewharvey** [comment]
> I added Bing imagery and I tried to add the OSM carto style, but it now requires to inform a user-agent. I didn't find a way to do it with mapbox-gl.

@willemarcel can you use `transformRequest` to add a header that the OSM operations team can whitelist?
```
 transformRequest: (url, resourceType)=> {
    if(resourceType === 'Source' && url.startsWith('http://myHost')) {
      return {
       url: url.replace('http', 'https'),
       headers: { 'my-custom-header': true},
       credentials: 'include'  // Include cookies for cross-origin requests
     }
    }
  }
```
