### ISSUE TITLE
Please add Cyrillic support

### ISSUE THREAD

**Issue by mellangr** [mapbox/osmcha-frontend#270]
## *Brief Description*

OSMCha now uses the Open Sans font without Cyrillic characters. Typically, users from Ukraine, Belarus, and Russia write a comment to a changeset in their native language. The following comments have a bad look in the OSMCha interface:

![default](https://user-images.githubusercontent.com/20912330/36626742-b1e93c94-1940-11e8-8670-1fd911cf848a.png)

It would be great if full Cyrillic support was enabled. The full version of Open Sans font supports these characters.

## What is the motivation / use case for this feature?

- Mappers from Ukraine, Belarus and Russia will be pleased to use this site

**Comment by willemarcel** [comment]
Thank you very much for your report, @mellangr !

@rasagy, could you take a look on this? I suppose it can be an issue of https://github.com/mapbox/assembly

**Comment by mellangr** [comment]
Thank you, @willemarcel

**Comment by willemarcel** [comment]
@mellangr sorry for my lack of knowledge about Cyrillic.... would you mind giving me more details about what is wrong? I compared the comment text in osmcha with the OSM website and api and it looks the same. I also verified the text in opensans with the Google Fonts website and didn't notice any difference. It would be useful to have an image of the correct way that text should be rendered.
Thanks!

**Comment by mellangr** [comment]
@willemarcel sorry, my English is very bad, but I will try to explain. Now in one line the text is written in two fonts:

![fonts1](https://user-images.githubusercontent.com/20912330/36721590-039f6f2a-1bb4-11e8-887f-59153e0aa4da.jpg)

But the Open Sans font supports Cyrillic, and ideally it should be:

![fonts2](https://user-images.githubusercontent.com/20912330/36721604-0cb7799a-1bb4-11e8-9f58-ddc55435cae1.jpg)

Here's another screenshot:

![image3](https://user-images.githubusercontent.com/20912330/36721619-183f30b4-1bb4-11e8-882f-26e10f5d8d5d.png)

**Comment by willemarcel** [comment]
Thank you very much @mellangr! I confirmed the issue and pushed a fix to assembly

**Comment by willemarcel** [comment]
@mellangr this issue has been solved and deployed!

**Comment by mellangr** [comment]
Thank you very much @willemarcel !
