### ISSUE TITLE
Improve geometry simplification

### ISSUE THREAD

**Issue by willemarcel** [mapbox/osmcha-frontend#274]
## *Brief Description*
when we apply a location filter that generates an url larger than 4094 chars, it fails. Possible solution: improve the geometry simplification to reduce the number of decimal digits in the coordinates.

For example:

**Frontend link:** https://osmcha.mapbox.com/?filters=%7B%22geometry%22%3A%5B%7B%22label%22%3A%7B%22type%22%3A%22MultiPolygon%22%2C%22coordinates%22%3A%5B%5B%5B%5B-73.9830625%2C-7.5347344%5D%2C%5B-72.940798%2C-8.9854321%5D%2C%5B-73.1910319%2C-9.3999081%5D%2C%5B-72.4134046%2C-9.4826364%5D%2C%5B-72.1572979%2C-9.9721762%5D%2C%5B-71.2517318%2C-9.9677395%5D%2C%5B-70.5469073%2C-9.4268164%5D%2C%5B-70.6210253%2C-10.9998208%5D%2C%5B-69.3108944%2C-10.9449178%5D%2C%5B-68.666718%2C-11.1377503%5D%2C%5B-66.5971322%2C-9.8972405%5D%2C%5B-65.345923%2C-9.7479128%5D%2C%5B-65.3614287%2C-11.2385965%5D%2C%5B-65.2609735%2C-11.7018912%5D%2C%5B-65.0824835%2C-11.7150739%5D%2C%5B-64.9805893%2C-12.0177273%5D%2C%5B-64.7021956%2C-12.0908997%5D%2C%5B-64.4075013%2C-12.4460151%5D%2C%5B-63.7187376%2C-12.4409399%5D%2C%5B-63.283027%2C-12.6848116%5D%2C%5B-63.0906659%2C-12.636004%5D%2C%5B-62.7876598%2C-13.0026719%5D%2C%5B-62.1213021%2C-13.1509949%5D%2C%5B-61.8103105%2C-13.5282891%5D%2C%5B-61.0209546%2C-13.4883157%5D%2C%5B-60.5117445%2C-13.7907775%5D%2C%5B-60.2471533%2C-15.0614926%5D%2C%5B-60.4999033%2C-15.0973067%5D%2C%5B-60.2392049%2C-15.4749158%5D%2C%5B-60.1738197%2C-16.2667293%5D%2C%5B-58.3395449%2C-16.2741749%5D%2C%5B-58.424%2C-17.09%5D%2C%5B-58.145%2C-17.413%5D%2C%5B-57.7459133%2C-17.5509309%5D%2C%5B-57.5051262%2C-18.200337%5D%2C%5B-57.7086758%2C-18.9834169%5D%2C%5B-58.131%2C-19.758%5D%2C%5B-57.8579571%2C-19.9702976%5D%2C%5B-58.162789%2C-20.2266571%5D%2C%5B-57.8356529%2C-20.9376193%5D%2C%5B-57.937195%2C-22.0992991%5D%2C%5B-56.7789784%2C-22.2571732%5D%2C%5B-56.4386641%2C-22.0810105%5D%2C%5B-55.7430168%2C-22.3926611%5D%2C%5B-55.4462276%2C-23.9164577%5D%2C%5B-55.0588073%2C-23.9915198%5D%2C%5B-54.6697791%2C-23.8126147%5D%2C%5B-54.3199586%2C-24.0304971%5D%2C%5B-54.2616541%2C-24.3391083%5D%2C%5B-54.594359%2C-25.5496618%5D%2C%5B-54.4422509%2C-25.6802819%5D%2C%5B-54.108%2C-25.495%5D%2C%5B-53.9256584%2C-25.6209056%5D%2C%5B-53.6410997%2C-26.2155872%5D%2C%5B-53.671383%2C-26.895827%5D%2C%5B-53.829951%2C-27.147881%5D%2C%5B-54.838%2C-27.6%5D%2C%5B-55.7374137%2C-28.2306606%5D%2C%5B-55.6943285%2C-28.4220428%5D%2C%5B-55.903229%2C-28.4121775%5D%2C%5B-57.6425134%2C-30.1794033%5D%2C%5B-57.2621208%2C-30.2676064%5D%2C%5B-56.837885%2C-30.091376%5D%2C%5B-56.0131851%2C-30.8052349%5D%2C%5B-55.9487344%2C-31.0815692%5D%2C%5B-55.549824%2C-30.8856329%5D%2C%5B-55.2177592%2C-31.261853%5D%2C%5B-54.5724997%2C-31.4825171%5D%2C%5B-53.7278341%2C-32.0951455%5D%2C%5B-53.5757377%2C-32.455076%5D%2C%5B-53.0755833%2C-32.7408806%5D%2C%5B-53.5181889%2C-33.153425%5D%2C%5B-53.5261636%2C-33.6264111%5D%2C%5B-53.1810897%2C-33.8689056%5D%2C%5B-52.4315397%2C-33.2153489%5D%2C%5B-52.0870161%2C-32.4183205%5D%2C%5B-50.6044131%2C-31.2413459%5D%2C%5B-49.4639924%2C-29.3422147%5D%2C%5B-48.4071246%2C-28.4325455%5D%2C%5B-48.1148306%2C-27.3245345%5D%2C%5B-48.3489679%2C-26.7508145%5D%2C%5B-48.2868174%2C-26.2975346%5D%2C%5B-47.8651591%2C-25.4832679%5D%2C%5B-46.6506721%2C-24.7010524%5D%2C%5B-45.0594722%2C-24.0738278%5D%2C%5B-44.0995483%2C-23.4192901%5D%2C%5B-41.8587865%2C-23.154575%5D%2C%5B-41.4817676%2C-22.5033696%5D%2C%5B-40.7849816%2C-22.0464292%5D%2C%5B-40.8144167%2C-21.6767229%5D%2C%5B-39.4922739%2C-19.4013387%5D%2C%5B-39.4675013%2C-18.3035913%5D%2C%5B-39.2888184%2C-18.1409554%5D%2C%5B-38.6705278%2C-18.1685475%5D%2C%5B-38.4917127%2C-18.0046035%5D%2C%5B-38.9099805%2C-16.8463679%5D%2C%5B-38.6469672%2C-15.8832657%5D%2C%5B-38.8499601%2C-14.6108195%5D%2C%5B-38.6278326%2C-13.3476607%5D%2C%5B-37.8966819%2C-12.7584425%5D%2C%5B-36.7563375%2C-10.9188619%5D%2C%5B-36.2819698%2C-10.6568193%5D%2C%5B-35.0781912%2C-9.2078669%5D%2C%5B-34.6437431%2C-7.9873549%5D%2C%5B-34.5995314%2C-7.1113264%5D%2C%5B-35.286053%2C-5.0250349%5D%2C%5B-36.9844078%2C-4.7080354%5D%2C%5B-37.5121798%2C-4.4153468%5D%2C%5B-38.3125687%2C-3.5770286%5D%2C%5B-39.933587%2C-2.6418359%5D%2C%5B-41.4523687%2C-2.6846508%5D%2C%5B-42.7971145%2C-2.3203793%5D%2C%5B-44.7778888%2C-1.1143602%5D%2C%5B-48.2553171%2C-0.0127365%5D%2C%5B-50.7867449%2C3.0059607%5D%2C%5B-50.9423175%2C4.2016512%5D%2C%5B-51.4942689%2C4.6742577%5D%2C%5B-51.6586669%2C4.0527618%5D%2C%5B-52.3221465%2C3.1704704%5D%2C%5B-52.5716911%2C2.5084462%5D%2C%5B-52.9472487%2C2.1768619%5D%2C%5B-53.745%2C2.373889%5D%2C%5B-54.282222%2C2.155556%5D%2C%5B-55.0037377%2C2.5909298%5D%2C%5B-55.3853272%2C2.4183602%5D%2C%5B-55.9102034%2C2.5200369%5D%2C%5B-56.114487%2C2.2985681%5D%2C%5B-55.9563774%2C1.8450942%5D%2C%5B-57.3071169%2C1.9966525%5D%2C%5B-57.5770937%2C1.6903525%5D%2C%5B-58.3895372%2C1.5353778%5D%2C%5B-58.5190011%2C1.2581824%5D%2C%5B-58.8001115%2C1.1765323%5D%2C%5B-59.751%2C1.859%5D%2C%5B-59.7256882%2C2.2604115%5D%2C%5B-59.8992628%2C2.3634561%5D%2C%5B-59.9847969%2C2.8524193%5D%2C%5B-59.836287%2C3.5254615%5D%2C%5B-59.5611163%2C3.9205025%5D%2C%5B-59.6826893%2C4.363737%5D%2C%5B-60.1495499%2C4.5114679%5D%2C%5B-59.9767103%2C5.0796423%5D%2C%5B-60.2150053%2C5.280936%5D%2C%5B-60.7375541%2C5.2018977%5D%2C%5B-60.591%2C4.927%5D%2C%5B-60.954%2C4.563%5D%2C%5B-62.112%2C4.093%5D%2C%5B-62.406%2C4.18%5D%2C%5B-62.678%2C4.039%5D%2C%5B-62.744%2C3.684%5D%2C%5B-63.026%2C3.651%5D%2C%5B-63.286%2C3.973%5D%2C%5B-63.997%2C3.904%5D%2C%5B-64.133%2C4.106%5D%2C%5B-64.5565022%2C4.105295%5D%2C%5B-64.8112289%2C4.2704754%5D%2C%5B-64.196724%2C3.600541%5D%2C%5B-64.058235%2C2.500407%5D%2C%5B-63.373047%2C2.411534%5D%2C%5B-63.380055%2C2.210381%5D%2C%5B-64.001046%2C1.972869%5D%2C%5B-64.326017%2C1.395002%5D%2C%5B-64.448326%2C1.472375%5D%2C%5B-65.103801%2C1.155311%5D%2C%5B-65.531234%2C0.665526%5D%2C%5B-65.596224%2C0.999415%5D%2C%5B-66.31032%2C0.744944%5D%2C%5B-66.8511907%2C1.2289593%5D%2C%5B-67.0867527%2C1.167036%5D%2C%5B-67.3663713%2C2.2053049%5D%2C%5B-67.9540941%2C1.8471395%5D%2C%5B-68.1901801%2C2.0290636%5D%2C%5B-68.2161805%2C1.771824%5D%2C%5B-69.7812711%2C1.7005753%5D%2C%5B-69.8426578%2C1.0727188%5D%2C%5B-69.2392743%2C1.0383589%5D%2C%5B-69.1182075%2C0.655482%5D%2C%5B-69.4763233%2C0.7345742%5D%2C%5B-70.0462896%2C0.5626671%5D%2C%5B-70.0432279%2C-0.1899788%5D%2C%5B-69.6436814%2C-0.4806448%5D%2C%5B-69.3971905%2C-1.1143462%5D%2C%5B-69.9725975%2C-4.3344272%5D%2C%5B-70.6206656%2C-4.1280524%5D%2C%5B-71.002818%2C-4.3896239%5D%2C%5B-71.867648%2C-4.5280776%5D%2C%5B-72.8721657%2C-5.1516175%5D%2C%5B-73.238328%2C-6.0450543%5D%2C%5B-73.1343515%2C-6.5082283%5D%2C%5B-73.65421%2C-6.7869298%5D%2C%5B-73.7250596%2C-7.3427471%5D%2C%5B-73.9256142%2C-7.3650916%5D%2C%5B-73.9830625%2C-7.5347344%5D%5D%5D%2C%5B%5B%5B-34.0179673%2C-3.8498538%5D%2C%5B-33.8920989%2C-4.036535%5D%2C%5B-33.6273557%2C-3.9185038%5D%2C%5B-33.7498676%2C-3.6597819%5D%2C%5B-34.0179673%2C-3.8498538%5D%5D%5D%2C%5B%5B%5B-32.6402573%2C-3.7968206%5D%2C%5B-32.4289092%2C-4.0401869%5D%2C%5B-32.2381178%2C-3.780463%5D%2C%5B-32.3554072%2C-3.6453725%5D%2C%5B-32.6402573%2C-3.7968206%5D%5D%5D%2C%5B%5B%5B-29.5580613%2C-20.4737545%5D%2C%5B-29.3471493%2C-20.7132331%5D%2C%5B-29.0718818%2C-20.570881%5D%2C%5B-28.8328612%2C-20.6981359%5D%2C%5B-28.6354856%2C-20.4928358%5D%2C%5B-28.8027648%2C-20.2758075%5D%2C%5B-29.0953728%2C-20.4264857%5D%2C%5B-29.3342982%2C-20.289323%5D%2C%5B-29.5580613%2C-20.4737545%5D%5D%5D%2C%5B%5B%5B-29.5472679%2C0.92553%5D%2C%5B-29.3637099%2C0.7189175%5D%2C%5B-29.1450135%2C0.9260544%5D%2C%5B-29.3589898%2C1.1205948%5D%2C%5B-29.5472679%2C0.92553%5D%5D%5D%5D%7D%2C%22value%22%3A%7B%22type%22%3A%22MultiPolygon%22%2C%22coordinates%22%3A%5B%5B%5B%5B-73.9830625%2C-7.5347344%5D%2C%5B-72.940798%2C-8.9854321%5D%2C%5B-73.1910319%2C-9.3999081%5D%2C%5B-72.4134046%2C-9.4826364%5D%2C%5B-72.1572979%2C-9.9721762%5D%2C%5B-71.2517318%2C-9.9677395%5D%2C%5B-70.5469073%2C-9.4268164%5D%2C%5B-70.6210253%2C-10.9998208%5D%2C%5B-69.3108944%2C-10.9449178%5D%2C%5B-68.666718%2C-11.1377503%5D%2C%5B-66.5971322%2C-9.8972405%5D%2C%5B-65.345923%2C-9.7479128%5D%2C%5B-65.3614287%2C-11.2385965%5D%2C%5B-65.2609735%2C-11.7018912%5D%2C%5B-65.0824835%2C-11.7150739%5D%2C%5B-64.9805893%2C-12.0177273%5D%2C%5B-64.7021956%2C-12.0908997%5D%2C%5B-64.4075013%2C-12.4460151%5D%2C%5B-63.7187376%2C-12.4409399%5D%2C%5B-63.283027%2C-12.6848116%5D%2C%5B-63.0906659%2C-12.636004%5D%2C%5B-62.7876598%2C-13.0026719%5D%2C%5B-62.1213021%2C-13.1509949%5D%2C%5B-61.8103105%2C-13.5282891%5D%2C%5B-61.0209546%2C-13.4883157%5D%2C%5B-60.5117445%2C-13.7907775%5D%2C%5B-60.2471533%2C-15.0614926%5D%2C%5B-60.4999033%2C-15.0973067%5D%2C%5B-60.2392049%2C-15.4749158%5D%2C%5B-60.1738197%2C-16.2667293%5D%2C%5B-58.3395449%2C-16.2741749%5D%2C%5B-58.424%2C-17.09%5D%2C%5B-58.145%2C-17.413%5D%2C%5B-57.7459133%2C-17.5509309%5D%2C%5B-57.5051262%2C-18.200337%5D%2C%5B-57.7086758%2C-18.9834169%5D%2C%5B-58.131%2C-19.758%5D%2C%5B-57.8579571%2C-19.9702976%5D%2C%5B-58.162789%2C-20.2266571%5D%2C%5B-57.8356529%2C-20.9376193%5D%2C%5B-57.937195%2C-22.0992991%5D%2C%5B-56.7789784%2C-22.2571732%5D%2C%5B-56.4386641%2C-22.0810105%5D%2C%5B-55.7430168%2C-22.3926611%5D%2C%5B-55.4462276%2C-23.9164577%5D%2C%5B-55.0588073%2C-23.9915198%5D%2C%5B-54.6697791%2C-23.8126147%5D%2C%5B-54.3199586%2C-24.0304971%5D%2C%5B-54.2616541%2C-24.3391083%5D%2C%5B-54.594359%2C-25.5496618%5D%2C%5B-54.4422509%2C-25.6802819%5D%2C%5B-54.108%2C-25.495%5D%2C%5B-53.9256584%2C-25.6209056%5D%2C%5B-53.6410997%2C-26.2155872%5D%2C%5B-53.671383%2C-26.895827%5D%2C%5B-53.829951%2C-27.147881%5D%2C%5B-54.838%2C-27.6%5D%2C%5B-55.7374137%2C-28.2306606%5D%2C%5B-55.6943285%2C-28.4220428%5D%2C%5B-55.903229%2C-28.4121775%5D%2C%5B-57.6425134%2C-30.1794033%5D%2C%5B-57.2621208%2C-30.2676064%5D%2C%5B-56.837885%2C-30.091376%5D%2C%5B-56.0131851%2C-30.8052349%5D%2C%5B-55.9487344%2C-31.0815692%5D%2C%5B-55.549824%2C-30.8856329%5D%2C%5B-55.2177592%2C-31.261853%5D%2C%5B-54.5724997%2C-31.4825171%5D%2C%5B-53.7278341%2C-32.0951455%5D%2C%5B-53.5757377%2C-32.455076%5D%2C%5B-53.0755833%2C-32.7408806%5D%2C%5B-53.5181889%2C-33.153425%5D%2C%5B-53.5261636%2C-33.6264111%5D%2C%5B-53.1810897%2C-33.8689056%5D%2C%5B-52.4315397%2C-33.2153489%5D%2C%5B-52.0870161%2C-32.4183205%5D%2C%5B-50.6044131%2C-31.2413459%5D%2C%5B-49.4639924%2C-29.3422147%5D%2C%5B-48.4071246%2C-28.4325455%5D%2C%5B-48.1148306%2C-27.3245345%5D%2C%5B-48.3489679%2C-26.7508145%5D%2C%5B-48.2868174%2C-26.2975346%5D%2C%5B-47.8651591%2C-25.4832679%5D%2C%5B-46.6506721%2C-24.7010524%5D%2C%5B-45.0594722%2C-24.0738278%5D%2C%5B-44.0995483%2C-23.4192901%5D%2C%5B-41.8587865%2C-23.154575%5D%2C%5B-41.4817676%2C-22.5033696%5D%2C%5B-40.7849816%2C-22.0464292%5D%2C%5B-40.8144167%2C-21.6767229%5D%2C%5B-39.4922739%2C-19.4013387%5D%2C%5B-39.4675013%2C-18.3035913%5D%2C%5B-39.2888184%2C-18.1409554%5D%2C%5B-38.6705278%2C-18.1685475%5D%2C%5B-38.4917127%2C-18.0046035%5D%2C%5B-38.9099805%2C-16.8463679%5D%2C%5B-38.6469672%2C-15.8832657%5D%2C%5B-38.8499601%2C-14.6108195%5D%2C%5B-38.6278326%2C-13.3476607%5D%2C%5B-37.8966819%2C-12.7584425%5D%2C%5B-36.7563375%2C-10.9188619%5D%2C%5B-36.2819698%2C-10.6568193%5D%2C%5B-35.0781912%2C-9.2078669%5D%2C%5B-34.6437431%2C-7.9873549%5D%2C%5B-34.5995314%2C-7.1113264%5D%2C%5B-35.286053%2C-5.0250349%5D%2C%5B-36.9844078%2C-4.7080354%5D%2C%5B-37.5121798%2C-4.4153468%5D%2C%5B-38.3125687%2C-3.5770286%5D%2C%5B-39.933587%2C-2.6418359%5D%2C%5B-41.4523687%2C-2.6846508%5D%2C%5B-42.7971145%2C-2.3203793%5D%2C%5B-44.7778888%2C-1.1143602%5D%2C%5B-48.2553171%2C-0.0127365%5D%2C%5B-50.7867449%2C3.0059607%5D%2C%5B-50.9423175%2C4.2016512%5D%2C%5B-51.4942689%2C4.6742577%5D%2C%5B-51.6586669%2C4.0527618%5D%2C%5B-52.3221465%2C3.1704704%5D%2C%5B-52.5716911%2C2.5084462%5D%2C%5B-52.9472487%2C2.1768619%5D%2C%5B-53.745%2C2.373889%5D%2C%5B-54.282222%2C2.155556%5D%2C%5B-55.0037377%2C2.5909298%5D%2C%5B-55.3853272%2C2.4183602%5D%2C%5B-55.9102034%2C2.5200369%5D%2C%5B-56.114487%2C2.2985681%5D%2C%5B-55.9563774%2C1.8450942%5D%2C%5B-57.3071169%2C1.9966525%5D%2C%5B-57.5770937%2C1.6903525%5D%2C%5B-58.3895372%2C1.5353778%5D%2C%5B-58.5190011%2C1.2581824%5D%2C%5B-58.8001115%2C1.1765323%5D%2C%5B-59.751%2C1.859%5D%2C%5B-59.7256882%2C2.2604115%5D%2C%5B-59.8992628%2C2.3634561%5D%2C%5B-59.9847969%2C2.8524193%5D%2C%5B-59.836287%2C3.5254615%5D%2C%5B-59.5611163%2C3.9205025%5D%2C%5B-59.6826893%2C4.363737%5D%2C%5B-60.1495499%2C4.5114679%5D%2C%5B-59.9767103%2C5.0796423%5D%2C%5B-60.2150053%2C5.280936%5D%2C%5B-60.7375541%2C5.2018977%5D%2C%5B-60.591%2C4.927%5D%2C%5B-60.954%2C4.563%5D%2C%5B-62.112%2C4.093%5D%2C%5B-62.406%2C4.18%5D%2C%5B-62.678%2C4.039%5D%2C%5B-62.744%2C3.684%5D%2C%5B-63.026%2C3.651%5D%2C%5B-63.286%2C3.973%5D%2C%5B-63.997%2C3.904%5D%2C%5B-64.133%2C4.106%5D%2C%5B-64.5565022%2C4.105295%5D%2C%5B-64.8112289%2C4.2704754%5D%2C%5B-64.196724%2C3.600541%5D%2C%5B-64.058235%2C2.500407%5D%2C%5B-63.373047%2C2.411534%5D%2C%5B-63.380055%2C2.210381%5D%2C%5B-64.001046%2C1.972869%5D%2C%5B-64.326017%2C1.395002%5D%2C%5B-64.448326%2C1.472375%5D%2C%5B-65.103801%2C1.155311%5D%2C%5B-65.531234%2C0.665526%5D%2C%5B-65.596224%2C0.999415%5D%2C%5B-66.31032%2C0.744944%5D%2C%5B-66.8511907%2C1.2289593%5D%2C%5B-67.0867527%2C1.167036%5D%2C%5B-67.3663713%2C2.2053049%5D%2C%5B-67.9540941%2C1.8471395%5D%2C%5B-68.1901801%2C2.0290636%5D%2C%5B-68.2161805%2C1.771824%5D%2C%5B-69.7812711%2C1.7005753%5D%2C%5B-69.8426578%2C1.0727188%5D%2C%5B-69.2392743%2C1.0383589%5D%2C%5B-69.1182075%2C0.655482%5D%2C%5B-69.4763233%2C0.7345742%5D%2C%5B-70.0462896%2C0.5626671%5D%2C%5B-70.0432279%2C-0.1899788%5D%2C%5B-69.6436814%2C-0.4806448%5D%2C%5B-69.3971905%2C-1.1143462%5D%2C%5B-69.9725975%2C-4.3344272%5D%2C%5B-70.6206656%2C-4.1280524%5D%2C%5B-71.002818%2C-4.3896239%5D%2C%5B-71.867648%2C-4.5280776%5D%2C%5B-72.8721657%2C-5.1516175%5D%2C%5B-73.238328%2C-6.0450543%5D%2C%5B-73.1343515%2C-6.5082283%5D%2C%5B-73.65421%2C-6.7869298%5D%2C%5B-73.7250596%2C-7.3427471%5D%2C%5B-73.9256142%2C-7.3650916%5D%2C%5B-73.9830625%2C-7.5347344%5D%5D%5D%2C%5B%5B%5B-34.0179673%2C-3.8498538%5D%2C%5B-33.8920989%2C-4.036535%5D%2C%5B-33.6273557%2C-3.9185038%5D%2C%5B-33.7498676%2C-3.6597819%5D%2C%5B-34.0179673%2C-3.8498538%5D%5D%5D%2C%5B%5B%5B-32.6402573%2C-3.7968206%5D%2C%5B-32.4289092%2C-4.0401869%5D%2C%5B-32.2381178%2C-3.780463%5D%2C%5B-32.3554072%2C-3.6453725%5D%2C%5B-32.6402573%2C-3.7968206%5D%5D%5D%2C%5B%5B%5B-29.5580613%2C-20.4737545%5D%2C%5B-29.3471493%2C-20.7132331%5D%2C%5B-29.0718818%2C-20.570881%5D%2C%5B-28.8328612%2C-20.6981359%5D%2C%5B-28.6354856%2C-20.4928358%5D%2C%5B-28.8027648%2C-20.2758075%5D%2C%5B-29.0953728%2C-20.4264857%5D%2C%5B-29.3342982%2C-20.289323%5D%2C%5B-29.5580613%2C-20.4737545%5D%5D%5D%2C%5B%5B%5B-29.5472679%2C0.92553%5D%2C%5B-29.3637099%2C0.7189175%5D%2C%5B-29.1450135%2C0.9260544%5D%2C%5B-29.3589898%2C1.1205948%5D%2C%5B-29.5472679%2C0.92553%5D%5D%5D%5D%7D%7D%5D%2C%22checked%22%3A%5B%7B%22label%22%3A%22Not%20Reviewed%22%2C%22value%22%3A%22False%22%7D%5D%7D

**Backend:** https://osmcha.mapbox.com/api/v1/changesets/?page=1&page_size=75&geometry={%22type%22:%22MultiPolygon%22,%22coordinates%22:[[[[-73.9830625,-7.5347344],[-72.940798,-8.9854321],[-73.1910319,-9.3999081],[-72.4134046,-9.4826364],[-72.1572979,-9.9721762],[-71.2517318,-9.9677395],[-70.5469073,-9.4268164],[-70.6210253,-10.9998208],[-69.3108944,-10.9449178],[-68.666718,-11.1377503],[-66.5971322,-9.8972405],[-65.345923,-9.7479128],[-65.3614287,-11.2385965],[-65.2609735,-11.7018912],[-65.0824835,-11.7150739],[-64.9805893,-12.0177273],[-64.7021956,-12.0908997],[-64.4075013,-12.4460151],[-63.7187376,-12.4409399],[-63.283027,-12.6848116],[-63.0906659,-12.636004],[-62.7876598,-13.0026719],[-62.1213021,-13.1509949],[-61.8103105,-13.5282891],[-61.0209546,-13.4883157],[-60.5117445,-13.7907775],[-60.2471533,-15.0614926],[-60.4999033,-15.0973067],[-60.2392049,-15.4749158],[-60.1738197,-16.2667293],[-58.3395449,-16.2741749],[-58.424,-17.09],[-58.145,-17.413],[-57.7459133,-17.5509309],[-57.5051262,-18.200337],[-57.7086758,-18.9834169],[-58.131,-19.758],[-57.8579571,-19.9702976],[-58.162789,-20.2266571],[-57.8356529,-20.9376193],[-57.937195,-22.0992991],[-56.7789784,-22.2571732],[-56.4386641,-22.0810105],[-55.7430168,-22.3926611],[-55.4462276,-23.9164577],[-55.0588073,-23.9915198],[-54.6697791,-23.8126147],[-54.3199586,-24.0304971],[-54.2616541,-24.3391083],[-54.594359,-25.5496618],[-54.4422509,-25.6802819],[-54.108,-25.495],[-53.9256584,-25.6209056],[-53.6410997,-26.2155872],[-53.671383,-26.895827],[-53.829951,-27.147881],[-54.838,-27.6],[-55.7374137,-28.2306606],[-55.6943285,-28.4220428],[-55.903229,-28.4121775],[-57.6425134,-30.1794033],[-57.2621208,-30.2676064],[-56.837885,-30.091376],[-56.0131851,-30.8052349],[-55.9487344,-31.0815692],[-55.549824,-30.8856329],[-55.2177592,-31.261853],[-54.5724997,-31.4825171],[-53.7278341,-32.0951455],[-53.5757377,-32.455076],[-53.0755833,-32.7408806],[-53.5181889,-33.153425],[-53.5261636,-33.6264111],[-53.1810897,-33.8689056],[-52.4315397,-33.2153489],[-52.0870161,-32.4183205],[-50.6044131,-31.2413459],[-49.4639924,-29.3422147],[-48.4071246,-28.4325455],[-48.1148306,-27.3245345],[-48.3489679,-26.7508145],[-48.2868174,-26.2975346],[-47.8651591,-25.4832679],[-46.6506721,-24.7010524],[-45.0594722,-24.0738278],[-44.0995483,-23.4192901],[-41.8587865,-23.154575],[-41.4817676,-22.5033696],[-40.7849816,-22.0464292],[-40.8144167,-21.6767229],[-39.4922739,-19.4013387],[-39.4675013,-18.3035913],[-39.2888184,-18.1409554],[-38.6705278,-18.1685475],[-38.4917127,-18.0046035],[-38.9099805,-16.8463679],[-38.6469672,-15.8832657],[-38.8499601,-14.6108195],[-38.6278326,-13.3476607],[-37.8966819,-12.7584425],[-36.7563375,-10.9188619],[-36.2819698,-10.6568193],[-35.0781912,-9.2078669],[-34.6437431,-7.9873549],[-34.5995314,-7.1113264],[-35.286053,-5.0250349],[-36.9844078,-4.7080354],[-37.5121798,-4.4153468],[-38.3125687,-3.5770286],[-39.933587,-2.6418359],[-41.4523687,-2.6846508],[-42.7971145,-2.3203793],[-44.7778888,-1.1143602],[-48.2553171,-0.0127365],[-50.7867449,3.0059607],[-50.9423175,4.2016512],[-51.4942689,4.6742577],[-51.6586669,4.0527618],[-52.3221465,3.1704704],[-52.5716911,2.5084462],[-52.9472487,2.1768619],[-53.745,2.373889],[-54.282222,2.155556],[-55.0037377,2.5909298],[-55.3853272,2.4183602],[-55.9102034,2.5200369],[-56.114487,2.2985681],[-55.9563774,1.8450942],[-57.3071169,1.9966525],[-57.5770937,1.6903525],[-58.3895372,1.5353778],[-58.5190011,1.2581824],[-58.8001115,1.1765323],[-59.751,1.859],[-59.7256882,2.2604115],[-59.8992628,2.3634561],[-59.9847969,2.8524193],[-59.836287,3.5254615],[-59.5611163,3.9205025],[-59.6826893,4.363737],[-60.1495499,4.5114679],[-59.9767103,5.0796423],[-60.2150053,5.280936],[-60.7375541,5.2018977],[-60.591,4.927],[-60.954,4.563],[-62.112,4.093],[-62.406,4.18],[-62.678,4.039],[-62.744,3.684],[-63.026,3.651],[-63.286,3.973],[-63.997,3.904],[-64.133,4.106],[-64.5565022,4.105295],[-64.8112289,4.2704754],[-64.196724,3.600541],[-64.058235,2.500407],[-63.373047,2.411534],[-63.380055,2.210381],[-64.001046,1.972869],[-64.326017,1.395002],[-64.448326,1.472375],[-65.103801,1.155311],[-65.531234,0.665526],[-65.596224,0.999415],[-66.31032,0.744944],[-66.8511907,1.2289593],[-67.0867527,1.167036],[-67.3663713,2.2053049],[-67.9540941,1.8471395],[-68.1901801,2.0290636],[-68.2161805,1.771824],[-69.7812711,1.7005753],[-69.8426578,1.0727188],[-69.2392743,1.0383589],[-69.1182075,0.655482],[-69.4763233,0.7345742],[-70.0462896,0.5626671],[-70.0432279,-0.1899788],[-69.6436814,-0.4806448],[-69.3971905,-1.1143462],[-69.9725975,-4.3344272],[-70.6206656,-4.1280524],[-71.002818,-4.3896239],[-71.867648,-4.5280776],[-72.8721657,-5.1516175],[-73.238328,-6.0450543],[-73.1343515,-6.5082283],[-73.65421,-6.7869298],[-73.7250596,-7.3427471],[-73.9256142,-7.3650916],[-73.9830625,-7.5347344]]],[[[-34.0179673,-3.8498538],[-33.8920989,-4.036535],[-33.6273557,-3.9185038],[-33.7498676,-3.6597819],[-34.0179673,-3.8498538]]],[[[-32.6402573,-3.7968206],[-32.4289092,-4.0401869],[-32.2381178,-3.780463],[-32.3554072,-3.6453725],[-32.6402573,-3.7968206]]],[[[-29.5580613,-20.4737545],[-29.3471493,-20.7132331],[-29.0718818,-20.570881],[-28.8328612,-20.6981359],[-28.6354856,-20.4928358],[-28.8027648,-20.2758075],[-29.0953728,-20.4264857],[-29.3342982,-20.289323],[-29.5580613,-20.4737545]]],[[[-29.5472679,0.92553],[-29.3637099,0.7189175],[-29.1450135,0.9260544],[-29.3589898,1.1205948],[-29.5472679,0.92553]]]]}&checked=False

## What is the motivation / use case for this feature?
Allow to filter changesets by using large geometries, for example a contry with the size of Brazil.

## What  is the current behaviour, (attach relevant screenshots) ?
The request will fail and the user will be logged out.

## What  is the expected behaviour ?
Simplify the geometry or recommend the user to save the filter .

**Comment by tridip1931** [comment]
🙈 , great find @willemarcel 
Can you share any ideas how you are going to solve this?

**Comment by mmd-osm** [comment]
Polylines could be an option for lists of lat/lon pairs: https://github.com/mapbox/polyline

**Comment by willemarcel** [comment]
The solution I found was not simplify the geometry, but analyse the parameters characters length and ask the user to save the filter instead of applying it.
It requested some additional changes in the code, but now it's working great.

**Comment by willemarcel** [comment]
Solved with https://github.com/mapbox/osmcha-frontend/pull/277/commits/e7e5236fa5a859f4bc397d8dd53578f52a9f7717
