### ISSUE TITLE
change "open with button behavior"

### ISSUE THREAD

**Issue by govvin** [mapbox/osmcha-frontend#279]
![image](https://user-images.githubusercontent.com/5821688/37858910-b17fa236-2f46-11e8-9197-31a073935a0c.png)

## *Brief Description*
It would be nice to have the "Open with button" open a preferred editor in one click (similar to OSM edit button), but still retaining the option to choose an editor. 

![image](https://user-images.githubusercontent.com/5821688/37858923-f4935f90-2f46-11e8-9c6e-d91534e20006.png)

## What is the motivation / use case for this feature?
If you a lot of OsmCha and prefer a particular editor, choosing every time gets a bit tedious. This can contribute to a 50% click reduction on that button. :stuck_out_tongue_winking_eye: 

## What  is the current behaviour, (attach relevant screenshots) ?
You're required to choose an editor every time.

**Comment by willemarcel** [comment]
Thanks for the report, @govvin!

Currently we have the `J` keyboard shortcut that loads the changeset on JOSM. I'll add a shortcut to open it on iD and for the other menu options. I'll talk with the team about having an edit button.

**Comment by govvin** [comment]
Thanks @willemarcel .  I didn't know about the shortcut keys! This works just as well.

**Comment by willemarcel** [comment]
Added the new keyboard shortcuts in https://github.com/mapbox/osmcha-frontend/commit/7bca1aee9cc98eb9b2f6d3e816edf4d76e48f9c0. It'll be deployed soon.
