### ISSUE TITLE
The feed appears to have got stuck. Could someone give it a prod, please

### ISSUE THREAD

**Issue by DaveF63** [mapbox/osmcha-frontend#281]
As the subject line.

**Comment by batpad** [comment]
@amishas157 @willemarcel @tridip1931

**Comment by willemarcel** [comment]
We are working to fix this issue right now. Thanks for the report, @DaveF63

**Comment by willemarcel** [comment]
Fixed! Sorry for the inconvenience!

**Comment by zzptichka** [comment]
Appears to be stuck again

**Comment by amishas157** [comment]
Osmcha is undergoing some fluctuations at server side. Working on fixing it. @zzptichka
