### ISSUE TITLE
missing tag changes

### ISSUE THREAD

**Issue by Marc-marc-marc** [mapbox/osmcha-frontend#288]
## *Brief Description*
https://osmcha.mapbox.com/changesets/57838384
this changeset create several way that have somes tags

## What  is the current behaviour, (attach relevant screenshots) ?
the "tag changes" tab said "No tags were changed in this changeset."

## What  is the expected behaviour ?
list added tags

## How do we replicate the issue ?
1. clic on https://osmcha.mapbox.com/changesets/57838384
2. clic on "tag changes" tab

**Comment by willemarcel** [comment]
The aim of this tab is to show strictly "tag changes", so objects created or deleted will never be listed on this tab. Only objects that were modified and lost tags or had changes in the tag values.
