### ISSUE TITLE
If no comment, Changeset details navbar breaks

### ISSUE THREAD

**Issue by tridip1931** [mapbox/osmcha-frontend#30]
If there is no comment in the changeset, the changeset details navbar do not show up. Clicking on subsequent changeset do not fix the issue. 

For reference: 
changeset id: 49184825

![screencapture-localhost-3000-changesets-49184825-1496385299461](https://cloud.githubusercontent.com/assets/7458983/26713902/7d69ab92-478c-11e7-9076-b98dd2816c2e.png)

cc: @kepta @ajithranka @rasagy

**Comment by kepta** [comment]
this was fixed.
