### ISSUE TITLE
osmcha.mapbox.com opens to Welcome to nginx!

### ISSUE THREAD

**Issue by cliffordsnow** [mapbox/osmcha-frontend#303]
## I'm submitting a _(bug report/feature request/ support or question)_
bug report
## *Brief Description*

When attempting to open OSMCha, only Welcome to nginx! appears

## What  is the current behaviour, (attach relevant screenshots) ?

Just the page showing that nginx is installed
## What  is the expected behaviour ?

open to the osmcha page to look at changesets etc.
## When does this occur ?

allways
## How do we replicate the issue ?

1.go to https://osmcha.mapbox.com
2.
3.
4.

## Please tell us about your environment:

Chrome on Linux
## Other Information / context:

Was asked by osmcha to reload when pulling up a changeset http://osmcha.mapbox.com/changesets/60638876

**Comment by willemarcel** [comment]
@cliffordsnow thanks for the report!

This seems to be happening only in Chrome browsers. We are searching for a solution.

**Comment by gscscnd** [comment]
I’ve just logged in using Firefox and was greeted with “Welcome to nginx!” on next visit.

**Comment by NonnEmilia** [comment]
I tried with Firefox and I saw the nginx welcome. I cleared my cache and now is gone.

**Comment by kepta** [comment]
@willemarcel after a big back n forth, I feel the server behaviour has changed a bit and the service worker wasn't expecting that.

The service work expects the endpoints 
- `https://osmcha.mapbox.com` 
- `https://osmcha.mapbox.com/` 
- `https://osmcha.mapbox.com/index.html`
I believe the server is serving the `nginx` page when I do 
```bash
curl https://osmcha.mapbox.com/index.html
```
If we can make all the above url serve the same `index.html` file, I believe the service worker should start working correctly.

**Comment by willemarcel** [comment]
@kepta thank you a lot! there is really a problem with the index.html url

I'm working on this now.

**Comment by willemarcel** [comment]
@cliffordsnow @gscscnd @NonnEmilia We have fixed the problem. Maybe you will need to clear the osmcha cache to get this updated: https://7labs.io/tips-tricks/clear-site-specific-cookies-cache.html#Clear_site-specific_cookies_and_cache_in_Chrome

I'm studying a way to force the browser to refresh. Thank you for the reports and sorry for the inconvenience

**Comment by willemarcel** [comment]
All issues with OSMCha have been solved. If you yet see some error, just reload the page.
