### ISSUE TITLE
changesets fail to load, intermittently

### ISSUE THREAD

**Issue by Piskvor** [mapbox/osmcha-frontend#307]
## *Brief Description*

1. Open any changeset in OSMCha (manifests randomly - when something is overloaded, I guess?) - number of edits or bounding box size doesn't seem to be related.
2. Changeset starts loading

## What  is the current behaviour, (attach relevant screenshots) ?
3. Changeset never loads, neither does the map
4. Map eventually turns pink and a notification "failed to load" is shown
5. With dev console open, this output is generated:
`12:28:33.265 -1 61592375:1:101`

`12:28:46.199 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://overpass.maptime.in/api/interpreter?data=[out:xml][adiff:%222018-08-12T15:45:19Z,%22,%222018-08-12T15:45:21Z%22];(node(bbox)(changed);way(bbox)(changed);relation(bbox)(changed));out%20meta%20geom(bbox);&bbox=14.4002811,50.0912721,14.4050026,50.0923744. (Reason: CORS request did not succeed).`

`12:28:46.208
Object { msg: "Overpass query failed.", error: TypeError, name: "Changeset:61592375 Map failed" }
console.js:26`

## What  is the expected behaviour ?
3. Changeset loads, map loads

## When does this occur ?
Intermittently - logged in or not, large changesets or small, large bounding box or not. Opening multiple changesets in a short timespan is likely to trigger the bug.

## How do we replicate the issue ?

1. Open a changeset in OsmCha
2. In short succession, open another changeset in OsmCha
3. Repeat - usually the bug manifests within 10 changesets

## Please tell us about your environment:

Reproduced on Firefox	61.0.1, Google Chrome Stable (versions 67 and 68), etc.

## Other Information / context:

If an Overpass server is overloaded/not configured for external access (does osmcha query multiple ones? overpass.maptime.in looks unfamiliar...), the app doesn't seem to handle a failed OP query at all.
 Not sure if root cause (overload?) fixable, but I guess that a warning of a failed request might help the user.

**Comment by willemarcel** [comment]
Thanks for reporting @Piskvor ! We already have noticed it and right now the failing changesets are being repaired.

**Comment by willemarcel** [comment]
Now it's solved: https://osmcha.mapbox.com/changesets/61592375/
