### ISSUE TITLE
Filter date range format should use ISO-8601 (YYYY-MM-DD)

### ISSUE THREAD

**Issue by b-jazz** [mapbox/osmcha-frontend#309]
## *Brief Description*
Dates are presented as DD/MM/YYYY which is confusing to me since our locale uses MM/DD/YYYY. Since this is an internationally used website, you should consider using the international standard (ISO-8601) of YYYY-MM-DD.

## What is the motivation / use case for this feature?
Prevent confusion. Adhere to standards.

## How do we replicate the issue ?

1. Bring up the filter panel
2. Note that the date range dates are expressed in a non-ISO format

## Please tell us about your environment:
Linux OS
Firefox browser

**Comment by willemarcel** [comment]
done and deployed some weeks ago!
