### ISSUE TITLE
Add legend or other hints to show which object is old and which is new

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/osmcha-frontend#312]
## *Brief Description*
To make osmcha easier for new users, a legend or other hints showing which shade of yellow/orange is the new version vs which is the old version.

## What is the motivation / use case for this feature?
When a feature is moved, at the moment it's unclear how it changed as there's no legend or other hints explaning which is the old vs. which is the new.

**Comment by willemarcel** [comment]
Hi @andrewharvey 

We already have a legend:

![](https://user-images.githubusercontent.com/8921295/35940114-236f8314-0c1c-11e8-9649-47c1f077ab02.png)

I'll think if there is a way we could make it more visible.

**Comment by andrewharvey** [comment]
My mistake! Sorry I should have looked a bit harder.
