### ISSUE TITLE
Export My Filter's Result

### ISSUE THREAD

**Issue by adiatmad** [mapbox/osmcha-frontend#314]
Hello, is it possible to export OSMCha results based on my filter settings?
Thank you in advance.

**Comment by willemarcel** [comment]
Hi @adiatmad 

Yes, we have an API that you can use to export the filter results as a JSON file. For example:  https://osmcha.mapbox.com/api/v1/aoi/71247014-abbf-4253-8093-2a2afdda4169/changesets/?format=json

Replace `71247014-abbf-4253-8093-2a2afdda4169` by your AOI uid.

**Comment by pietervdvn** [comment]
Hey,

I'm a bit lost on the AOI-UID (what is that?) and on how to authenticate against this API-endpoint.

If possible, could we get a button in the frontend to download this json?

**Comment by waldyrious** [comment]
> how to authenticate against this API-endpoint

I too bumped into this issue when attempting to download the changesets using the API. If I try to open the following URL:

https://osmcha.org/api/v1/aoi/2b27d8fe-cc68-495a-9bb8-5c12f92c29cc/changesets/?format=json

I get the error message "Authentication credentials were not provided.", even though I am logged in to OSMCha. I don't see anything in the docs about API authentication :(

One workaround is to use the RSS export format (which [is documented](https://osmcha.org/about#saving-and-sharing-custom-filters)), which for some reason works without requiring further authentication:

https://osmcha.org/api/v1/aoi/2b27d8fe-cc68-495a-9bb8-5c12f92c29cc/changesets/feed

Another workaround is to use the browser's developer tools to get the API request URL including the authentication data — in my case, using Firefox, I opened the developer tools, went to the Network tab, clicked the refresh button in the OSMCha UI, and then copied the resulting API request as a cURL command:

![Image](https://github.com/user-attachments/assets/df841d43-4ddd-413d-a801-f74197805102)

The result I got was something like this:

```
curl 'https://osmcha.org/api/v1/aoi/2b27d8fe-cc68-495a-9bb8-5c12f92c29cc/changesets/?page_size=25^&page=1' \
  --compressed \
  -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:139.0) Gecko/20100101 Firefox/139.0' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en,en-US;q=0.8,pt-PT;q=0.5,pt;q=0.3' \
  -H 'Accept-Encoding: gzip, deflate, br, zstd' \
  -H 'Referer: https://osmcha.org/filters?aoi=2b27d8fe-cc68-495a-9bb8-5c12f92c29cc' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Token [REDACTED]' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: i18next=en; csrftoken=[REDACTED]' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Priority: u=0' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache'
```

(Notice the `-H 'Authorization: Token [REDACTED]'` line)

I pasted this into a text editor, changed the `?page_size=25^&page=1` parameters in the URL to `?format=json`, then ran the resulting command in the terminal, which finally produced the intended JSON output.

Still, this authentication issue seems like something that should be fixed directly in OSMCha.
