### ISSUE TITLE
Filter option to only show what actually happened in my bbox (cut/clip filter for bbox?)

### ISSUE THREAD

**Issue by tordans** [mapbox/osmcha-frontend#315]
This might be a bug report or feature request or support or question; I dont know yet.

## My UseCase

- I re-visit an area every few month. 
- I want to be able to see _"what changed in this area since I was here last"_

The goal is, to be up to date to my immediate surroundings.

And with that learn stuff. Or fix stuff. Or extend edits that where done by other since I was last here.

## Behaviour, Example

Right now, I set a filter and draw a bbox around the area I visit.

My problem is: The settings seems to be "show every changeset that touches this bbox".
As a consequence I get a lot of edits that changed the world or germany as a whole but did not actually edit anything in my bbox.

In other word, I want the bbox filter to actually clip or cut the changelogs and only show those changelogs that actually modified/… thinks in my bbox.

Example: https://osmcha.mapbox.com/changesets/63025514?filters=%7B%22geometry%22%3A%5B%7B%22label%22%3A%7B%22coordinates%22%3A%5B%5B%5B12.810140468056176%2C51.03232660315075%5D%2C%5B12.848513330950652%2C51.03262179482218%5D%2C%5B12.848865375560592%2C51.0140210472764%5D%2C%5B12.805211843461763%2C51.0157190440583%5D%2C%5B12.810140468056176%2C51.03232660315075%5D%5D%5D%2C%22type%22%3A%22Polygon%22%7D%2C%22value%22%3A%7B%22coordinates%22%3A%5B%5B%5B12.810140468056176%2C51.03232660315075%5D%2C%5B12.848513330950652%2C51.03262179482218%5D%2C%5B12.848865375560592%2C51.0140210472764%5D%2C%5B12.805211843461763%2C51.0157190440583%5D%2C%5B12.810140468056176%2C51.03232660315075%5D%5D%5D%2C%22type%22%3A%22Polygon%22%7D%7D%5D%7D

# Questions

- Is that already possible / how?
- Is it possible at all / should it be a checkbox or maybe the default?
- What is missing to allow this feature / external dependencies?
- Is there a different tool that I should use?

**Comment by willemarcel** [comment]
Hi @tordans 

The solution to this is to set a value to the **BBox size bound** field. It will filter changesets that have a bbox area lower than X times the area of your BBox or geometry filter. For example, if the geometry you defined in your filter has an area of 1 degree and you set the 'BBox size bound' to 2, it will filter the changesets whose bbox area is lower than 2 degrees.

**Comment by tordans** [comment]
@willemarcel sorry for no reply, I found the option and got it working. Thanks!

I still think this is a bit hard to understand but I dont have any better idea for now.

I am very happy with my new RSS feeds for now :-)

**Comment by willemarcel** [comment]
Yes, @tordans! I know it's a bit complicated. I'll try to find a better solution to this soon.

**Comment by georg-d** [comment]
Seems to be same use case as in https://github.com/mapbox/osmcha-frontend/issues/347
