### ISSUE TITLE
Problem with `Unknown iD Instance` detector?

### ISSUE THREAD

**Issue by batpad** [mapbox/osmcha-frontend#324]
I'm seeing a lot of recent changesets flagged with `Unknown iD Instance` - not sure if that's genuine or something like a new iD release that has not been accounted for in the flagging code.

Please feel free to close this issue if the flagging is behaving as wanted - just wanted to flag this so someone can double-check that the changesets being flagged are genuine. Thanks.

Example flagged changeset: https://osmcha.mapbox.com/changesets/63783595

cc @willemarcel

**Comment by willemarcel** [comment]
@batpad In the case of that changeset, it's missing the `host` tag. The iD available in the OSM website continues adding the `host` tag

Maybe it's a case of contacting the amazon logistics team and ask them to add the `host` tag.
