### ISSUE TITLE
"Hide trusted users" save error

### ISSUE THREAD

**Issue by Danysan1** [mapbox/osmcha-frontend#330]
## *Brief Description*
Filters with "Hide trusted users" set to "Yes" are corrupted on save ("Hide trusted users" is changed to "True", which does not work).

## When does this occur ?
When I set "Hide trusted users" to "Yes" ([screenshot](https://user-images.githubusercontent.com/8406735/49879799-0bcf8b80-fe2b-11e8-92da-e9768f79955c.png)) and save the filter ([screenshot](https://user-images.githubusercontent.com/8406735/49879918-4e916380-fe2b-11e8-936f-c1c9f16fca44.png))

## What  is the current behaviour, (attach relevant screenshots) ?
When i load the filter "Hide trusted users" is set to "True" instead of "Yes" and the filter fails ([screenshot](https://user-images.githubusercontent.com/8406735/49880025-8bf5f100-fe2b-11e8-9509-ed3d327516ab.png))

## What  is the expected behaviour ?
When loading the filter "Hide trusted users" should be "Yes"

## How do we replicate the issue ?

1. Set "Hide trusted users" to "Yes"
2. Save the filter
3. Open new tab
4. Open your OSMCha profile page in a new tab and load the saved filter

## Please tell us about your environment:
Windows 10 64 bit, Mozilla Firefox 65.0b3

**Comment by willemarcel** [comment]
Thanks for the report, @Danysan1. I'm checking it now

**Comment by willemarcel** [comment]
Solved with https://github.com/willemarcel/osmcha-django/commit/0b8c2e941693985bce5b9f6dfab4fbfb7e673b32

We will update the server tomorrow.

**Comment by willemarcel** [comment]
Server updated. You can test again @Danysan1

**Comment by Danysan1** [comment]
Now it works correctly. Thank you!
