### ISSUE TITLE
add PeWu "OSM history" as option for viewing feature object history

### ISSUE THREAD

**Issue by govvin** [mapbox/osmcha-frontend#334]
## *Brief Description*
Kindly consider adding [PeWu's OSM History](https://github.com/PeWu/osm-history) as additional button to OSM, and Deep History when a object feature is selected.

![image](https://user-images.githubusercontent.com/5821688/50346018-f1548b00-056b-11e9-84da-c9722c0e9415.png)

## What is the motivation / use case for this feature?
An alternative to visualize historical changes to a feature, or changes that was made in a particular element.

Compared to Deep History, where the main emphasis is attribute changes between changesets, PeWu visualizes both attribute and geometry between changesets. This allows users to conveniently visualize changes for validation or QA purposes.

![image](https://user-images.githubusercontent.com/5821688/50345658-d46b8800-056a-11e9-991b-2479975fea19.png)

## What  is the current behaviour, (attach relevant screenshots) ?
This is not currently available.

## What  is the expected behaviour ?
To be able to visualize changes made to a particular object.

**Comment by PeWu** [comment]
This looks like feature request to https://github.com/osmlab/changeset-map – this is the component that shows history links.
