### ISSUE TITLE
List relation members

### ISSUE THREAD

**Issue by Danysan1** [mapbox/osmcha-frontend#339]
## *Brief Description*
Show inside the changeset view the list of elements that compose a relation and their role.

## What is the motivation / use case for this feature?
Using OSMCha it is currently impossible to check how the members of relation have been modified. 

If someone only changed an object's role in a relation it's even impossible to check which relation has been modified (example: https://osmcha.mapbox.com/changesets/66055571 , which changed the role of two objects in https://www.openstreetmap.org/relation/7574133/history ).

When selecting an edited relation inside the changeset view it should be possible to see the list of it's members and their role, including how they have been changed. 

This could be shown in the same fashion as the tag details list: two columns (element and role) and one row for each element. If an element is added it will be shown in light blue. If an element is removed it will be shown in red. If a role is changed the element will occupy two rows (one orange with the old role and one yellow with the new role).

**Comment by willemarcel** [comment]
It was solved some months ago.
