### ISSUE TITLE
'known teams' user filter shortcuts

### ISSUE THREAD

**Issue by mvexel** [mapbox/osmcha-frontend#340]
## *Brief Description*
Breaking out an idea from https://github.com/mapbox/osmcha-frontend/issues/328, it would be great to have 'known mapping teams' available as pre-set user filters.

## What is the motivation / use case for this feature?
Organized editing teams are held to high mapping and community standards, which is now formalized in the Organized Editing Policy. OSMCha is a great tool to review those teams' work, so it would make sense to have 'known' teams available as filter presets.

## What  is the current behaviour, (attach relevant screenshots) ?
Right now, you would need to look up the team's user names and key them in one by one to create a filter.

## What  is the expected behaviour ?
You would see a drop down list with know mapping teams. You could possibly define your own 'teams' as well.

## Additional considerations
OSMCha is perhaps not the best place to maintain a canonical repository of what the 'known teams' are. There is some thought being put into creating a JSON representation of organized editing teams, which could be hosted in a separate Github repository. Once that is settled we could pull the known teams in from there.

**Comment by willemarcel** [comment]
Hi @mvexel 

I'm right now working to implement it! Thank you for the suggestion

**Comment by willemarcel** [comment]
@mvexel that features is already available. Check the instructions at: https://github.com/mapbox/osmcha-frontend/wiki/Mapping-Teams

**Comment by jharpster** [comment]
I've noticed that the members of the 'known teams' is static. For this feature to work as intended someone needs to continuously curate the lists of team members as they rotate from their original teams and on to new teams or out of the ecosystem.
