### ISSUE TITLE
Authentication on Swagger UI

### ISSUE THREAD

**Issue by ylinzhi** [mapbox/osmcha-frontend#346]
## *Brief Description*

At the Swagger UI, with correct token,  it will still fail to get response from OSMCha API.  401 Response with message "Authentication credentials were not provided" are the current output for requests.

## What  is the current behaviour, (attach relevant screenshots) ?

<img width="1005" alt="screen shot 2019-02-14 at 5 13 06 pm" src="https://user-images.githubusercontent.com/35787039/52794748-7eeebb80-3081-11e9-8d80-41def327b61d.png">

## What  is the expected behaviour ?
Respond with successful run and API details in JSON format

## When does this occur ?
When using Swagger UI

## How do we replicate the issue ?

Set harmful=1, check_date__gte=2018-01-21, check_date__lte=2018-01-22 for parameters in "GET /api/v1/changesets/" section,  then run it

## Please tell us about your environment:

MacBook Pro
Chrome

**Comment by willemarcel** [comment]
Hi @ylinzhi !

Sorry for the delay. On the dialog that opens when you click on the `Authorize` button, when you paste your token, add also the word `Token `.
For example, if your token is `xyz1234`, you will add `Token xyz1234`

**Comment by ylinzhi** [comment]
Hi @willemarcel 

Thanks for the clarification!
