### ISSUE TITLE
Osmcha doesn't work

### ISSUE THREAD

**Issue by literannn** [mapbox/osmcha-frontend#349]
OSMCha doesnot work for edits after time about day ago. Shows smth like that:
![osmcha](https://user-images.githubusercontent.com/46343992/54706486-1b5c2000-4b50-11e9-806c-f1e435fd59bf.jpg)

Older changesets are visualised properly

**Comment by willemarcel** [comment]
We are having problems processing the changeset data to the map
visualization. Unfortunately, we won't be able to fix it until tomorrow.
Sorry for the inconvenience.

**Comment by zzptichka** [comment]
Thanks for working on it.
In the meantime one can open a changeset in Achavi (via "Open with" dropdown). Not as convenient as OsmCha but gets the job done.

**Comment by literannn** [comment]
Unfortunately, Achavi does not work in Russia, thanks to https://en.wikipedia.org/wiki/Internet_censorship_in_Russia#Increase_in_Internet_censorship :-/

**Comment by InsertUser** [comment]
Is there a fix coming soon?

**Comment by flohoff** [comment]
Any news? Seems to be down for a week - Is there anything we can help with?

**Comment by mzdraper** [comment]
👋 We're investigating this internally. We'll update this issue once we have more information. Thank you for your patience.

**Comment by NonnEmilia** [comment]
According to the console it give me a "403 Forbidden".

If it helps I have a screenshot:
![immagine](https://user-images.githubusercontent.com/2818194/54981303-41e2e680-4fa8-11e9-9ad9-89f2daf7d931.png)

**Comment by mmd-osm** [comment]
"403 Forbidden" simply means that the changeset json data hasn't been pushed to AWS S3 yet. It's pretty much meaningless to analyze the issue at hand.

**Comment by willemarcel** [comment]
We're still having problems on the OSMCha server infrastructure. There is a delay of 10 to 11 hours between the time a new changeset is created on OpenStreetMap database and the time its visualization is available on OSMCha.

We hope all the issues will be fixed this week.

Thank you for your understanding,

**Comment by muralito** [comment]
Without this tool I am unable to keep an eye in the BBox of my interest. :-(, because it's makes very easy to understand what and how was changed, for every element of the changeset.

Thanks for your efforts. The delay I am seeing is bigger, Now I cannot analyze anything newer than 2019-03-19.

**Comment by flohoff** [comment]
Hi,

i am still seeing no solution. I worked for some hours a couple days back and we are now back to completely dysfunctional or is that just me?

Flo

**Comment by mmd-osm** [comment]
Reason seems to be this one: https://github.com/osmlab/changeset-map/pull/179#issuecomment-481691303

**Comment by literannn** [comment]
Thanks, now Osmcha works good with new edits. Are there any plans to fix visualization for changesets from 19 March to 9, April?

**Comment by willemarcel** [comment]
@literannn On the next week we will work to generate the visualization of the changesets that are missing.

Thank you very much @amishas157 @geohacker and @batpad for helping solve those issues. :clap:

**Comment by mmd-osm** [comment]
@willemarcel : did you read my comment about the outdated changeset-map? That would be the remaining bit to solve this issue, as the old version still causes syntax errors.

**Comment by willemarcel** [comment]
@mmd-osm thanks for allerting! Yes, I noticed that the changes didn't get on production, although I have updated the changeset-map version on osmcha-frontend. I think there is some error on the package instalation. Checking it now.

**Comment by mmd-osm** [comment]
Ok, great! 

Byt the way, did you notice that https://s3.amazonaws.com/mapbox/real-changesets/production/69131255.json seems to be the last cs on AWS. The next one https://s3.amazonaws.com/mapbox/real-changesets/production/69131256.json and everything after that one aren't available yet.

**Comment by literannn** [comment]
it doesn't work again, for about 20 hours :-(

**Comment by tordans** [comment]
@willemarcel the problem seems to shift somehow. Some changesets work fine. But others are still - half? - broken. Like https://osmcha.mapbox.com/changesets/69204689/ which loads the changeset-comment, but shows an error in console and does not render the map.

```
(index):1 -1
console.js:35 uncaught at s TypeError: Cannot read property 'indexOf' of null
…
s3.amazonaws.com/mapbox/real-changesets/production/69204689.json:1 

Failed to load resource: the server responded with a status of 403 (Forbidden)
overpass.maptime.in/api/interpreter?data=[out:xml][adiff:%222019-04-14T14:49:31Z,%22,%222019-04-14T14:49:32Z%22];(node(bbox)(changed);way(bbox)(changed);relation(bbox)(changed));out%20meta%20geom(bbox);&bbox=13.4426336,52.4664075,13.4426336,52.4664075:1 

Failed to load resource: the server responded with a status of 400 (Bad Request)
```

**Comment by mmd-osm** [comment]
The SSL certificate on overpass.maptime.in has expired on 04/28/2019.

https://overpass.maptime.in/

**Comment by willemarcel** [comment]
Thanks for reporting the issue with the SSL certificate, @mmd-osm ! @amishas157 fixed it on Monday.

**Comment by grinapo** [comment]
Got 403 forbidden from amazonaws just now:
https://s3.amazonaws.com/mapbox/real-changesets/production/70885956.json

**Comment by tordans** [comment]
I still get random 403.
Do we know when those happen?
Is there a way to re-start the process that prepares the changeset for certain changesets, so they go away?

Example:
- https://osmcha.mapbox.com/changesets/70770306/
- https://overpass-api.de/achavi/?changeset=70770306

```
s3.amazonaws.com/mapbox/real-changesets/production/70770306.json:1 
Failed to load resource: the server responded with a status of 403 (Forbidden)

overpass.maptime.in/api/interpreter?data=[out:xml][adiff:%222019-05-30T13:20:53Z,%22,%222019-05-30T13:21:00Z%22];(node(bbox)(changed);way(bbox)(changed);relation(bbox)(changed));out%20meta%20geom(bbox);&bbox=13.4245722,52.4771607,13.4364570,52.4850931:1 
Failed to load resource: the server responded with a status of 400 (Bad Request)
```
