### ISSUE TITLE
Error when running locally in development mode – RangeError: Invalid typed array length: -4095

### ISSUE THREAD

**Issue by tordans** [mapbox/osmcha-frontend#356]
I am trying to get this repo running locally.

# Firefox + httpS

I start the server `yarn start`.
When I open `https://localhost:3000/` in Firefox I get the error below.

This might be related to something that only happens if httpS is on (see below).

```
Starting the development server...

internal/buffer.js:928
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:928:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:165:17)
    at Stream.<anonymous> (/Users/tordans/Development/osmcha-frontend/node_modules/handle-thing/lib/handle.js:120:12)
    at Stream.emit (events.js:201:15)
    at endReadableNT (/Users/tordans/Development/osmcha-frontend/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ 
```

I am on the current master. With MacOS.

Does anyone know what is going on?

--- 

# Chrome + http

I did a different try with Chrome.
Chrome does not allow self signed certificates. So I remove the force-ssl from the start script and the JS-https-redirect locally. 

This way, I was able tho render the page. And by following https://github.com/mapbox/osmcha-frontend/blob/master/CONTRIBUTING.md#how-to-login-when-running-locally-in-development-mode I was also able to log in.

However, I did not see any changesets. Likely, because https://osmcha-django-staging.tilestream.net/api/v1/changesets/?page_size=75&page=1&date__gte=2019-05-11 needs an authentication which the local request does not provide. 

I assumed this was due to the missing httpS, so I tried the approach above with the described result.

--- 

Any ideas how to get this going?

**Comment by willemarcel** [comment]
Hi @tordans 

Generally I have this error when I run osmcha-frontend with most updated nodejs versions. with 9.10 it works great. Let me know if it works for you. Soon I'll update the dependencies. In the past we had problems deploying OSMCha with https, so the solution the infrastructure team found was to add that redirect on the client, which is not ideal...

About the fact that you're not seeing any changesets, it's because we stopped populating the staging database in mid 2017. Try to set the start date on May 2017, and you'll have changesets results.

**Comment by tordans** [comment]
Thanks @willemarcel, I got it running. I updated the readme to make it easier for the next person to figure this out. Please check out https://github.com/mapbox/osmcha-frontend/pull/358.

**Comment by willemarcel** [comment]
@tordans I updated create-react-app. Now you can run osmcha and changeset-map with modern nodejs versions, no need of nvm anymore
