### ISSUE TITLE
overpass parsing error

### ISSUE THREAD

**Issue by grinapo** [mapbox/osmcha-frontend#361]
## *Brief Description*
Change cannot be displayed. I can't tell whether it's due to #349 or not, but I guess osmcha should not generate syntactically invalid requests anyway.

## Description of the problem
Request: 
```
https://overpass.maptime.in/api/interpreter?data=[out:xml][adiff:%222019-06-03T13:14:59Z,%22,%222019-06-03T13:15:00Z%22];(node(bbox)(changed);way(bbox)(changed);relation(bbox)(changed));out%20meta%20geom(bbox);&bbox=18.9357333,47.3271267,18.9357333,47.3271267
```

Response:
```
Error: line 1: parse error: ';' expected - ')' found.

Error: line 1: parse error: Unexpected end of input.

Error: line 1: static error: Element "print" cannot be subelement of element "union". 
```

## When does this occur ?
Clicking on a change, before anything is displayed about it.

## Please tell us about your environment:
Debian/sid, Firefox nightly.

**Comment by mmd-osm** [comment]
This was already fixed here: https://github.com/osmlab/changeset-map/pull/179#issuecomment-481691303

For unknown reasons, the fix hasn't made it into production yet.

**Comment by grinapo** [comment]
It seems wishful thinking is needed. Can't help it from here.
