### ISSUE TITLE
"Yandex Panoramas" is not suspect but "Yandex" is

### ISSUE THREAD

**Issue by mikelmaron** [mapbox/osmcha-frontend#366]
## *Brief Description*

“Yandex Panoramas” is now an ok source for OSM. However “Yandex” on its own is still suspect, since that could be imagery or their maps

Not sure if this means change to the logic in 
https://github.com/willemarcel/osmcha/blob/master/osmcha/changeset.py#L153

Suspect word list is at https://github.com/willemarcel/osmcha/blob/d9a8bc4fd55b859396a65e2e17863c6b4e93a5ce/osmcha/suspect_words.yaml#L12

## What is the motivation / use case for this feature?

Yandex Panoramas are now an ok source

## What  is the current behaviour, (attach relevant screenshots) ?

Anything with "Yandex" in it gets flagged

**Comment by willemarcel** [comment]
Fixed with:
https://github.com/willemarcel/osmcha/commit/f2fd7ea116ee3d26d81798d808ae7e44a4ab95f6
https://github.com/willemarcel/osmcha-django/pull/190
