### ISSUE TITLE
OSMCha status popup covers property diffs

### ISSUE THREAD

**Issue by pwithnall** [mapbox/osmcha-frontend#367]
The ‘OSMCha Status’ ‘There is a delay of 5 minutes…’ popup is quite annoying.
 * It’s shown even if the changeset diff is older than 5 minutes and is being shown.
 * It covers up the diff of properties on a node/way, which is one of the main things someone’s going to be looking at if they’re reviewing a changeset.
 * Closing it using the ‘x’ in its corner doesn’t persist  — it’ll appear again the next time I open OSMCha in a tab.

**Comment by iandees** [comment]
I came here to report this as well 😄. Here's a screenshot of the alert covering up the important information:

![image](https://user-images.githubusercontent.com/261584/60184238-4f00b300-97ed-11e9-8468-1f99a7ac3280.png)

**Comment by gileri** [comment]
This got fixed in the 0.60 version via this [commit](https://github.com/mapbox/osmcha-frontend/commit/c45615b72cc416e9b80b4b979d9d406e8f9fc7fd)

**Comment by pwithnall** [comment]
Sort of. Two of the three problems still remain, but they are less immediately annoying:
 * It’s shown even if the changeset diff is older than 5 minutes and is being shown.
 * Closing it using the ‘x’ in its corner doesn’t persist — it’ll appear again the next time I open OSMCha in a tab.

I’ll open a new issue for them. Thanks.
