### ISSUE TITLE
Use warning tags added by iD as suspicion reasons

### ISSUE THREAD

**Issue by willemarcel** [mapbox/osmcha-frontend#376]
Use the information provided by iD editor as source for suspicion reasons https://github.com/openstreetmap/iD/tree/a365da8a89a53380ba4a979a2151a87d4e045a8a/modules/validations

**Comment by tordans** [comment]
Out of curiosity, is this meant as 
a. "Copy the validation rules over to Osmcha and run them there" or
b. "Use the changeset-tags about non-solved / ignored validation rules from iD, see https://github.com/openstreetmap/iD/issues/6123"
?

Personally, I think option b fits more into osmcha.

**Comment by willemarcel** [comment]
@tordans We are just reading the changeset tags and associating the issues with the changeset on osmcha database. Closing it as it was already implemented some weeks ago.
