### ISSUE TITLE
Some changesets fail to load

### ISSUE THREAD

**Issue by flyingpimonster** [mapbox/osmcha-frontend#378]
## Brief Description
Some changesets fail to load, for example many of this user's: <https://www.openstreetmap.org/user/harshjs>

The loading spinner continues indefinitely, the map stays black, and no data is loaded. No error messages are produced.

## Details

The network logs show a request to `https://s3.amazonaws.com/mapbox/real-changesets/production/72862303.json` which returns a 403.

Then, a request is made to `https://overpass.maptime.in/api/interpreter`, which fails with a 400 because the query is missing a semicolon:

```
[out:xml][adiff:"2019-07-31T15:27:16Z,","2019-07-31T15:27:19Z"];
(
    node(bbox)(changed);
    way(bbox)(changed);
    relation(bbox)(changed) <--- here
);
out meta geom(bbox);
```

## Replicating:
I can't figure out exactly how to reproduce, but [this changeset](https://osmcha.mapbox.com/changesets/72862303) is one that triggers the bug.

## Environment:
Firefox 68.0, using osmcha.mapbox.com

**Comment by willemarcel** [comment]
Thanks for the report, @flyingpimonster . We solved this problem last night.
