### ISSUE TITLE
Question: May overpass.maptime.in/api/ be used by StreetComplete?

### ISSUE THREAD

**Issue by westnordost** [mapbox/osmcha-frontend#381]
## I'm submitting a question

Hi @willemarcel, I have a question regarding the overpass instance hosted on overpass.maptime.in. Is it hosted by you, or else do you know who I might ask about it? I am sorry if this is not the right channel to contact you (about that), it seemed the easiest way to reach you. (Otherwise, my email is osm at westnordost.de)

I would like to include this server in the alternative download (=overpass) server selection option in the settings of StreetComplete, with the hoster's permission and if it does not regularly lag behind too much. Or even maybe, if this instance could be made into the default download server in the app if it is clear that this instance will stay being around and being maintained.

(See also https://github.com/westnordost/StreetComplete/issues/1514 )

**Comment by willemarcel** [comment]
Hi @westnordost ! I think this server is managed by @batpad, @amishas157 and @geohacker, so they can answer you better than me

**Comment by westnordost** [comment]
Thank you for the answer, I will ask them!
