### ISSUE TITLE
OSMCha doesn't work

### ISSUE THREAD

**Issue by literannn** [mapbox/osmcha-frontend#384]
OSMCha does not show changesets for about half a day. Only pink background and "Map failed" box.

**Comment by andrewharvey** [comment]
https://s3.amazonaws.com/mapbox/real-changesets/production/73478312.json is returning 403.

**Comment by willemarcel** [comment]
Thanks for reporting, @literannn and @andrewharvey ! It seems our Overpass instance stopped. We will be working on it in some hours

**Comment by willemarcel** [comment]
The issue is solved!

**Comment by andrewharvey** [comment]
https://s3.amazonaws.com/mapbox/real-changesets/production/73494566.json still says Access Denied for me.

**Comment by willemarcel** [comment]
I think it's not an issue of OSMCha, overpass is running out of memory when querying the changeset, and the same happened on achavi: https://overpass-api.de/achavi/?changeset=73494566&relations=true

**Comment by nrenner** [comment]
These are two different things.

The achavi-like, live adiff query is only run as a fallback when the S3 json is not available.

The cached S3 json files are generated by a script from minutely augmented diffs that don't have the memory issue, see:
https://www.openstreetmap.org/user/geohacker/diary/40846
https://github.com/drolbr/Overpass-API/issues/346#issuecomment-293502943

After an outage, the S3 script would ideally start over after the last successful json or run separately to fill up the missing ones.
