### ISSUE TITLE
Newly created way that is part of a relation not shown in changeset

### ISSUE THREAD

**Issue by westnordost** [mapbox/osmcha-frontend#388]
# Bug Report

For a specific changeset, I observed that a way that was added in the changeset was missing from the visual display.

## Current behaviour
The changeset https://osmcha.mapbox.com/changesets/74262576 displays like this:

<img width="537" alt="Bildschirmfoto 2019-09-10 um 12 07 49" src="https://user-images.githubusercontent.com/4661658/64605282-115eff80-d3c4-11e9-8329-831f65c3ed92.png">

The very first segment of "Bäckergasse" is not displayed at all.

## Expected behaviour

The way is shown and highlighted to be a way that was added in this changeset.

## Other Information:
- The changeset both contains v1 **and v2** of the added way. Thus, might be related to #265
- The added way is part of a relation

**Comment by willemarcel** [comment]
It's solved!

![image](https://user-images.githubusercontent.com/666291/93607871-496a2c80-f9a0-11ea-80f6-bdcde7f42cd5.png)
