### ISSUE TITLE
Feed and watchlist: 500 internal error 

### ISSUE THREAD

**Issue by cascafico** [mapbox/osmcha-frontend#389]
I want to track some OSM vandalism, relying on a compiled OSMCHA watchlist.

Saved filter RSS links work fine (ie: bbox, polygon AOI etc).  I successfully tested them on a couple of Telegram feed readers. But whenever I set "Watchlisted users to "yes", save the updated filter and update telegram bots RSS link, such link is not funcional anymore, yelding something like "(500) internal server error".

All above operations are done on Chromium (v.60.0.31112.89) and Chrome (v.73.0.3683.75)

**Comment by willemarcel** [comment]
@cascafico thank you for your report. I'll analyse this error this week.

**Comment by camelCaseNick** [comment]
I have the same problem with getting a 500 Internal Server Error. It also occurs when trusted mapped are hidden, but not, when verified mapping teams are.

**Comment by BalooUriza** [comment]
At this point, the feeds don't work at all, with feed URLs providing the same thing as the normal web interface.

**Comment by camelCaseNick** [comment]
@BalooUriza If you have a filter list with _watchlisted users_ or _trusted mappers_ settings, you get a 500, but under that circumstances you always get redirected to `/`, so that you see the normal web interface. (look into the inspector if you don't trust me)

**Comment by BalooUriza** [comment]
Is it possible to get that corrected when such filters are in place??

**Comment by momu** [comment]
@willemarcel thanks for fixing it, when will the fix be available on https://osmcha.org?

**Comment by willemarcel** [comment]
@momu we'll update it today yet I think.

**Comment by willemarcel** [comment]
@momu osmcha.org is updated!
