### ISSUE TITLE
Unable to create new editing teams

### ISSUE THREAD

**Issue by garylancelot** [mapbox/osmcha-frontend#406]
## *Fields are greyed out and not editable.*

I am unable to create new teams.

## What  is the current behaviour, (attach relevant screenshots) ?

When trying to add a new mapping team at https://osmcha.mapbox.com/teams, both the Name and Users fields are greyed out and unusable, rendering the feature useless.

![image](https://user-images.githubusercontent.com/25396258/67511544-5da08f00-f654-11e9-83ec-788929c14ccd.png)

## What  is the expected behaviour ?

Editable fields.

## When does this occur ?

When a user selects "+" to add a new mapping team.

## Please tell us about your environment:

Microsoft Edge Version 78.0.276.20 (Official build) Beta (64-bit), Chrome Version 77.0.3865.120 (Official Build) (64-bit). This is consistent across various browsers and various users.

**Comment by willemarcel** [comment]
It was fixed some weeks ago, @garylancelot
