### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by kepta** [mapbox/osmcha-frontend#41]
Currently the mobile view is in denial, we might need to fix mobile related issues.
I will add all the minor issues related to mobile and small screens here.

**Comment by kepta** [comment]
cc @rasagy

**Comment by ajithranka** [comment]
Mostly done in PR #148. Thanks kepta!
Let's defer further improvements to the next milestone.

**Comment by kepta** [comment]
Lets open a new ticket if needed
