### ISSUE TITLE
When opening a changeset with only one object modified, select it

### ISSUE THREAD

**Issue by gileri** [mapbox/osmcha-frontend#413]
## *Brief Description*
When opening a changeset with only one object modified, select it in order to display the info/action box.

## What is the motivation / use case for this feature?
Quicken the review of one-object changesets.

## What  is the current behaviour, (attach relevant screenshots) ?
The object is unselected by default.

**Comment by willemarcel** [comment]
@gileri good suggestion! I'll work on it soon!
