### ISSUE TITLE
[User Testing] Feedback Master ticket

### ISSUE THREAD

**Issue by rasagy** [mapbox/osmcha-frontend#42]
Feel free to share any feedback on this ticket (bugs, feature request, workflow feedback)

![bugs](https://cloud.githubusercontent.com/assets/1117531/26774340/73825332-49ed-11e7-8a88-43584cfefa76.gif)

cc @manoharuss @krishnanammala @chtnha @kepta @ajithranka @geohacker @batpad

**Comment by rasagy** [comment]
**What**
Filters > Reasons dropdown stops working after selecting two, but you can still type and add more filters.

![osmcha-reasons](https://cloud.githubusercontent.com/assets/1117531/26774862/e9a7c05e-49ef-11e7-8dd4-011dcbd2d7dd.gif)

**Expected**
Dropdown should continue to show up when you select two options. Also the UI shouldn’t expand.

**Comment by rasagy** [comment]
**What**
If comment has a link, the changeset details has a horizontal scroll

<img width="466" alt="screenshot 2017-06-05 13 18 40" src="https://cloud.githubusercontent.com/assets/1117531/26775252/b0860f90-49f1-11e7-8ae9-5cb221d05007.png">

**Expected**
Truncate the url or set max-width that breaks the url to next line.

**Comment by rasagy** [comment]
**What**
When `Source` has a link, the three-column layout doesn’t work well

<img width="466" alt="screenshot 2017-06-05 13 21 26" src="https://cloud.githubusercontent.com/assets/1117531/26775345/29d7a8ae-49f2-11e7-80a1-172b471799b8.png">

**Expected**
Either truncate link and let someone copy the whole text to the clipboard, or make the columns as individual rows.

**Comment by rasagy** [comment]
**What**
Satellite imagery gives 404, and map style toggles don’t work (getting a 200).

![image](https://cloud.githubusercontent.com/assets/1117531/26775446/a6eeccc8-49f2-11e7-973a-30b9996b3c9c.png)

![image](https://cloud.githubusercontent.com/assets/1117531/26775483/cb9e00ca-49f2-11e7-8d67-a984980ffd31.png)

**Expected**
We probably need to fix the changeset map integration, and show errors if this happens

**Comment by rasagy** [comment]
### Feature parity with old Filters UI
(Listing these down including known issues for us to check off)

- [ ] `Date` needs a presets section
- [ ] `Reasons` need all/any
- [ ] `Reviewed`, `harmful`, `flagged`, needs three states (Yes, No, All)
- [ ] `Users` & `checked by` doesn’t need to be a drop down _(Up for discussion)_
- [ ] Fewer, more relevant options in `Order by`
- [ ] `Bbox` needs a map control + file upload option

**Comment by willemarcel** [comment]
![captura de tela de 2017-06-16 16-44-49](https://user-images.githubusercontent.com/666291/27242375-4447acc4-52b3-11e7-9c92-75d8ade6ff6e.png)

Some fields placeholder text are lighter than others (and much difficult to read). I prefer the darker colour.

**Comment by kepta** [comment]
Closing this ticket as it is difficult to track.
@rasagy Could you open new tickets for the issues mentioned here which aren't resolved .
