### ISSUE TITLE
No result by filtering old user/changeset - resource not found

### ISSUE THREAD

**Issue by iriman** [mapbox/osmcha-frontend#423]
I try the following filter:

["https://osmcha.mapbox.com/?filters={\"date__gte\":[{\"label\":\"\",\"value\":\"\"}],\"users\":[{\"label\":\"iran_provinces\",\"value\":\"iran_provinces\"}]}"](https://osmcha.mapbox.com/?filters=%7B%22date__gte%22%3A%5B%7B%22label%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%2C%22users%22%3A%5B%7B%22label%22%3A%22iran_provinces%22%2C%22value%22%3A%22iran_provinces%22%7D%5D%7D)

but no results:

![image](https://user-images.githubusercontent.com/8467903/70870928-b3d3e380-1fae-11ea-90f9-25e785977a7d.png)

Also I tried to view the [changeset 4266075](https://osmcha.mapbox.com/changesets/4266075/) but I got these errors:

![image](https://user-images.githubusercontent.com/8467903/70870917-93a42480-1fae-11ea-80f1-0bbc16928283.png)

**Comment by willemarcel** [comment]
Hi @iriman
The last changeset of iran_provinces was 10 years ago (https://www.openstreetmap.org/user/iran_provinces/history). OSMCha doesn't have changesets created before October 2015.
