### ISSUE TITLE
OSMCha is not refreshing changesets

### ISSUE THREAD

**Issue by BrackoNe** [mapbox/osmcha-frontend#428]
Just to make heads up, OSMCha haven't been updated for 18 hours at the moment. It doesn't pick new changesets from the OSM.

Best Regards,
Nemanja

**Comment by willemarcel** [comment]
@BrackoNe We're aware and the team is working to fix it.

**Comment by BrackoNe** [comment]
> @BrackoNe We're aware and the team is working to fix it. Thanks for reporting!

Thanks for the information!

Very best regards,
Nemanja
