### ISSUE TITLE
using emojis 👍 👎 instead of colors

### ISSUE THREAD

**Issue by kepta** [mapbox/osmcha-frontend#43]
The current sidebar is peppered with so many colours that it becomes a bit overwhelming to grab necessary information. 
I feel adding emojis (which people are familiar with) and icons would help reduce the information clutter. 

cc @rasagy @geohacker @manoharuss

**Comment by kepta** [comment]
![screen shot 2017-06-05 at 3 39 36 pm](https://cloud.githubusercontent.com/assets/6966254/26779982/3cc20d20-4a05-11e7-8dbb-4f2b37eb9d83.png)

**Comment by geohacker** [comment]
May be change the background colour of the entire row?

**Comment by rasagy** [comment]
@kepta @geohacker Good point, adding this in the list of things we want to iterate (from a design perspective). 🙇

**Comment by kepta** [comment]
![screen shot 2017-06-05 at 5 38 07 pm](https://cloud.githubusercontent.com/assets/6966254/26783443/d10cc55a-4a15-11e7-9e02-d53d669dc25c.png)
added some icons to make it a bit smoother.

**Comment by geohacker** [comment]
@kepta Nice! The icons look good but I think we should stick to using big text in green, yellow and red for consistency across tools and OSM. @rasagy
