### ISSUE TITLE
Zoom in to highlighted feature

### ISSUE THREAD

**Issue by ylinzhi** [mapbox/osmcha-frontend#431]
It would be nice that, when clicking on `Map` under `Action` to review the flagged feature,  it also enables zooming in to the highlighted feature

<img width="1263" alt="Screen Shot 2020-02-04 at 12 31 10 PM" src="https://user-images.githubusercontent.com/35787039/73784546-87387e80-474a-11ea-96d9-09c4c51c08b3.png">

**Comment by willemarcel** [comment]
@ylinzhi this feature is already available on https://osmcha.org
