### ISSUE TITLE
Geocoding error. The changesets showing dragged nodes from the relation to the null island.

### ISSUE THREAD

**Issue by korolenok** [mapbox/osmcha-frontend#440]
## *Brief Description*

The changesets showing a huge dragged node from the relation to the null island, that wasn't supposed to be. This problem affects data quality assessment.

## What  is the current behaviour, (attach relevant screenshots) ?

The problem can be observed in the following changesets by clicking to the relations:
[82367820](https://osmcha.org/changesets/82367820/)
[82368321](https://osmcha.org/changesets/82368321/)
[82392275](https://osmcha.org/changesets/82392275/)
[82513769](https://osmcha.org/changesets/82513769)
[82513541](https://osmcha.org/changesets/82513541)

For example, the node (Node 6496477147) from the relation in the changeset (82368321) has never been in the null island:

<img width="1043" alt="Screen Shot 2020-03-25 at 10 14 56" src="https://user-images.githubusercontent.com/42146546/77511235-b7b2b400-6e81-11ea-8c37-86f8adb5b703.png">
<img width="1288" alt="Screen Shot 2020-03-25 at 10 14 11" src="https://user-images.githubusercontent.com/42146546/77511229-b3869680-6e81-11ea-9847-05743a0082ee.png">

## What  is the expected behaviour ?

Given that the data doesn't contain any dragged nodes, the changeset should not contain information if they were.

## When does this occur ?

All examples above used the ID editor v2.17.2. But this problem is observed selectively.

## Please tell us about your environment:

Google Chrome Version 80.0.3987.149

**Comment by planemad** [comment]
Issue observed upstream in changeset-map https://osmlab.github.io/changeset-map/#82367820

<img width="973" alt="Screen Shot 2020-03-27 at 10 35 58 AM" src="https://user-images.githubusercontent.com/126868/77766981-c8486300-7016-11ea-9708-542425c77353.png">

**Comment by planemad** [comment]
A very simple fix would be to catch any nodes if for some reason a coordinate could not be found and avoiding plotting them at null island.

**Comment by willemarcel** [comment]
Solved with https://github.com/osmlab/changeset-map/pull/208. We will deploy it in the next few days.
