### ISSUE TITLE
Update domain next to one-line-github-description

### ISSUE THREAD

**Issue by tordans** [mapbox/osmcha-frontend#442]
ATM, it says
> Frontend for the osmcha-django REST API https://osmcha.mapbox.com

Ideally, this would also say …
> Frontend for the osmcha-django REST API https://osmcha.org/

This cannot be edited via PR, its something the repo-admin has to change – so no PR possible :-).

**Comment by willemarcel** [comment]
Thanks, @tordans ! It's done.
