### ISSUE TITLE
Opening data in JOSM in ney layer

### ISSUE THREAD

**Issue by literannn** [mapbox/osmcha-frontend#457]
When opening feature in JOSM, it always opens in new layer. It's not convenient when work with big quantity of changesets or objects. May someone fix it (or make a setting), to open objects in existing JOSM layer (like remote control from www.openstreetmap.org, when press "edit with JOSM")?

![изображение](https://user-images.githubusercontent.com/46343992/81707696-7d28c900-9479-11ea-815a-b952c74a28f1.png)

**Comment by gileri** [comment]
This PR should have fixed that already : #414
Maybe it hasn't been deployed to osmcha.org ?

**Comment by willemarcel** [comment]
@gileri thanks, closing it

**Comment by literannn** [comment]
I've tried it right now, and it still doesn't work. Objects in JOSM opens in new layer. Firefox, Chrome - the same.
