### ISSUE TITLE
Show the number of comments right in the list on the sidebar

### ISSUE THREAD

**Issue by antonvolkau** [mapbox/osmcha-frontend#458]
## *Brief Description*

Showing the number of comments should help to identify suspicious/problematic changesets quickly. The long work with OSMCha within the Mapbox Streets Review prompts this suggestion as very helpful.

An example of how this might look:
![comment_number](https://user-images.githubusercontent.com/43467428/82945093-06291f80-9fa5-11ea-98a8-4c5d28e33b8c.png)

## What is the motivation / use case for this feature?

The number of comments is a good point to pay attention to the changeset. 

## Please tell us about your environment:

Google Chrome

## Other Information / context:

Related to https://github.com/mapbox/osmcha-frontend/issues/410

cc @willemarcel

**Comment by willemarcel** [comment]
@antonvolkau The problem here is that the number of comments are dynamic, and we would need to make an API request to each changeset to get updated values.

**Comment by willemarcel** [comment]
That issue is solved and deployed.
