### ISSUE TITLE
A user page

### ISSUE THREAD

**Issue by kepta** [mapbox/osmcha-frontend#46]
Creating this ticket to track user page related things.

**Comment by kepta** [comment]
@rasagy Tagging you for fixing the user related ui.

The current view looks like this.

![image](https://user-images.githubusercontent.com/6966254/26914579-c406b6aa-4c3f-11e7-8700-3c321b878e23.png)

![image](https://user-images.githubusercontent.com/6966254/26914608-e645f258-4c3f-11e7-93eb-87819ac41be5.png)

cc @batpad @ajithranka

**Comment by willemarcel** [comment]
I suggest to change `Age` to `Contributor since X time ago`.

In the changeset detail tab you are showing the `username(nº of edits)`. I would prefer to have it in another place or make it clear that the number is the edits count of the user. At first look, I thought it was the `uid` of the user

**Comment by kepta** [comment]
As per @rasagy he is busy with other things.
I think we are fine with the ui for this release

**Comment by rasagy** [comment]
This got updated:

Includes feedback from #126, #112, #111:
![image](https://user-images.githubusercontent.com/1117531/27483836-91e8b7d4-5844-11e7-9cb7-976a974ac4cf.png)

This will expand more once we start doing settings, and lists like #127:
![image](https://user-images.githubusercontent.com/1117531/27483854-a0e28076-5844-11e7-9823-2dd93688af8b.png)

We’re still iterating on the layout (center-aligned vs 2-column-left-aligned), will update this ticket with any update on this front.

**Comment by kepta** [comment]
I guess the next step would be to make the 
Good and bad clickable.

**Comment by willemarcel** [comment]
This is awesome!!!
