### ISSUE TITLE
Expose Token $access_token more directly in frontend or just change API to use only access_token for authorization

### ISSUE THREAD

**Issue by manoharuss** [mapbox/osmcha-frontend#463]
#### *Brief Description*

<img width="681" alt="Slack___tilesets-api___Mapbox" src="https://user-images.githubusercontent.com/8921295/86671224-6f984700-bfc3-11ea-8837-f06e89628a36.png">

<img width="473" alt="OSM_Changeset_Analyzer" src="https://user-images.githubusercontent.com/8921295/86671401-9b1b3180-bfc3-11ea-982f-afcc1f2b380a.png">

## What is the motivation / use case for this feature?

Easier to onboard to new users.
Using  `Token  xxxx` works flawlessly on swaggerUI because API supports it. But pasting the token alone does not work. This is not easy to understand for API users.

## What  is the current behaviour, (attach relevant screenshots) ?

Current behavior is  `Token xxxx` is the actual  accepted access  token.

## What  is the expected behaviour ?

Either only `xxxx` is the access_token in the API or  frontend shows `Token xxxx` in the settings page.

## When does this occur ?

Always because  API only accepts `Token xxxx` style param.

## How do we replicate the issue ?

1. Check https://osmcha.org/ profile and see the access  token.
2. Test the token with API docs https://osmcha.org/api-docs/ 
3. Using `Token xxxx` works but  not  the actual token alone

## Please tell us about your environment:

Using https://osmcha.org/

## Other Information / context:

cc @willemarcel

**Comment by willemarcel** [comment]
Solved by https://github.com/mapbox/osmcha-frontend/pull/466
