### ISSUE TITLE
Area filter only show change sets with modifications within the area

### ISSUE THREAD

**Issue by Hedaja** [mapbox/osmcha-frontend#464]
I'm submitting a feature request.

Area filter only show change sets with modifications within the area

This would allow focusing on changes made within the area of interest.

Oftentimes people forget to upload a changes before moving on with editing another part of the world or bots fix issues creating change sets that span huge area. For example: https://resultmaps.neis-one.org/osm-change-viz?c=87582017
These change sets also show up even if you have an area filter set for somewhere within the whole change set area, even though no modifications have been made within the filtered area.
If possible (I think it might be hard because you'd already have to load the modified geometry) the change set filter should check whether modifications have been made in the area or not and filter out those change sets that just happen to span across the filtered area.

**Comment by willemarcel** [comment]
@Hedaja Use the "BBox size bound" filter to limit the size of the changesets you want to filter. JOSM developers are discussing about limiting the area of changesets.
