### ISSUE TITLE
Add MapComplete team

### ISSUE THREAD

**Issue by joostschouppe** [mapbox/osmcha-frontend#468]
I have created a team for "MapComplete". I didn't read https://github.com/mapbox/osmcha-frontend/wiki/Mapping-Teams before I tried, and since the site does not say "now please make a Github issue to activate this team", I tried again. So there should now be two almost identical teams with MapComplete in the name. Could you activate this Team? Thanks!

**Comment by willemarcel** [comment]
Hi @joostschouppe ! I've trusted the team 145 (name: "MapComplete")

**Comment by joostschouppe** [comment]
Thanks wille!
I can't seem to be able to edit my team though. I expected that if I made it, it's associated with my username and should show up under the "My Teams" section...

**Comment by willemarcel** [comment]
@joostschouppe It's weird... I tested creating a team with another user, then I trusted it with my admin user and I could edit it again. Are you sure that you were using the `joostschouppe` user?

**Comment by joostschouppe** [comment]
Yes, pretty sure. Though my osm username is "Joost Schouppe", which might
cause issues here

Op ma 27 jul. 2020 11:49 schreef Wille Marcel <notifications@github.com>:
