### ISSUE TITLE
Fix pagination on front-end

### ISSUE THREAD

**Issue by batpad** [mapbox/osmcha-frontend#47]
Right now it always shows a list of page numbers even when those pages don't exist, and clicking on an invalid page number seems to break things a bit.

Also would be nice to display the count of results returned somewhere.

**Comment by kepta** [comment]
For the v1 release we are simply going to not show the pages which do not exist. 
Using some math on the result size and page size.

cc @rasagy

**Comment by kepta** [comment]
This was fixed in #58
