### ISSUE TITLE
404 on changesets result in an empty page

### ISSUE THREAD

**Issue by tordans** [mapbox/osmcha-frontend#471]
I am trying to open a changeset that is about an hour ago.

**Issue:**
OSMCha shows a blank page without any info. Only via the dev console I see that the changeset data is not avaliable, yet.

![Bildschirmfoto 2020-08-07 um 14 42 19 Kopie](https://user-images.githubusercontent.com/111561/89646957-060aa180-d8bd-11ea-8930-d7b2f43332f5.jpg)

**Suggested Solution:**
Show some 404-information in the area that shows the map view, or as a JS alert (or something similar). The info should say something along the lines of …
> The changeset you are looking for is not avaliable. 
> Is it the right changeset-ID? Please check the URL and try again.
> Is it a fairly new changeset? OSMCha has to process changesets wich ususally takes about an hour after it was created. Please try again later.

**Details:**
Changeset: https://www.openstreetmap.org/changeset/89090179#map=16/53.1583/13.2333&layers=N
Empty OSMCha Page: https://osmcha.org/changeset/89090179

Error Message from the console:
```
GET https://osmcha.org/changeset/89090179 404
89090179:1 -1
```

**Comment by andrewharvey** [comment]
you need to visit https://osmcha.org/changesets/89090179 instead

**Comment by tordans** [comment]
@andrewharvey true, thanks. 

But regardless, there should be an error message in the UI.

**Comment by tordans** [comment]
I found out, why I end up on this 404 page and created https://github.com/mapbox/osmcha-frontend/issues/481 which is IMO the smarter ticket to address, so I will close this one.
