### ISSUE TITLE
FR: add "Changeset by Comparison Visualization" to the "open with" menu

### ISSUE THREAD

**Issue by thibaultmol** [mapbox/osmcha-frontend#473]
Hi,

I found this new(?) tool from Neis that allows you to compare before and after a changeset
I know there are many tools at this point, but they all have their pros and cons depending on the type of changeset it is.
And I think this one has some unique advantages:

https://resultmaps.neis-one.org/osm-change-viz?c=89137311

Cheers,

**Comment by willemarcel** [comment]
@thibaultmol the main problem on adding it is that it only has data of changesets created in the last 30 days. What it provides in terms of visualization is available on OSMCha, you can enable/disable created/modified/deleted features.

**Comment by thibaultmol** [comment]
True.
I guess the main thing I like about it is that it has split views for created/modified/deleted features.
But yeah, guess it's fine
