### ISSUE TITLE
Fix feature selection remaining from previous changeset

### ISSUE THREAD

**Issue by batpad** [mapbox/osmcha-frontend#48]
Steps to reproduce:

Click on changeset in list.
Select a feature on changeset map.
Click on different changeset on list.

What happens:
The details for the feature selected from the previous changeset still shows on changeset map.

What I expect to happen:
Feature selection from previous changeset is cleared.

**Comment by kepta** [comment]
@batpad is this going to be a deal breaker for v1 release ?

**Comment by kepta** [comment]
This was fixed in #58
