### ISSUE TITLE
BBox filters don't work

### ISSUE THREAD

**Issue by literannn** [mapbox/osmcha-frontend#494]
Filters with BBox don't work already two days in all browsers. Tried to make new filter - the same.

![изображение](https://user-images.githubusercontent.com/46343992/99390480-bee37200-28e9-11eb-83b9-7cf44e3e490b.png)

After about one minute waiting in the left panel all last changesets of OSM are shown

**Comment by willemarcel** [comment]
@literannn thanks for the report. Since yesterday, we are having some issues on the database. We are working to fix it as soon as possible.

**Comment by willemarcel** [comment]
@literannn We are yet having some performance problems with bbox and geometry filters, but it's a bit better now. I believe you'll be able to do that query

**Comment by literannn** [comment]
No, BBox filters don't work

![изображение](https://user-images.githubusercontent.com/46343992/99666336-ef5b1580-2a7b-11eb-9bd0-1c63b5276958.png)

**Comment by willemarcel** [comment]
It seems you're setting both location and bbox filters. I was able to do a [query over Moscow](https://osmcha.org/?filters=%7B%22date__gte%22%3A%5B%7B%22label%22%3A%222020-11-09%22%2C%22value%22%3A%222020-11-09%22%7D%5D%2C%22in_bbox%22%3A%5B%7B%22label%22%3A%2237.1043%2C55.4575%2C38.0528%2C55.9917%22%2C%22value%22%3A%2237.1043%2C55.4575%2C38.0528%2C55.9917%22%7D%5D%7D).

**Comment by literannn** [comment]
no, "Moscow" is only name of this filter :) https://osmcha.org/filters?aoi=e53f863a-3d3b-4dd3-937b-81df6efe1223

But i'll try to make Bbox filter again

**Comment by willemarcel** [comment]
We finished a maintenance on the database and now I believe all filters are working properly and faster.
