### ISSUE TITLE
error 504 for RSS feeds

### ISSUE THREAD

**Issue by vinber** [mapbox/osmcha-frontend#495]
## I'm submitting a _(bug report/feature request/ support or question)_
bug report

## *Brief Description*

In liferea, rss reader, i use this source : https://osmcha.org/api/v1/aoi/99a8097f-5c45-45b6-ac25-073e8c7a3b7f/changesets/feed/

i want to follow each changeset in this area

## What  is the current behaviour, (attach relevant screenshots) ?

since yesterday error http 504
![Capture d’écran de 2020-11-17 21-49-56](https://user-images.githubusercontent.com/890869/99446189-f882a000-291e-11eb-9de3-1a7a3fe0257d.png)

In french : 
"La dernière mise à jour de cet abonnement a échoué !
Code d’erreur HTTP 504 : Erreur du serveur
Des erreurs sont survenues pendant l’analyse syntaxique de ce flux !
Détails
Impossible de détecter le type de ce flux ! Veuillez vérifier que la source pointe vraiment vers une ressource fournie dans un des formats supportés !

Sortie de l’analyseur syntaxique XML :
L’URL à laquelle vous voulez vous abonner pointe vers une page web et aucun flux n’a été découvert sur cette page. Cette page web ne supporte peut-être pas la découverte automatique de flux.La source pointe vers un document HTML.

In english 
_The last update of this subscription failed!
HTTP error code 504: Server error
Errors occurred during the syntax analysis of this stream!
Details
Impossible to detect the type of this flow! Please check that the source really points to a resource provided in one of the supported formats!

Output of the XML parser :
The URL you want to subscribe to points to a web page and no feed has been found on this page. This web page may not support automatic feed discovery - the source points to an HTML document.

Translated with www.DeepL.com/Translator (free version)_

## What  is the expected behaviour ?

See last changeset

## How do we replicate the issue ?

1. open liferea
2. add a new subcription (https://osmcha.org/api/v1/aoi/99a8097f-5c45-45b6-ac25-073e8c7a3b7f/changesets/feed/)
3.
4.

## Please tell us about your environment:

ubuntu / liferea

## Other Information / context:

it ok on the website / url for the same filter : https://osmcha.org/?aoi=99a8097f-5c45-45b6-ac25-073e8c7a3b7f

**Comment by willemarcel** [comment]
@vinber we had some database performance issues on the last 2 days, but it seems it's working better now! Keep us updated if you find some other issue.

**Comment by vinber** [comment]
I think it's still a bit "slow".
But first of all thank you for osmcha!

**Comment by willemarcel** [comment]
We finished a maintenance on the database and now I believe all filters are working properly and faster.

**Comment by RicoElectrico** [comment]
Hi, the feeds don't work again with a 504 error.

E.g. https://osmcha.org/api/v1/aoi/59e3062a-738c-4bb7-804d-daa95dc107fd/changesets/feed/
