### ISSUE TITLE
"new user" with edits over 9000?

### ISSUE THREAD

**Issue by Piskvor** [mapbox/osmcha-frontend#505]
## *Brief Description*

A long-time, frequent user's edit is tagged "Park added by new user". As I mostly review tagged edits, this tagging adds noise.

## What  is the current behaviour, (attach relevant screenshots) ?

https://osmcha.org/changesets/96076301?aoi=e76ef7d4-5ae9-4c96-ad14-98ab138d19d2

[A new instance of the bug](https://osmcha.org/changesets/98585327?aoi=e76ef7d4-5ae9-4c96-ad14-98ab138d19d2), same user:
![Screenshot_20210202_172603](https://user-images.githubusercontent.com/917239/106630355-0f2eaf80-657c-11eb-8b7c-7f9c62cec2e7.png)

- user with many edits adds landuse=village_green
- gets tagged as Park added by new user

## What  is the expected behaviour ?

- experienced user adds landuse=village_green
- nothing happens

## When does this occur ?

Doesn't seem to be always reproducible.

## How do we replicate the issue ?

First occurence so far. Hesitating to map for the renderer...

## Please tell us about your environment:

n/a, tag is shown regardless of client environment

**Comment by weech** [comment]
[Here's another instance](https://osmcha.org/changesets/99118358) of this bug, this time with the "waterbody added by new user" lint, in case it helps.
![image](https://user-images.githubusercontent.com/21208007/107684908-5817ef80-6c71-11eb-8d12-90c557f3338a.png)

**Comment by bugdebugger** [comment]
The wrong tagging by the `new_user_*` comparators seems to be flaky.

Was previously reported here mapbox/osm-compare#180 and here #193 

Only some changesets (by user Hlav) are tagged incorrectly.
Other changesets (by user Hlav) e.g. https://osmcha.org/changesets/98983377 were not tagged, although a new way which matches the park definition from [mapbox/osm-compare](https://github.com/mapbox/osm-compare/blob/master/lib/park.js) was added.

Judging by the code from the `mapbox/osm-compare` repository this shouldn't happen.

It seems the information used in [mapbox/osm-compare -> new_user.js](https://github.com/mapbox/osm-compare/blob/master/comparators/new_user.js) might come from the [osm-comments-api](willemarcel/osm-comments-api) with `extra=true`. Not sure what to make of the missing underscore in `osm:user:changesetcount` (vs `changeset_count` from the API)

But I can't find where the code from the `mapbox/osm-compare` repo is actually called to do the tagging. So I don't really know where/how `newVersion` is "filled"

My guess is the osm-comments-api (or whatever is responsible for `osm:user:changesetcount` and `osm:user:mapping_days` ) is buggy and sometimes reports the wrong values. Maybe a fallback which returns 0 if a DB call times out

Or the code in the osm-compare repo is not the one used to generate those tags

**Comment by willemarcel** [comment]
We had some problems, but now it's fixed!
