### ISSUE TITLE
Incorrectly flagged as new mapper

### ISSUE THREAD

**Issue by cliffordsnow** [mapbox/osmcha-frontend#521]
## I'm submitting a _(bug report/feature request/ support or question)_
bug report

## *Brief Description*

edits with waterbody and pokemon features default to feature added by new user. 

## What  is the current behaviour, (attach relevant screenshots) ?

![Not new users](https://mycloud.snowandsnow.us/index.php/s/JRkNG9fYSFPrzrw)
See https://osmcha.org/changesets/100298873
or https://osmcha.org/changesets/100301265

## When does this occur ?

when a pokemon or waterbody feature is added.
## How do we replicate the issue ?

1.
2.
3.
4.

## Other Information / context:

The two users shown in the image, Glassman and Carnildo are both long time mappers.

**Comment by ScottWalkerAU** [comment]
See #505

**Comment by cliffordsnow** [comment]
I missed that issue. Closing as duplicate of #505.
