### ISSUE TITLE
Search filter data entered as "Other metadata" appears to be ignored.

### ISSUE THREAD

**Issue by SomeoneElseOSM** [mapbox/osmcha-frontend#533]
Someone mentioned https://www.openstreetmap.org/changeset/87218552 , and I noticed the odd changeset tag there "closed:improveosm", and I'd like to search for that changeset tag field.  Unfortunately, although at https://osmcha.org there are lots of possible filter fields, and some do correspond to changeset tags ("Editor" I presume is trying to search the "created_by" changeset tag) it doesn't appear possible to search by some text that I type in.  There is a field "Other metadata" but data entered there has no impact on search results.

If I type "djakjdshakjjdshakjdhakjdhaksjdhakdjhak" in that field I'd expect to see only changesets with that as a changeset tag (i.e. none) but instead I see a lot (presumably all) changesets.

**Comment by willemarcel** [comment]
Hi @SomeoneElseOSM 

That filter works, you can use `closed:improveosm=*` on the other metadata field to query any value. We started registering all the metadata of the changeset on the database only in September that year. You can see some changesets here: https://osmcha.org/?filters=%7B%22metadata%22%3A%5B%7B%22label%22%3A%22closed%3Aimproveosm%3D%2A%22%2C%22value%22%3A%22closed%3Aimproveosm%3D%2A%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%222020-08-01%22%2C%22value%22%3A%222020-08-01%22%7D%5D%7D 

Yes, Editor is the created_by tag.

**Comment by SomeoneElseOSM** [comment]
Thanks - it was the "=*" that I was missing.
