### ISSUE TITLE
Checklist for launch

### ISSUE THREAD

**Issue by rasagy** [mapbox/osmcha-frontend#54]
Listing things that we should try to include (must have + good to have) when we release the new beta.

1. **Good About page**: More detail about what the tool is, what validation is about, what flags mean, and a bit about repo, licensing + Mapbox etc.
2. **Welcome to NEW OSMCha modal**: Highlight the major changes in the new UI
3. **Walkthrough**: (Optional) Step-by-step list of UI highlights

cc @kepta @batpad @geohacker

**Comment by kepta** [comment]
cc @jinalfoflia

**Comment by rasagy** [comment]
Focusing on two screens: a modal for new user to explain the new features+summarize what you can do on OSMCha, and a default screen for details view when no changeset is selected.

For the modal, I’m thinking of a full-page splash screen as follows:

![mapbox work process_19](https://user-images.githubusercontent.com/1117531/27075559-2823ff4c-5048-11e7-8580-fba8c249e5b3.jpg)

1. Welcome message
1. What is OSMCha? (One liner)
1. Highlight the core features
1. Primary call-to-action (get started), secondary (know more about OSMCha)

In the default screen for the details view, I thought about exploring minimal coach marks or a short message with an overview of the UI:

![mapbox work process_18](https://user-images.githubusercontent.com/1117531/27077569-21d40a3c-504e-11e7-9472-aef494d68f93.jpg)

![mapbox work process_17](https://user-images.githubusercontent.com/1117531/27077582-2b3258cc-504e-11e7-9f0a-f232b6e09b89.jpg)

Coach marks are [notorious for being overused](https://www.nngroup.com/articles/mobile-instructional-overlay/), and getting [the placeholder UI](https://medium.com/anatomy-of-web-interface/placeholder-loading-ui-bbaf2222f95f) as sketched above might require some extra-work, so I’m going to try a mix of minimal coach marks + short message.

**Comment by kepta** [comment]
@rasagy could give me an `HTML` template for this. Since it is mostly static and I can easily port it to react.

**Comment by jinalfoflia** [comment]
> Good About page: More detail about what the tool is, what validation is about, what flags mean, and a bit about repo, licensing + Mapbox etc.

The about documentation is moving and is now part of OSMCha-frontend repo -
 https://github.com/mapbox/osmcha-frontend/blob/master/ABOUT.md

cc: @willemarcel

**Comment by rasagy** [comment]
Going to try and implement a default view like this:

![main illustration links](https://user-images.githubusercontent.com/1117531/27281316-01913596-5509-11e7-86b6-49d8ac8895f4.png)

Showing:
- OSMCha title
- Short description
- Main steps
- Link to documentation
- Link to repo, what’s new etc. with Assembly icons

**Comment by kepta** [comment]
This has worked well closing this ticket now.
@rasagy let me know if I missed anything.
