### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by pyrog** [mapbox/osmcha-frontend#560]
## *Brief Description*
When clicking on the comment tab of an issue, the screen is blank and the console display:
- Error: Invalid LngLat object: (NaN, NaN)
- RangeError: Invalid time value

## What  is the current behaviour, (attach relevant screenshots) ?
<img width="33%" alt="changesets" src="https://user-images.githubusercontent.com/2158081/124359256-72546900-dc24-11eb-8ac3-8bb1f8f085b3.png"> <img width="33%" alt="crash"  src="https://user-images.githubusercontent.com/2158081/124359075-9e231f00-dc23-11eb-8dd4-0e579580b38e.png">

## What  is the expected behaviour ?
Display comments of the current changeset

## When does this occur ?
On clicking on the Comments tab.
~~But for **filtered changesets by Number of comments ≥ 1**~~

## How do we replicate the issue ?
1. Open this [filter](https://osmcha.org/changesets/107356862/?filters=%7B%22comments_count__gte%22%3A%5B%7B%22label%22%3A%221%22%2C%22value%22%3A%221%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%7D) or simply this [changeset](https://osmcha.org/changesets/107356862/)
2. click on the comments tab of one changeset

## Please tell us about your environment:
- macOS Big Sure
- tested with Chrome, Safari and Firefox

**Comment by pyrog** [comment]
Also got `Changeset:107360433 Map failed.null is not an object (evaluating 't.to.toString')` for this [filter](https://osmcha.org/changesets/107360433/)
<img width="22%" src="https://user-images.githubusercontent.com/2158081/124360649-3ffa3a00-dc2b-11eb-8ebd-b1dae72425fe.png">

**Comment by Dubs120** [comment]
I replicated the issue on Debian 10 XFCE / Firefox 78.11.0esr

**Comment by willemarcel** [comment]
Thanks for the report, @pyrog ! I have already fixed it and OSMCha will be updated on Monday.

> Also got `Changeset:107360433 Map failed.null is not an object (evaluating 't.to.toString')` for this [filter](https://osmcha.org/changesets/107360433/)

It works now. Maybe when you loaded it, the visualization was not ready yet.

**Comment by pyrog** [comment]
Thank you very much Wille 😃
