### ISSUE TITLE
Changes to support Rovas integration

### ISSUE THREAD

**Issue by alexanderzatko** [mapbox/osmcha-frontend#568]
I'm submitting a feature request

*Brief Description*

There is a new application [Rovas](https://rovas.app/)* available to the OSM editors that allows them among other things to create permanent reports of their editing time and have them verified by other users. To make the report creation easy a [JOSM plugin](https://gitlab.com/JOSM/plugin/RovasConnector) was developed that times the edits made and upon uploading the job to the OSM database creates a report in Rovas. For every published report Rovas picks two verifiers and sends them email invitations with URL links where they can see "the map" changes, in order to make a judgement about accuracy of the reported times. They can then either approve or reject the report. The verification links currently display the created changeset in the Achavi application. For several reasons mentioned below we would like to switch to Osmcha.

\* Rovas is an application of community economic system NEO, whose reason for existence is to make volunteer work visible, reward them for their work and improve funding of volunteer projects.

## What is the motivation / use case for this feature?

The main reason the Rovas integration uses Achavi is that users do not need to log into the app to see a changeset. We need anonymous access, as in rare cases the verifiers chosen might not have OSM account. Regardless, Osmcha seems to be a better candidate for our use case, as Achavi is lacking features Osmcha has, or could provide that we would like to offer to the verifiers. Below is the list of changes with the most important at the top that we would like to see in Osmcha. We imagine the modifications could be revealed/triggered upon detection of a specially formatted URL.

1. make logging into Osmcha optional to see a changeset. This mode could be switched to by detecting URL containing a specific parameter. This feature would allow us to start using Osmcha immediately as a verification tool
2. support ability to control the list displayed in the block (on the left of the screen) that currently displays the newly-created changesets. Ideally there would be a way to populate the list from changeset IDs provided in the URL. This would address situations when a verifier has to verify multiple changesets at once
3. Provide a new section in the existing popup that would allow the verifiers to verify the labor time reported in Rovas work report directly in the Osmcha application. There is a Rovas API the function would use.

These are the main features we would need to support our use case. We believe implementing them could lead to greater usage of the Osmcha application (by the Rovas users) while being invisible to its "regular" users. The first two features could be useful to support use cases not specific to Rovas and could therefore be conceivably implemented into the existing production version of Osmcha. The 3rd one is Rovas specific, but also needed the least.

We can sponsor implementing these changes.

**Comment by willemarcel** [comment]
Hi @alexanderzatko 

> make logging into Osmcha optional to see a changeset. This mode could be switched to by detecting URL containing a specific parameter. This feature would allow us to start using Osmcha immediately as a verification tool

We require login because of the [GDPR](https://wiki.openstreetmap.org/wiki/GDPR), so we don't expose any user information to unauthenticated users.

> support ability to control the list displayed in the block (on the left of the screen) that currently displays the newly-created changesets. Ideally there would be a way to populate the list from changeset IDs provided in the URL. This would address situations when a verifier has to verify multiple changesets at once

This filter is already available. Check "Changeset IDs" field on the [Filters page](https://osmcha.org/filters).

> Provide a new section in the existing popup that would allow the verifiers to verify the labor time reported in Rovas work report directly in the Osmcha application. There is a Rovas API the function would use.

In this case, probably it would be better if you embed OSMCha or [changeset-map](https://github.com/osmlab/changeset-map/) in your application, as I believe it would require to pass some authentication to Rovas and control which users could submit information.

**Comment by alexanderzatko** [comment]
Thank you for responding. Could you maybe be more specific please with the GDPR issue? It seems to me only publicly accessible data is shown, but I am not that familiar with the app ... as the 2nd point illustrates..

... yes, I just discovered this - that's great. :-)

Yeah, that could be a way. We could also create a custom version of OSMcha, as Rovas is not really OSM specific. The point No. 3 is really not a showstopper, it's more like nice to have.

**Comment by alexanderzatko** [comment]
@willemarcel could you please clarify the GDPR issue? All I can see about the user in Osmcha seems to be the same info that is available on the user's public OSM profile page.

**Comment by willemarcel** [comment]
@alexanderzatko The understanding of the [Legal Working Group of the OSM Foundation](https://wiki.openstreetmap.org/wiki/File:GDPR_Position_Paper.pdf) is that any metadata that could identify a user, like usernames and user ids should be available only to logged-in users. Although the OSM website is yet exposing that information, since October 2018, OSMCha is compliant with the GDPR.

**Comment by alexanderzatko** [comment]
Thank you, that seems to be the most prudent approach a developer can make.
