### ISSUE TITLE
Undetected Fictional Mapping

### ISSUE THREAD

**Issue by adiatmad** [mapbox/osmcha-frontend#580]
Hi @willemarcel. I noticed that this changeset (https://osmcha.org/changesets/110699823/) contains suspicious objects and doesn't have any flag. Usually will be flagged as Fictional Mapping or something else.

![Screenshot from 2021-09-07 14-10-02](https://user-images.githubusercontent.com/38268616/132300473-28b21d0e-26f1-4414-8d8a-582fe88e5f5d.png)

**Comment by matkoniecz** [comment]
What could be a hint that it is fictional and fake data?

**Comment by adiatmad** [comment]
@matkoniecz Thank you for your reply. It looks good now on OSMCha. The only hint I have is my local knowledge, there are no multiple-polygons in the field rice like that. Also if you confirm using satellite imagery, there are no building as tagged.

**Comment by matkoniecz** [comment]
Note that automatic detection of that is extremely hard.

And some good edits, newer that aerial imagery used to check, would trriger it.

**Comment by adiatmad** [comment]
Yes, someone deleted them already.

OSMCha detected them well now, so I think I should close this ticket. Thank you for your discussion.
