### ISSUE TITLE
v0.83 is live and broken

### ISSUE THREAD

**Issue by cmoffroad** [mapbox/osmcha-frontend#588]
## *Brief Description*

Since a few days ago, OSMCha front-end does not show anymore the objects that have been modified inside any changesets including geometries on maps and inside popup details.

Console shows a potential endpoint issue:

```
Failed to load resource: the server responded with a status of 403 (Forbidden)
https://s3.amazonaws.com/mapbox/real-changesets/production/112039285.json

```

Also, current repository CI shows Failed.

## Please tell us about your environment:

Tested on Chrome 94 and Firefox  on Mac OSX.

**Comment by alexanderzatko** [comment]
Likely the same issue as #587

**Comment by willemarcel** [comment]
We have a problem in the overpass instance used by OSMCha. I'll update here when there is a solution to it.

**Comment by mmd-osm** [comment]
It's really unrelated to overpass itself. As has happened on other boxes, missing root certificates have stopped curl/wget from downloading minutely diff files from planet.openstreetmap.org.

See https://twitter.com/OSM_Tech/status/1443622725021577222 for discussion.

**Comment by willemarcel** [comment]
Finally the overpass is back and OSMCha is fully functional. Sorry for the inconveniences caused.

**Comment by alexanderzatko** [comment]
fantastic. thank you
