### ISSUE TITLE
Open in menu

### ISSUE THREAD

**Issue by willemarcel** [mapbox/osmcha-frontend#59]
* The link to `iD` is wrong, it should receive the coordinates of the current map view or of the first changeset map view, example: https://www.openstreetmap.org/edit?editor=id#map=15/-4.5650/-37.7613

* The `OSM` option is duplicated.

**Comment by kepta** [comment]
Thanks for reporting the bug, @willemarcel. Will fix it.

**Comment by kepta** [comment]
This was fixed in #58
