### ISSUE TITLE
support for "or" at OSM features tags filter

### ISSUE THREAD

**Issue by Langlaeufer** [mapbox/osmcha-frontend#623]
## *Brief Description*
OSM features tags filter is selecting objects with have all listed tags (AND)
Please at a support also OR to select feature with have at least one of the listed tags.

## What is the motivation / use case for this feature?
watching different tags in using only one filter to do not have duplicate listings of one object when different tags was changing

**Comment by RicoElectrico** [comment]
+1 - we have a problem of users changing major road classes without community consultation and manually monitoring `highway = motorway / trunk / primary / secondary` and their `*_link`  would be tedious.
