### ISSUE TITLE
Don't close Tags dropdown after selecting an option

### ISSUE THREAD

**Issue by willemarcel** [mapbox/osmcha-frontend#648]
## *Brief Description*
Normally we want to select more than one Tag, after reviewing a changeset, but the dropdown closes automatically after selecting one option
![image](https://user-images.githubusercontent.com/666291/222739162-10af724f-ee8d-484a-b700-320ef1021561.png)

## What is the motivation / use case for this feature?
If it doesn't close automatically after selecting an option, we would improve the experience and motivate users to add more tags.

**Comment by ArslanYM** [comment]
Can I work on this feature?

**Comment by willemarcel** [comment]
@ArslanYM Yes, you can. I noticed when we click on the input box, it doesn't close the dropdown, so maybe a solution is to include the label inside the input component.

**Comment by ArslanYM** [comment]
@willemarcel Will definitely keep that in mind. Have started working on this.
