### ISSUE TITLE
Fictional Mapping Suggestion

### ISSUE THREAD

**Issue by adiatmad** [mapbox/osmcha-frontend#656]
I believe that this can also be marked as "Fictional mapping." S/he uploaded the Tasking Manager project boundaries in some manner.

(https://osmcha.org/changesets/134938617/)

![Changeset 124938617](https://user-images.githubusercontent.com/38268616/232686699-16695710-0a9f-4fe8-8539-6fe51e2debc3.jpg)

**Comment by willemarcel** [comment]
@adiatmad The fictional mapping flag is made manually by the Mapbox team. I'll alert them about it. Thanks!
