### ISSUE TITLE
Filter name (BBox size bound) is not clear

### ISSUE THREAD

**Issue by ramen2581** [mapbox/osmcha-frontend#657]
Feature request: Change "BBox size bound" to something more descriptive like "Changeset size bound" or "Changeset size filter"

I have wanted a feature like this for while only to find out from a comment in https://github.com/mapbox/osmcha-frontend/issues/347 that it already exists. I believe a better label would improve utilization of the specific filter and of OSMcha as a whole because of frustrations when changesets with large areas continuously show up in local filters.

Thanks

**Comment by willemarcel** [comment]
@ramen2581 Thanks for the suggestion. I've addressed it in a PR. Soon the app will be updated.
