### ISSUE TITLE
Hide changesets that are still being processed

### ISSUE THREAD

**Issue by rasagy** [mapbox/osmcha-frontend#66]
The default list of changesets reflects all changesets, which means the most recent ones will have data that is still being processed. We should hide these so it doesn’t get confusing for people — in any case these won’t be usable till we fetch all the details.

<img width="1280" alt="screenshot 2017-06-12 16 13 52" src="https://user-images.githubusercontent.com/1117531/27031512-30945178-4f8e-11e7-9e3d-3226cae5c7a5.png">

cc @batpad @geohacker @kepta

**Comment by batpad** [comment]
Maybe this is something that the back-end should do.

cc @willemarcel do you think it makes sense for the back-end to filter out / not return changesets where we don't have metadata yet?

These basically happen when our feature processing pipeline is faster than the changeset processing -- so we get details for a suspicious feature before the changeset metadata has arrived, so create an "empty" changeset of sorts with just the feature detail attached to it.

Should we just filter out where like `user` is `null` or something similar where we know the changeset does not have metadata yet @willemarcel?

**Comment by willemarcel** [comment]
done in https://github.com/willemarcel/osmcha-django/commit/90f0f5c5c0cf395395a37be81ed21b1a5316ceae

**Comment by kepta** [comment]
This was fixed.
