### ISSUE TITLE
Mapbox tiles returning 403

### ISSUE THREAD

**Issue by pnoll1** [mapbox/osmcha-frontend#667]
## *Brief Description*
Mapbox tile requests being rejected with 403 for a couple months now.

## What  is the current behaviour, (attach relevant screenshots) ?
https://api.mapbox.com/v4/mapbox.mapbox-streets-v7.json?secure&access_token=pk.eyJ1Ijoib3BlbnN0cmVldG1hcCIsImEiOiJjam10OXpmc2YwMXI5M3BqeTRiMDBqMHVyIn0.LIcIDe3TZLSDdTWDoojzNg and https://api.mapbox.com/v4/mapbox.satellite.json?secure&access_token=pk.eyJ1Ijoib3BlbnN0cmVldG1hcCIsImEiOiJjam10OXpmc2YwMXI5M3BqeTRiMDBqMHVyIn0.LIcIDe3TZLSDdTWDoojzNg get 403 responses meaning no tiles are loaded

## What  is the expected behaviour ?
Tiles load

## When does this occur ?
For at least the last 2 months

## How do we replicate the issue ?
1. Go to osmcha.org
2. click on any changeset 

## Please tell us about your environment:
firefox 114

## Other Information / context:
Osm operations person thought key was rotated at Mapbox's request

**Comment by willemarcel** [comment]
@pnoll1 I'm not able to reproduce it. Could you record your screen and post a video here?

**Comment by pnoll1** [comment]
Sorry for the delay, hopefully a screenshot works
![20230628_01h28m21s_grim](https://github.com/mapbox/osmcha-frontend/assets/8444617/b1f4b0b2-e40e-4bd9-bab1-c31c68d5aa1b)

**Comment by pnoll1** [comment]
Switching to a different firefox profile solved the issue. I wasn't able to figure out which setting is causing the problem.
