### ISSUE TITLE
Can’t filter for #tags in comments

### ISSUE THREAD

**Issue by rasagy** [mapbox/osmcha-frontend#68]
For ex, searching for #hotosm in comments [doesn’t work](https://mapbox.github.io/osmcha-%20frontend/filters?filters=%7B%22comment%22%3A%5B%7B%22label%22%3A%22%23hotosm-project%22%2C%22value%22%3A%22%23hotosm-project%22%7D%5D%7D).

cc @kepta

**Comment by kepta** [comment]
nice catch @rasagy ,
will fix it.
