### ISSUE TITLE
osmcha.org not processing changesets

### ISSUE THREAD

**Issue by elevenchars** [mapbox/osmcha-frontend#687]
## *Brief Description*

The official osmcha.org instance has not processed any changesets in 9 hours.

## What  is the current behaviour, (attach relevant screenshots) ?

No new changesets show up in the osmcha.org homepage or any filters. Changesets from before [this changeset
](https://www.openstreetmap.org/changeset/142974027) are in the feed.

## What  is the expected behaviour ?

Changesets should appear in the feed after a short processing delay.

## When does this occur ?

Since `Sun, 22 Oct 2023 15:35:16 +0000`
## How do we replicate the issue ?

1. Open osmcha.org
2. Observe that the feed is not updating

## Please tell us about your environment:

N/A

## Other Information / context:

@willemarcel

**Comment by willemarcel** [comment]
@elevenchars thanks for the report. It seems the issue is solved now, isn't it?

**Comment by elevenchars** [comment]
Yes, it does seem to be caught up now. Thank you.
