### ISSUE TITLE
Validate input fields

### ISSUE THREAD

**Issue by rasagy** [mapbox/osmcha-frontend#69]
Fields like Filter dates needs basic checks so that invalid input should give an error. For ex: From is after to, to/from is in the future etc.

cc @kepta

**Comment by ajithranka** [comment]
We have some validation on the date and number ranges.
Please see [pull/141#issuecomment-311919086
](https://github.com/mapbox/osmcha-frontend/pull/141#issuecomment-311919086).

**Comment by kepta** [comment]
Closing this.
Feel free to open it in future.
