### ISSUE TITLE
Weird drop down behavior in Reasons filter

### ISSUE THREAD

**Issue by rasagy** [mapbox/osmcha-frontend#70]
- Reasons drop down `v` stops working (nothing happens on clicking) after adding 2 reasons
- If you add and remove reasons, then clicking on drop down gives no list

![osmcha-reasons-input](https://user-images.githubusercontent.com/1117531/27067171-0421ef94-5027-11e7-8c41-9b741d01568a.gif)

cc @kepta

**Comment by rasagy** [comment]
Might be related to #51.

**Comment by ajithranka** [comment]
cc: @manoharuss who's been facing the same issue.

**Comment by ajithranka** [comment]
This is a bit tricky to fix. Deferring for later.

**Comment by kepta** [comment]
@tridip1931 can you take a look at this one?

**Comment by tridip1931** [comment]
## Debugging

I believe this is the issue of the `react-select` library. 

It kinda messes up when using `Async`

It also does not work in the [Official Demo Page](https://jedwatson.github.io/react-select/)
![alt-image](https://cloud.githubusercontent.com/assets/8257269/22774318/986d25e0-eecc-11e6-82a0-83c8ed4d2ceb.gif)

Any thoughts on this? 

**cc:/** @kepta @batpad

**Comment by tridip1931** [comment]
It was fixed in 👉  release [https://github.com/JedWatson/react-select/releases/tag/v1.0.0-rc.9](https://github.com/JedWatson/react-select/releases/tag/v1.0.0-rc.9)
