### ISSUE TITLE
Improve changeset header buttons

### ISSUE THREAD

**Issue by rasagy** [mapbox/osmcha-frontend#76]
Listing quick fixes that we should do for the header:

![image](https://user-images.githubusercontent.com/1117531/27125187-188bf2c8-5111-11e7-8b0a-cd20c2beef1b.png)

---

- [x] **Add an explicit `Open in v` button**
![image](https://user-images.githubusercontent.com/1117531/27125180-11068482-5111-11e7-993f-ee40556ce825.png)
The current design makes it slight difficult to discover this, and making just the `v` clickable makes it less usable. We should either make the whole changeset id a drop down button that lists different tools, or add an explicit button that lists these. I prefer the latter, since it’ll be easy to recognize and stay consistent with our buttons across the design `verb v`.

- [ ] **Show `Verify` first, `Tags` disabled, and highlight `Tags` only when changeset is verified**

![osmcha-verify-3](https://user-images.githubusercontent.com/1117531/27125434-d612b728-5111-11e7-9f2e-d518ad3da8c5.gif)

- [x] **Update the list of tags to match the current OSMCha**

![image](https://user-images.githubusercontent.com/1117531/27125795-0f34a4a2-5113-11e7-87cf-6a5ff693de61.png)

- [x] Right align drop downs for verify & tags?

![osmcha-verify-4](https://user-images.githubusercontent.com/1117531/27125516-2a43bf9a-5112-11e7-9f9f-effb2946cb51.gif)

We should use the same emoji 👍 👎 in the drop down (to make it consistent), and ideally right align the list so it doesn’t get cut by the screen edge. This is not a blocker, and we can fix this in our next iteration.

cc @kepta

**Comment by kepta** [comment]
@rasagy `Update the list of tags to match the current OSMCha` can you explain more ?

**Comment by rasagy** [comment]
@kepta That was same as https://github.com/mapbox/osmcha-frontend/issues/86, now fixed.
