### ISSUE TITLE
Timings of discussions not showing up appropriately

### ISSUE THREAD

**Issue by krishnanammala** [mapbox/osmcha-frontend#78]
Noticed that in this changeset https://www.openstreetmap.org/changeset/49413231. The discussions has a time gap between them, but in the discussions icon it was showing up the same for all 👇 

![screen shot 2017-06-14 at 5 51 58 pm](https://user-images.githubusercontent.com/17470597/27132008-c52d0a26-512a-11e7-8a97-8df8c3ae63b0.png)

cc @kepta @batpad @geohacker @rasagy @manoharuss

**Comment by kepta** [comment]
This was fixed in #67
