### ISSUE TITLE
Default URL has a date filter

### ISSUE THREAD

**Issue by manoharuss** [mapbox/osmcha-frontend#79]
Observed that when we open OSMCha with https://mapbox.github.io/osmcha-frontend, by default a date filter is enabled to filter changesets that are after 08/6/2017

![image](https://user-images.githubusercontent.com/8921295/27175079-b4280a76-51db-11e7-8b35-86a95bf9f61f.png)

cc @kepta @geohacker @rasagy

**Comment by willemarcel** [comment]
@manoharuss see https://github.com/mapbox/osmcha-frontend/issues/73

**Comment by manoharuss** [comment]
@willemarcel thank you. This was intentional. Closing.
