### ISSUE TITLE
For really old changesets, OSMCha panels don’t load.

### ISSUE THREAD

**Issue by rasagy** [mapbox/osmcha-frontend#82]
Tried opening this changeset: https://mapbox.github.io/osmcha-frontend/changesets/2525433

It took a while to load (gave an error: `GET https://s3/…/production/2525433.json 403 (Forbidden)`) and a loooong `uncaught at s TypeError: Cannot read property 'get' of undefined` error.

![image](https://user-images.githubusercontent.com/1117531/27182201-097316c6-51f8-11e7-9e97-6d6e58c3617b.png)

This is a super old changeset — we should show an error in this case. cc @kepta

**Comment by kepta** [comment]
Was fixed with showing an error.
