### ISSUE TITLE
Improper link in source field

### ISSUE THREAD

**Issue by willemarcel** [mapbox/osmcha-frontend#84]
This [changeset](https://osmcha-django-staging.tilestream.net/changesets/49593249/) has `"source": "fabio/bruno"` what is generating a link to https://osmcha-django-staging.tilestream.net/changesets/fabio/bruno in the source area of the interface.

API page of the changeset: http://osmcha-django-staging.tilestream.net/api/v1/changesets/49593249/

**Comment by kepta** [comment]
This would be fixed in 1.2

**Comment by tyrasd** [comment]
A similar thing happens with the imagery_used field also, like here: https://osmcha.mapbox.com/changesets/51268021 (the layer's name is `South Tyrol Orthofoto 2014/2015`)

**Comment by naoliv** [comment]
Is it the same problem from https://osmcha.mapbox.com/changesets/55358267/ ?
See that the original source is `Bing; IBGE - Mapa das áreas rurais; Imagens Standard da DigitalGlobe; http://scdl.itamaraty.gov.br/pt-br/fronteiras_da_scdl.xml` while osmcha displays it as `Bing; IBGE - Mapa das áreas rurais; Imagens Standard da DigitalGlobe; _da_scdl.xml http://scdl.itamaraty.gov.br` (ie, it's even changing the order of the words for the last link)

**Comment by tridip1931** [comment]
thanks @naoliv for pointing this out, it was a `regex` issue
