### ISSUE TITLE
Change place holder tags to reflect real ones in our current workflow

### ISSUE THREAD

**Issue by manoharuss** [mapbox/osmcha-frontend#86]
![image](https://user-images.githubusercontent.com/8921295/27284770-c6a841ea-5517-11e7-8e1c-b8ffd4f5cd3c.png)
_current workflow_

![image](https://user-images.githubusercontent.com/8921295/27284922-553525c2-5518-11e7-99bf-3eaeff1ee233.png)
_place holder tags right now_

The tags in the new osmcha version are not the same as the ones in our current workflow. @kepta @rasagy it would be great if you can change these

cc @geohacker @batpad

**Comment by kepta** [comment]
@manoharuss these are not placeholder tags and being served by server.
Once the server changes these which might happen when we switch to production database.
