### ISSUE TITLE
A better homepage view

### ISSUE THREAD

**Issue by kepta** [mapbox/osmcha-frontend#88]
copying from https://github.com/mapbox/osmcha-frontend/issues/54
carrying forward @rasagy's work.

**Comment by rasagy** [comment]
Reposting here.

Aim to create the homepage section as:

![main illustration links](https://user-images.githubusercontent.com/1117531/27318849-06b25156-55ac-11e7-9459-9a5d59314eab.png)

Individual images:

![osmcha-logo](https://user-images.githubusercontent.com/1117531/27318915-5eefbf84-55ac-11e7-95dd-be9b7b2b0064.png)
![osmcha-steps](https://user-images.githubusercontent.com/1117531/27318916-5ef0af98-55ac-11e7-8a9c-50c1fd3a3b5e.png)

I’m going to work on the markup so this works across screen resolutions.

cc @ajithranka @kepta

**Comment by kepta** [comment]
This was done.
