### ISSUE TITLE
Using a component library

### ISSUE THREAD

**Issue by ajithranka** [mapbox/osmcha-frontend#9]
To speed up design & development time, I think it might be useful to rely on a react component library instead of using assembly. AFAIK, assembly does not have an extensive library of React components.

Let's assess these

- React Bootstrap: https://react-bootstrap.github.io/components.html
- React Material UI: http://www.material-ui.com/#/components/app-bar
- React Semantic UI: http://react.semantic-ui.com/introduction
- Grommet: https://grommet.github.io/docs/components

Some considerations

- Ease of designing responsive layouts
- Extensive collection of complex form components
- Stability and popularity of the library

Ref #8.
cc: @kepta @rasagy @batpad @geohacker

**Comment by kepta** [comment]
Semantic UI 👍

**Comment by lukasmartinelli** [comment]
> To speed up design & development time, I think it might be useful to rely on a react component library instead of using assembly. AFAIK, assembly does not have an extensive library of React components.

**I would try to make it work with Assembly CSS** and build your own components if you need to.
You will start to build out your own components once you progress in the development anyway.
It's also not that much gain for many basic components from an external library.

A lot of complex components can also be find as separate library - instead of relying on a huge component library.

**Comment by rasagy** [comment]
Based on a quick huddle yesterday evening with @kepta, @ajithranka & @batpad, it makes more sense to invest time in using Assembly: it brings us closer to our vision of a cohesive design language across such internal/open tools, and also helps us dog-food and share feedback with the Assembly team. As @lukasmartinelli said, let’s make it work with Assembly CSS. 🎉 

I had a quick chat with @samanpwbb regarding this as well, and will try to do regular syncs with him & @davidtheclark when we get started on this.

**Comment by ajithranka** [comment]
Closing. We'll go ahead with assembly.
