### ISSUE TITLE
Why does the front-end eat up URLs?

### ISSUE THREAD

**Issue by batpad** [mapbox/osmcha-frontend#96]
So if I try to navigate to a URL like https://osmcha.mapbox.com/api/v1/changesets, the frontend seems to grab the URL and not pass it on to the back-end.

I have no idea how it does this or why, but is there a way to make it stop? It's making debugging back-end issues a bit weird.

cc @kepta @geohacker

**Comment by kepta** [comment]
@batpad this was fixed in v0.16.1, I have list of whitelisted urls. 
I will open another ticket for discussing on how to handle urls more transparently.

**Comment by geohacker** [comment]
@kepta I don't think this is entirely fixed. Some cases:

* https://osmcha.mapbox.com/api - instead of a 404, takes me to the app. 
* go to https://osmcha.mapbox.com/api-docs/
  * click django login - takes me the app instead of django login?

Can you explain on this ticket what kind of URL overrides/state changes are happening on the front-end? Thank you!

**Comment by kepta** [comment]
@geocacher as per conversation with @willemarcel I white listed the urls that he mentioned. 

service workers configuration documented in the 7th point  [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#offline-first-considerations)

The white listing code can be found [here](https://github.com/mapbox/osmcha-frontend/blob/master/config-overrides.js)

```Javascript 

const NAVIGATE_FALLBACK_WHITELIST = [
  /^(?!.*\.html$|\/data\/|\/admin|\/api-docs|\/api\/).*/
];
```
So all the urls that we want to white list will go in the above reflex ^^

**Comment by willemarcel** [comment]
@kepta Everything is fine with the frontend. The urls that @geohacker tried to access are not configured in the backend.

> https://osmcha.mapbox.com/api - instead of a 404, takes me to the app.
`/api` only is not a valid url, as we don't have a view configured on it. The same to `/api/v1/`... it only works if you access a complete url like `/api/v1/changesets/`. All 404 errors in the backend URLs are redirected to the frontend.

>     click django login - takes me the app instead of django login?
The django login button was wrongly configured. I removed that button and configured the **Authorize** button to receive the user Token and use it in the api-docs requests. If you need some additional information on how to use it, tell me, @geohacker. https://github.com/willemarcel/osmcha-django/pull/106

**Comment by kepta** [comment]
@geohacker @willemarcel we good to close this?

**Comment by willemarcel** [comment]
@kepta for me, yes

**Comment by geohacker** [comment]
✌️ thank you for the explanation @willemarcel @kepta!
