### ISSUE TITLE
Document the build process

### ISSUE THREAD

**Issue by geohacker** [mapbox/osmcha-frontend#97]
@kepta what does `yarn build` do? what does oh-pages do?

**Comment by ajithranka** [comment]
Thanks @kepta for updating [the workflow](https://github.com/mapbox/osmcha-frontend#workflow)!

@geohacker Let us know if you see anything missing from the documentation. I'll pair up with @kepta for a deploy today.

**Comment by kepta** [comment]
This was fixed in [commit](https://github.com/mapbox/osmcha-frontend/commit/0a9c9d020184e914b07b1bf5fc90d3640857120a) Closing this.
