### ISSUE TITLE
URL shortener?

### ISSUE THREAD

**Issue by geohacker** [mapbox/osmcha-frontend#98]
Should we use a URL shortener? 

http://osmcha.mapbox.com/?filters=%7B%22reasons%22%3A%5B%7B%22label%22%3A%22Large%20building%20added%20by%20new%20user%22%2C%22value%22%3A47%7D%2C%7B%22label%22%3A%22Pokemon%20nest%20feature%20added%20by%20new%20user%22%2C%22value%22%3A50%7D%2C%7B%22label%22%3A%22Edit%20to%20city%2Ftown%20place%22%2C%22value%22%3A46%7D%2C%7B%22label%22%3A%22Profanity%20tag%22%2C%22value%22%3A45%7D%2C%7B%22label%22%3A%22Road%20mapped%20with%20a%20polygon%22%2C%22value%22%3A51%7D%2C%7B%22label%22%3A%22Waterbody%20added%20by%20new%20user%22%2C%22value%22%3A49%7D%2C%7B%22label%22%3A%22Large%20feature%20by%20new%20user%22%2C%22value%22%3A52%7D%2C%7B%22label%22%3A%22Major%20park%20name%20changed%22%2C%22value%22%3A48%7D%2C%7B%22label%22%3A%22Straight%20segment%20in%20feature%22%2C%22value%22%3A53%7D%2C%7B%22label%22%3A%22Wikitags%20deleted%22%2C%22value%22%3A56%7D%2C%7B%22label%22%3A%22Primary%20tag%20added%20to%20mature%20feature%22%2C%22value%22%3A58%7D%2C%7B%22label%22%3A%22Impossible%20angle%20in%20a%20highway%22%2C%22value%22%3A70%7D%2C%7B%22label%22%3A%22City%2Ftown%20changed%20type%22%2C%22value%22%3A60%7D%2C%7B%22label%22%3A%22New%20city%2Ftown%20created%22%2C%22value%22%3A61%7D%2C%7B%22label%22%3A%22Name%20of%20city%2Ftown%20changed%22%2C%22value%22%3A62%7D%2C%7B%22label%22%3A%22New%20user%20deleted%20a%20mature%20feature%22%2C%22value%22%3A66%7D%2C%7B%22label%22%3A%22New%20user%20added%20a%20footway%22%2C%22value%22%3A67%7D%2C%7B%22label%22%3A%22Trunk%2Fmotorway%20deleted%20by%20new%20user%22%2C%22value%22%3A69%7D%5D%2C%22checked%22%3A%5B%7B%22label%22%3A%22No%22%2C%22value%22%3A%22False%22%7D%5D%7D

cc @kepta @ajithranka @batpad

**Comment by willemarcel** [comment]
When we have the `AoI` implemented in the frontend, the user can save the filter and a URL to share like `http://osmcha.mapbox.com/aoi/<uuid>/`

**Comment by kepta** [comment]
will open a new ticket when we start with AoIs.

Closing this for now. 

cc @geohacker @willemarcel
